library(shiny);library(markdown)
shinyUI(fluidPage(headerPanel("Health Index"),
                  sidebarPanel(width=3,
                               textInput("Site","SiteID",value=NA),
                               textInput("ID","IndividualID",value=NA),
                               textInput("File","filePath",value="../../data/HealthIndex"),
                               selectInput("Type","File Type",c(".txt",".xls")),
                               actionButton("Append","Add record"),
                               textOutput("Add")),
                  mainPanel(
                            column(width=4,
                                   h4("Demographic fields"),
                                   selectInput("Sex","Sex",c("Female"=1,"Probable Female"=2,"Male"=3,"Probable Male"=4,"Juvenille"=5,"Unknown"=6)),
                                   numericInput("Age1","Summary Age (best estimate)",value=NA),
                                   conditionalPanel("input.Sex==5",numericInput("Age2","Dental Age",value=NA)),
                                   sliderInput("Age3","Age Range",min=0,max=100,value=c(40,60)),
                                   numericInput("DOB","Date of Birth",value=1900),
                                   selectInput("Ancestry","Continental Ancestry",c("Native American"=1,"European"=2,"African"=3,"Asian"=4,"Mixed"=5,"Unknown"=6)),
                                   selectInput("SOC1","stratification category of the society",selected=111,c("undifferentiated"=111,"Ranked"=2,"Class"=3)),
                                   conditionalPanel("input.SOC1!=111",numericInput("SOC2","number of distinct social strata",value=1),
                                   uiOutput("SOC3")),
                                   h4("Height and growth"),
                                   conditionalPanel("input.Sex==5",numericInput("FDIAP","Maximum diaphyseal length of femora(mm)",value=NA)),
                                   numericInput("FLEN","Maximum length of femur(mm)",value=NA),
                                   numericInput("HEIGT","Height(mm)",value=NA),
                                   h4("Robusticity"),
                                   numericInput("FMIDA","Mid shaft Anteriorposterior femoral diameter(mm)",value=NA),
                                   numericInput("FMIDM","Mid shaft Mediolateral femoral diameter(mm)",value=NA),
                                   numericInput("HLEN","Humerus maximum length(mm)",value=NA),
                                   numericInput("HCIR","Mid shaft humeral circumference(mm)",value=NA),
                                   br(h1()),
                                   br(h1()),
                                   br(h1())
                                   ),
                            column(width=4,
                                   h4("Enamel Hypoplasia"),
                                   selectInput("LDI","Left Decidous Incisor",c("Not observable"=0,"No Hypoplasia"=1,"One hypoplasia"=2,"Two or more hypoplasias"=3)),
                                   selectInput("LDC","Left Decidous Canine",c("Not observable"=0,"No Hypoplasia"=1,"One hypoplasia"=2,"Two or more hypoplasias"=3)),
                                   selectInput("LPI","Left Perminant Incisor",c("Not observable"=0,"No Hypoplasia"=1,"One hypoplasia"=2,"Two or more hypoplasias"=3)),
                                   selectInput("LPC","Left Perminant Canine",c("Not observable"=0,"No Hypoplasia"=1,"One hypoplasia"=2,"Two or more hypoplasias"=3)),
                                   h4("Dental Disease"),
                                   numericInput("SUMTET","Number of perminant teeth observed",value=NA),
                                   numericInput("SUMPRE","Number of perminant teeth lost antemortem",value=NA),
                                   numericInput("SUMCAV","Number of perminant teeth with lesions or restorations",value=NA),
                                   numericInput("SUMSOK","Number of sockets observed",value=NA),
                                   numericInput("SUMABS","Number of abscesses",value=NA),
                                   h4("Anemia"),
                                   selectInput("CROB","Cribra Orbitalia",c("No orbits to observe"=0,"Absent on at least one observable orbit"=1,"presence of a lesion"=2,"gross lesions,excessive expansion and large area of exposed diploe"=3)),
                                   selectInput("PORHY","Porotic Hyperostosis",c("No parietals observed"=0,"Absent on at least one observable parietal"=1,"Presence of a lesion"=2,"gross lession,excessive cranial expansion and huge areas of exposed diploe"=3)),
                                   h4("Auditory Exostosis"),
                                   selectInput("AUDEX","Exostosis",c("at least one auditory meatus not present for observation"=0,"No exostosis"=1,"Exostosis present"=2)),
                                   h4("Infection"),
                                   selectInput("TIBINF","Tibial Score",c("No tiba present"=0,"No infection"=1,"Slight/ small discrete patch(s)(<1/4 tibia(e) surface)"=2,"Moderate reaction (<1/2)"=3,"Severe reaction(>1/2)"=4)),
                                   selectInput("SKELINF","Remainer of skeleton",c("No periosteal reaction on rest of skeleton"=0,"Periosteal reaction not caused by trauma"=1,"Evidence of systemic infection"=2)),
                                   br(h1()),
                                   br(h1()),
                                   br(h1())),
                            column(width=4,
                                   h4("Degenerative joint disese"),
                                   selectInput("DJSH","Shoulder and elbow",c("Not available"=0,"No signs of DJD"=1,"intial osteophytes and degeneration of surface"=2,"major osteophytes and/or destruction"=3,"Immobilization of joint"=4,"Systemic degenerative disease"=5)),
                                   selectInput("DJHK","Hip and Knee",c("Not available"=0,"No signs of DJD"=1,"intial osteophytes and degeneration of surface"=2,"major osteophytes and/or destruction"=3,"Immobilization of joint"=4,"Systemic degenerative disease"=5)),
                                   selectInput("DJCER","Cervical",c("Not observable"=0,"No lesions"=1,"Intial osteophyte formation along rim"=2,"extensive osteophytes"=3,"2 or more vertebrae fused"=4)),
                                   selectInput("DJTHO","Thorasic",c("Not observable"=0,"No lesions"=1,"Intial osteophyte formation along rim"=2,"extensive osteophytes"=3,"2 or more vertebrae fused"=4)),
                                   selectInput("DJLUM","Lumbar",c("Not observable"=0,"No lesions"=1,"Intial osteophyte formation along rim"=2,"extensive osteophytes"=3,"2 or more vertebrae fused"=4)),
                                   selectInput("DJTMJ","TMJ",c("Not observable"=0,"No deterioration"=1,"DJD"=2)),
                                   selectInput("DJWR","Radio-ulnar joint",c("Not observable"=0,"No deterioration"=1,"DJD"=2)),
                                   selectInput("DJHAN","Hand",c("Not observable"=0,"No deterioration"=1,"DJD"=2)),
                                   h4("Trauma"),
                                   selectInput("TRARM","Arm",c("No long bones available"=0,"not fractured"=1,"Healed with acceptable alignment"=2,"Healed and poorly aligned"=3,"healed with fusion"=4,"healed with alignment unknown"=5)),
                                   selectInput("TRLEG","Leg",c("No long bones available"=0,"not fractured"=1,"Healed with acceptable alignment"=2,"Healed and poorly aligned"=3,"healed with extreme loss of locomotor function"=4,"healed with alignment unknown"=5)),
                                   selectInput("TRNAS","Nasal and Nasal process",c("No bones available"=0,"not fractured"=1,"Healed fracture"=2)),
                                   selectInput("TRFAC","Face other than Nasal",c("No bones available"=0,"not fractured"=1,"Healed fracture"=2)),
                                   selectInput("TRHAN","Hand",c("No bones available"=0,"not fractured"=1,"Healed fracture(s)"=2)),
                                   selectInput("TRWEAP","Weapon Wounds",c("None"=1,"Weapon wound(s)"=2)),
                                   br(h1()),
                                   br(h1()),
                                   br(h1()))
                            )))