#Lefort1####
Lefort1_UI<-tagList(fixedPage(h3("Lefort1 Fracture Description"),
                              h5("Please check the details in this section if any do not match your fracture use Custom to enter an accurate description"),
                              column(width=4,h4("Type"),
                                     selectInput("Lefort1_NLine","Number of fracture lines",c("Single-1")),
                                     selectInput("Lefort1_Complete","Complete Fracture?",c("TRUE")),
                                     selectInput("Lefort1_Type","Type of fracture",c("Other")),
                                     selectInput("Lefort1_Type2","Define Other",c("Lefort")),
                                     selectInput("Lefort1_Pattern","Fracture Pattern",c("Other")),
                                     selectInput("Lefort1_Pattern2","Define Other","Transverse curved fracture line passing along the alveolar ridge separtating the teeth from the upper face")),
                              column(width=4,h4("Location"),
                                     selectInput("Lefort1_Loc1","Region",c("Skull")),
                                     selectInput("Lefort1_Loc2","Bone",c("Maxilla Sphenoid")),
                                     selectInput("Lefort1_Loc3","Overall Location Decription",c("Curve across the base of the nasal aperture along the alveolar ridge to the canine fossa and lateral maxilla, effects anterolateral margins of the nasal fossa, maxillary sinus and ptergoid plate"))),
                              column(width=4,h4(br()),
                                     strong("Maxilla"),
                                     selectInput("Lefort1_Loc4","Side",c("Can be either or both")),
                                     selectInput("Lefort1_Loc5","Surface",c("Endocranial/Ectocrnial")),
                                     selectInput("Lefort1_Loc6","Feature",c("alveolar process/anterior nasal spine/maxillary sinus/Canine fossa")),
                                     selectInput("Lefort1_Loc7","Sutures",c("intermaxillary/sphenomaxillary")),
                                     strong("Sphenoid"),
                                     selectInput("Lefort1_Loc8","Feature",c("Pterygoid process")),
                                     selectInput("Lefort1_Loc9","Sutures",c("sphenomaxillary")))),
                    h5("-------------------------------------------------------------------------------------------------------------------------------------------------------"),
                    fixedPage(h5("Complete this section as normal"),
                              column(width=4,h4("Healing"),
                                     checkboxInput("Lefort1_Displaced","Displaced?",value=FALSE),
                                     conditionalPanel("input.Lefort1_Displaced",selectInput("Lefort1_Displaced2","Type of displacement",c("Translated","Angulated","Rotated","Shortened","Other")),
                                                      conditionalPanel("input.Lefort1_Displaced=='Other'",textInput("Lefort1_Displaced3","Define other",value=NA))),
                                     checkboxInput("Lefort1_Callus","Callus Formation?",value=FALSE),
                                     checkboxInput("Lefort1_NonUnion","Non Union?",value=FALSE),
                                     conditionalPanel("input.Lefort1_NonUnion",checkboxInput("Lefort1_NonUnion2","Healing on ununited edges?",value=FALSE),
                                                      conditionalPanel("input.Lefort1_NonUnion2",textInput("Lefort1_Nonunion3","Describe evidence of healing",value="Rounding of edges")),
                                                      selectInput("Lefort1_NonUnion4","Extent of Non-union",c("Complete","Partial")),
                                                      conditionalPanel("input.Lefort1_NonUnion4=='Partial'",numericInput("Lefort1_NonUnion5","Approximate Percentage of fracture united",value=50))),
                                     selectInput("Lefort1_Medical","Medical intervention",multiple=TRUE,selected="None",c("None","Pins","Plate","Screw","Splint","Periprosthetic fracture","Other")),
                                     conditionalPanel("input.Lefort1_Medical.indexOf('Other')>=0",textInput("Lefort1_Medical2","Define Other",value=NA))),
                              column(width=4,h4("Size"))))
#Lefort2####
Lefort2_UI<-tagList(fixedPage(h3("Lefort2 Fracture Description"),
                              h5("Please check the details in this section if any do not match your fracture use Custom to enter an accurate description"),
                              column(width=3,h4("Type"),
                                     h5("Please check the details in this section if any do not match your fracture then use Custom to enter an accurate description"),
                                     selectInput("Lefort2_NLine","Number of fracture lines",c("Single-1")),
                                     selectInput("Lefort2_Complete","Complete Fracture?",c("TRUE")),
                                     selectInput("Lefort2_Type","Type of fracture",c("Other")),
                                     selectInput("Lefort2_Type2","Define Other",c("Lefort")),
                                     selectInput("Lefort2_Pattern","Fracture Pattern",c("Other")),
                                     selectInput("Lefort2_Pattern2","Define Other","Pyramidal with the teeth at the base and the nasofrontal suture at the apex")),
                              column(width=3,h4("Location"),
                                     selectInput("Lefort2_Loc1","Region",c("Skull")),
                                     selectInput("Lefort2_Loc2","Bone",c("Maxilla/Sphenoid/Lacrimal/Nasal")),
                                     selectInput("Lefort2_Loc3","Overall Location Decription",c("Extends inferiolaterally from at or below the frontonasal suture to the posterior alveolar ridge.Going throught the lacrimal, inferior orbital rim (around the infraorbital foramen) and the lateral walls of the maxillary sinus"))),
                              column(width=3,h4(br()),
                                     strong("Maxilla"),
                                     selectInput("Lefort2_Loc4","Side",c("Can be either or both")),
                                     selectInput("Lefort2_Loc5","Surface",c("Endocranial/Ectocrnial")),
                                     selectInput("Lefort2_Loc6","Feature",c("alveolar process/maxillary sinus/frontal process/infraorbital foramen")),
                                     selectInput("Lefort2_Loc7","Sutures",c("sphenomaxillary/nasomaxillary/lacromaxillary")),
                                     strong("Sphenoid"),
                                     selectInput("Lefort2_Loc8","Feature",c("Pterygoid process")),
                                     selectInput("Lefort2_Loc9","Sutures",c("sphenomaxillary"))),
                              column(width=3,h4(br()),
                                     strong("Nasal"),
                                     selectInput("Lefort2_Loc10","Side",c("Can be either or both")),
                                     selectInput("Lefort2_Loc11","Surface",c("Endocranial/Ectocrnial")),
                                     selectInput("Lefort2_Loc12","Sutures",c("frontonasal/nasomaxillary/internasal")),
                                     strong("Lacrimal"),
                                     selectInput("Lefort2_Loc13","Side",c("Can be either or both")),
                                     selectInput("Lefort2_Loc14","Surface",c("Endocranial/Ectocrnial")),
                                     selectInput("Lefort2_Loc15","Sutures",c("lacromaxillary")))),
                    h5("-------------------------------------------------------------------------------------------------------------------------------------------------------"),
                    fixedPage(h5("Complete this section as normal"),
                              column(width=4,h4("Healing"),
                                     checkboxInput("Lefort2_Displaced","Displaced?",value=FALSE),
                                     conditionalPanel("input.Lefort2_Displaced",selectInput("Lefort2_Displaced2","Type of displacement",c("Translated","Angulated","Rotated","Shortened","Other")),
                                                      conditionalPanel("input.Lefort2_Displaced=='Other'",textInput("Lefort2_Displaced3","Define other",value=NA))),
                                     checkboxInput("Lefort2_Callus","Callus Formation?",value=FALSE),
                                     checkboxInput("Lefort2_NonUnion","Non Union?",value=FALSE),
                                     conditionalPanel("input.Lefort2_NonUnion",checkboxInput("Lefort2_NonUnion2","Healing on ununited edges?",value=FALSE),
                                                      conditionalPanel("input.Lefort2_NonUnion2",textInput("Lefort2_Nonunion3","Describe evidence of healing",value="Rounding of edges")),
                                                      selectInput("Lefort2_NonUnion4","Extent of Non-union",c("Complete","Partial")),
                                                      conditionalPanel("input.Lefort2_NonUnion4=='Partial'",numericInput("Lefort2_NonUnion5","Approximate Percentage of fracture united",value=50))),
                                     selectInput("Lefort2_Medical","Medical intervention",multiple=TRUE,selected="None",c("None","Pins","Plate","Screw","Splint","Periprosthetic fracture","Other")),
                                     conditionalPanel("input.Lefort2_Medical.indexOf('Other')>=0",textInput("Lefort2_Medical2","Define Other",value=NA))),
                              column(width=4,h4("Size"))))
