#Chip####
Chip_UI<-tagList(h3("Chip Description"))
Chip_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Hole####
Hole_UI<-tagList(h3("Hole Description"),
                 h5("For the purpose of recording a hole can be viewed as a tunnel between points on two surfaces, A and B, on the same bone section. 
                              should the abnormality be continous with an abnormality on a different section of bone (e.g. bullet entrance and exit wounds on different parts of the skull), these should be recorded separately and linked using the link tab.
                              In this case surface A of the entrance wound would be the ectocranial surface and surface B the endocranial surface."),
                 column(width=5,
                        img(src="Hole.png",height=450)),
                 column(width=2,h4("A to B"),
                        selectInput("Hole_Channel","Channel Shape",c("Straight","Angled","Curved","Unknown","Other")),
                        conditionalPanel("input.Hole_Channel=='Other'",textInput("Hole_Channel2","Define Other",value=NA)),
                        conditionalPanel("input.Hole_Channel=='Angled'||input.Hole_Channel=='Curved'||input.Hole_Channel=='Other'",
                                         selectInput("Hole_Angle","Direction of angulation",selected="None",c("Anterior","Posterior","Medial","Lateral","None","Superior","Inferior","Unknown","Other")),
                                         conditionalPanel("input.Hole_Angle=='Other'",textInput("Hole_Angle2","Define Other",value=NA))),
                        selectInput("Hole_AtoB","A to B Shape",c("Even","Tapered","Flared","Other","Unknown")),
                        conditionalPanel("input.Hole_AtoB=='Other'",textInput("Hole_AtoB2","Define Other",value=NA))),
                 column(width=2,h4("Surface A"),
                        selectInput("Hole_SurfaceA","Bone Surface",c("Endocranial","Ectocranial","Periosteal","Endosteal","Medial","Lateral","Anterior","Posterior","Superior","Inferior")),
                        selectInput("Hole_SurfaceShapeA","Surface Shape",c("Round","Oval","Linear","Irregular","KeyHole","Semi-Circular","Other")),
                        conditionalPanel("input.Hole_SurfaceShapeA=='Other'",textInput("Hole_SurfaceShapeA2","Define Other",value=NA)),
                        checkboxInput("Hole_BevelingA","Beveling?",value=FALSE),
                        conditionalPanel("input.Hole_BevelingA",
                                         selectInput("Hole_BevelingA2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                         conditionalPanel("input.Hole_BevelingA2=='Partially Surrounding'",selectInput("Hole_BevelingA3","Areas with Beveling",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior")))),
                        checkboxInput("Hole_FracturingA","Fractures?",value=FALSE),
                        conditionalPanel("input.Hole_FracturingA",
                                         selectInput("Hole_FracturingA2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                         conditionalPanel("input.Hole_FracturingA2=='Partially Surrounding'",selectInput("Hole_FracturingA3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior"))),
                                         selectInput("Hole_FracturingA4","Pattern",c("Radiating","Concentric","Other")),
                                         conditionalPanel("input.Hole_FracturingA4=='Other'",textInput("Hole_FracturingA5","Define Other",value=NA))),
                        checkboxInput("Hole_MicroA","Microfracturing?",value=FALSE),
                        conditionalPanel("input.Hole_MicroA",
                                         selectInput("Hole_MicroA2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                         conditionalPanel("input.Hole_MicroA2=='Partially Surrounding'",selectInput("Hole_MicroA3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior"))),
                                         selectInput("Hole_MicroA4","Pattern",c("Radiating","Concentric","Other")),
                                         conditionalPanel("input.Hole_MicroA4=='Other'",textInput("Hole_MicroA5","Define Other",value=NA)))),
                 column(width=2,h4("Surface B"),
                        selectInput("Hole_SurfaceB","Bone Surface",c("Endocranial","Ectocranial","Periosteal","Endosteal","Medial","Lateral","Anterior","Posterior","Superior","Inferior")),
                        selectInput("Hole_SurfaceShapeB","Surface Shape",c("Round","Oval","Linear","Irregular","KeyHole","Semi-Circular","Other")),
                        conditionalPanel("input.Hole_ShapeSurfaceShapeB=='Other'",textInput("Hole_SurfaceShapeB2","Define Other",value=NA)),
                        checkboxInput("Hole_BevelingB","Beveling?",value=FALSE),
                        conditionalPanel("input.Hole_BevelingB",
                                         selectInput("Hole_BevelingB2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                         conditionalPanel("input.Hole_BevelingB2=='Partially Surrounding'",selectInput("Hole_BevelingB3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior")))),
                        checkboxInput("Hole_FracturingB","Fractures?",value=FALSE),
                        conditionalPanel("input.Hole_FracturingB",
                                         selectInput("Hole_FracturingB2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                         conditionalPanel("input.Hole_FracturingB2=='Partially Surrounding'",selectInput("Hole_FracturingB3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior"))),
                                         selectInput("Hole_FracturingB4","Pattern",c("Radiating","Concentric","Other")),
                                         conditionalPanel("input.Hole_FracturingB4=='Other'",textInput("Hole_FracturingB5","Define Other",value=NA))),
                        checkboxInput("Hole_MicroB","Microfracturing?",value=FALSE),
                        conditionalPanel("input.Hole_MicroB",
                                         selectInput("Hole_MicroB2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                         conditionalPanel("input.Hole_MicroB2=='Partially Surrounding'",selectInput("Hole_MicroB3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior"))),
                                         selectInput("Hole_MicroB4","Pattern",c("Radiating","Concentric","Other")),
                                         conditionalPanel("input.Hole_MicroB4=='Other'",textInput("Hole_MicroB5","Define Other",value=NA)))),
                 column(width=1,h4("R.M"),
                        h5("-Hole circumference surface A"),
                        h5("-Hole circumference surface B"),
                        conditionalPanel("input.Hole_FracturingA || input.Hole_FracturingB",
                                         h5("-Fracturing Area(length)"),
                                         h5("-Fracturing Area(Width)")),
                        conditionalPanel("input.Hole_MicroA || input.Hole_MicroB",
                                         h5("-Microfracturing Area(length)"),
                                         h5("-Microfracturing Area(Width)"))))
Hole_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Puncture####
Puncture_UI<-tagList(fixedPage(h3("Puncture Description"),
                               column(width=6,
                                      img(src="Puncture.png",height=400)),
                               column(width=4,
                                      selectInput("Puncture_SurShape","Surface shape",c("Round","Oval","Linear","Irregular","Triangular","Curved","Cross","Diamond","Other")),
                                      conditionalPanel("input.Puncture_SurShape=='Other'",textInput("Puncture_SurShape2","Define Other",value=NA)),
                                      selectInput("Puncture_Direction","Direction",c("Medial","Lateral","Straight","Superior","Inferior","Anterior","Posterior","Other")),
                                      conditionalPanel("input.Puncture_Direction=='Other'",textInput("Puncture_Direction2","Define other",value=NA)),
                                      selectInput("Puncture_IndShape","Indentation Shape",c("Pointed","Straight","Tapered","Curved","Other")),
                                      conditionalPanel("input.Puncture_IndShape=='Other'",textInput("Puncture_IndShape2","Define other",value=NA)),
                                     checkboxInput("Puncture_FracturingA","Associated Macroscopic Fracturing?",value=FALSE),
                                      conditionalPanel("input.Puncture_FracturingA",
                                                       selectInput("Puncture_FracturingA2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                                       conditionalPanel("input.Puncture_FracturingA2=='Partially Surrounding'",selectInput("Puncture_FracturingA3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior"))),
                                                       selectInput("Puncture_FracturingA4","Pattern",c("Radiating","Concentric","Other")),
                                                       conditionalPanel("input.Puncture_FracturingA4=='Other'",textInput("Puncture_FracturingA5","Define Other",value=NA))),
                                      checkboxInput("Puncture_MicroA","Associated Microfracturing?",value=FALSE),
                                      conditionalPanel("input.Puncture_MicroA",
                                                       selectInput("Puncture_MicroA2","Relative Position of fracturing",c("Completly surrounding","Partially Surrounding")),
                                                       conditionalPanel("input.Puncture_MicroA2=='Partially Surrounding'",selectInput("Hole_MicroA3","Areas with fracturing",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior"))),
                                                       selectInput("Puncture_MicroA4","Pattern",c("Radiating","Concentric","Other")),
                                                       conditionalPanel("input.Puncture_MicroA4=='Other'",textInput("Hole_MicroA5","Define Other",value=NA)))),
                               column(width=2,h4("R.M"),
                                      h5("Surface Circumference"),
                                      h5("Puncture depth"),
                                      conditionalPanel("input.Puncture_FracturingA",
                                                       h5("Fracturing Area(length)"),
                                                       h5("Fracturing Area(Width)")),
                                      conditionalPanel("input.Puncture_MicroA",
                                                       h5("Microfracturing Area(length)"),
                                                       h5("Microfracturing Area(Width)")))
))
Puncture_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Pit####
Pit_UI<-tagList(h3("Pit Description"),
                column(width=4,
                       img(src="Pit.png",height=375)),
                column(width=4,
                       numericInput("Pit_Number","Number of distinct Pits (approximate)",value=1),
                       conditionalPanel("input.Pit_Number>1",
                                        textInput("Pit_Distribution","Distribution of pits across effected area",value=NA),
                                        selectInput("Pit_Overlap","Overlapping of pits",c("None","Some Overlapping but Individual pits still easierly discernable","Overlapping to an extent where the exact number of pits isn't clear","A mixture of degrees of overlapping is seen across the affected area")),
                                        h5("If the shape of different pits variesyou should consider recording these separately, and then linking using the link tab")),
                       selectInput("Pit_SShape","Surface Shape",c("Circular","Oval","Linear","Irregular","Other")),
                       conditionalPanel("input.Pit_SShape=='Other'",textInput("Pit_SShape2","Define Other",value=NA)),
                       selectInput("Pit_PShape","Profile Shape",c("U","Flat Base U","Raised base U","Stepped U","V","Flat Base V","Raised base V","Stepped V","Irregular","Flat Base Irregular","Raised base Irregular","Stepped Irregular","Other")),
                       conditionalPanel("input.Pit_PShape=='Other'",textInput("Pit_PShape2","Define Other",value=NA))),
                column(width=3,h4("R.M"),
                       h5("-surface width/circumference"),
                       h5("-Depth"),
                       conditionalPanel("input.Pit_Number>1",h5("-Size of affected area (atleast 2 Dimensions)"))))
Pit_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Incision####
Incision_UI<-tagList(h3("Incision Description"),
                     column(width=4,
                            strong("Cross Section Shape"),
                            img(src="incision.png",height=375),
                            strong("Layout of cut"),
                            img(src="cut.png",height=150)),
                     column(width=4,
                            numericInput("Incision_Number","Number of distinct incisions",value=1),
                            conditionalPanel("input.Incision_Number>1",
                                             selectInput("Incision_Relationship","Relative postion of multiple incisions",c("Parrell","Crosssing","Other")),
                                             conditionalPanel("input.Incision_Relationship=='Other'",textInput("Incision_Relationship2","Define Other",value=NA)),
                                             h5("If the cross sectional shape varies across multiple incisions you should consider recording these separately, and then linking using the link tab")),
                            selectInput("Incision_CrossSection","Cross section shape",c("V","U","Broad V","Broad U","Irregular","Flat base V","Flat base U","Flat base Broad V","Flat base Broad U","Flat base Irregular","1/2 V","1/2 U","1/2 Broad V","1/2 Broad U","1/2 Irregular","Stepped","Rounded Step","Broad Step","Broad rounded Step","Raised base v","Raised base U","Rasied base Broad V","Raised base Broad U","Raised base Irregular","Box","Raised base box","Other")),
                            conditionalPanel("input.Incision_CrossSection=='Other'",textInput("Incision_CrossSection2","Define Other",value=NA)),
                            selectInput("Incision_SideA","Texture of side A",c("Smooth","Verticle striations","Horizontal striations","Other")),
                            conditionalPanel("input.Incision_SideA=='Other'",textInput("Incision_SideA2","Define Other",value=NA)),
                            selectInput("Incision_SideB","Texture of side B",c("Smooth","Verticle striations","Horizontal striations","Other")),
                            conditionalPanel("input.Incision_SideB=='Other'",textInput("Incision_SideB2","Define Other",value=NA)),
                            selectInput("Incision_Base","Texture of base",c("NA","Smooth","Verticle striations","Horizontal striations","Other")),
                            conditionalPanel("input.Incision_Base=='Other'",textInput("Incision_Base","Define Other",value=NA))),
                     column(width=4,
                            selectInput("Incision_Internal","Abnormalities within chopmark",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                            conditionalPanel("input.Incision_Internal.indexOf('Other')>=0",textInput("Incision_Internal2","Define Other Abnormality",value=NA)),
                            conditionalPanel("input.Incision_Internal.indexOf('Fracture')>=0",h4("Fracturing"),
                                             selectInput("Incision_Fract_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_Fract_1=='Other'",textInput("Incision_Fract_1B","Define Other",value=NA)),
                                             selectInput("Incision_Fract_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_Fract_2=='Partial'",
                                                              numericInput("Incision_Fract_3","Approximate percentage of length of chop mark with fracturing",value=50),
                                                              textInput("Incision_Fract_4","Describe location of fracturing",value=NA))),
                            conditionalPanel("input.Incision_Internal.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                             selectInput("Incision_MFract_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_MFract_1=='Other'",textInput("Incision_MFract_1B","Define Other",value=NA)),
                                             selectInput("Incision_MFract_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_MFract_2=='Partial'",
                                                              numericInput("Incision_MFract_3","Approximate percentage of length of chop mark with Microfracturing",value=50),
                                                              textInput("Incision_MFract_4","Describe location of Microfracturing",value=NA))),
                            conditionalPanel("input.Incision_Internal.indexOf('Striations')>=0",h4("Striations"),
                                             selectInput("Incision_stri_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_stri_1=='Other'",textInput("Incision_stri_B","Define Other",value=NA)),
                                             selectInput("Incision_stri_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_stri_2=='Partial'",
                                                              numericInput("Incision_stri_3","Approximate percentage of length of chop mark with striations",value=50),
                                                              textInput("Incision_stri_4","Describe location of striations",value=NA))),
                            conditionalPanel("input.Incision_Internal.indexOf('Porosity')>=0",h4("Porosity"),
                                             selectInput("Incision_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                             selectInput("Incision_Por_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                             selectInput("Incision_Por_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_Por_2=='Partial'",
                                                              numericInput("Incision_Por_3","Approximate percentage of length of chop mark with porosity",value=50),
                                                              textInput("Incision_Por_4","Describe location of porosity",value=NA))),
                            conditionalPanel("input.Incision_Internal.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                             selectInput("Incision_CF_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_CF_2=='Partial'",
                                                              numericInput("Incision_CF_3","Approximate percentage of length of chop mark with flaking",value=50),
                                                              textInput("Incision_CF_4","Describe location of flaking",value=NA))),
                            conditionalPanel("input.Incision_Internal.indexOf('New bone growth')>=0",h4("New bone growth"),
                                             selectInput("Incision_NBG_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                             selectInput("Incision_NBG_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_NBG_2=='Partial'",
                                                              numericInput("Incision_NBG_3","Approximate percentage of length of chop mark with bone growth",value=50),
                                                              textInput("Incision_NBG_4","Describe location of new bone",value=NA))),
                            conditionalPanel("input.Incision_Internal.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                             selectInput("Incision_ET_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Incision_ET_2=='Partial'",
                                                              numericInput("Incision_ET_3","Approximate percentage of length of chop mark with exposed trabeculae",value=50),
                                                              textInput("Incision_ET_4","Describe location of exposed trabeculae",value=NA))),
                            selectInput("Incision_SurfaceA","Abnormalities on Surface A",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Other')>=0",textInput("Incision_SurfaceA2","Define Other Abnormality",value=NA)),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Fracture')>=0",h4("Fracturing"),
                                             selectInput("Incision_FractA_1","Orientation relative to incision",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_FractA_1=='Other'",textInput("Incision_FractA_1B","Define Other",value=NA)),
                                             selectInput("Incision_FractA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_FractA_2=='Partial'",
                                                              numericInput("Incision_FractA_3","Approximate percentage of length of incision with fracturing",value=50),
                                                              textInput("Incision_FractA_4","Describe location of fracturing",value=NA))),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                             selectInput("Incision_MFractA_1","Orientation relative to incision",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_MFractA_1=='Other'",textInput("Incision_MFractA_1B","Define Other",value=NA)),
                                             selectInput("Incision_MFractA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_MFractA_2=='Partial'",
                                                              numericInput("Incision_MFractA_3","Approximate percentage of length of incision with Microfracturing",value=50),
                                                              textInput("Incision_MFractA_4","Describe location of Microfracturing",value=NA))),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Striations')>=0",h4("Striations"),
                                             selectInput("Incision_striA_1","Orientation relative to incision",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_striA_1=='Other'",textInput("Incision_striA_B","Define Other",value=NA)),
                                             selectInput("Incision_striA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_striA_2=='Partial'",
                                                              numericInput("Incision_striA_3","Approximate percentage of length of incision with striations",value=50),
                                                              textInput("Incision_striA_4","Describe location of striations",value=NA))),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Porosity')>=0",h4("Porosity"),
                                             selectInput("Incision_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                             selectInput("Incision_PorA_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                             selectInput("Incision_PorA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_PorA_2=='Partial'",
                                                              numericInput("Incision_PorA_3","Approximate percentage of length of incision with porosity",value=50),
                                                              textInput("Incision_PorA_4","Describe location of porosity",value=NA))),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                             selectInput("Incision_CFA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_CFA_2=='Partial'",
                                                              numericInput("Incision_CFA_3","Approximate percentage of length of incision with flaking",value=50),
                                                              textInput("Incision_CFA_4","Describe location of flaking",value=NA))),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('New bone growth')>=0",h4("New bone growth"),
                                             selectInput("Incision_NBGA_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                             selectInput("Incision_NBGA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_NBGA_2=='Partial'",
                                                              numericInput("Incision_NBGA_3","Approximate percentage of length of incision with bone growth",value=50),
                                                              textInput("Incision_NBGA_4","Describe location of new bone",value=NA))),
                            conditionalPanel("input.Incision_SurfaceA.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                             selectInput("Incision_ETA_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_ETA_2=='Partial'",
                                                              numericInput("Incision_ETA_3","Approximate percentage of length of incision with exposed trabeculae",value=50),
                                                              textInput("Incision_ETA_4","Describe location of exposed trabeculae",value=NA))),
                            
                            selectInput("Incision_SurfaceB","Abnormalities on Surface B",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Other')>=0",textInput("Incision_SurfaceB2","Define Other Abnormality",value=NA)),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Fracture')>=0",h4("Fracturing"),
                                             selectInput("Incision_FractB_1","Orientation relative to incision",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_FractB_1=='Other'",textInput("Incision_FractB_1B","Define Other",value=NA)),
                                             selectInput("Incision_FractB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_FractB_2=='Partial'",
                                                              numericInput("Incision_FractB_3","Approximate percentage of length of incision with fracturing",value=50),
                                                              textInput("Incision_FractB_4","Describe location of fracturing",value=NA))),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                             selectInput("Incision_MFractB_1","Orientation relative to incision",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_MFractB_1=='Other'",textInput("Incision_MFractB_1B","Define Other",value=NA)),
                                             selectInput("Incision_MFractB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_MFractB_2=='Partial'",
                                                              numericInput("Incision_MFractB_3","Approximate percentage of length of incision with Microfracturing",value=50),
                                                              textInput("Incision_MFractB_4","Describe location of Microfracturing",value=NA))),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Striations')>=0",h4("Striations"),
                                             selectInput("Incision_striB_1","Orientation relative to incision",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Incision_striB_1=='Other'",textInput("Incision_striB_B","Define Other",value=NA)),
                                             selectInput("Incision_striB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_striB_2=='Partial'",
                                                              numericInput("Incision_striB_3","Approximate percentage of length of incision with striations",value=50),
                                                              textInput("Incision_striB_4","Describe location of striations",value=NA))),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Porosity')>=0",h4("Porosity"),
                                             selectInput("Incision_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                             selectInput("Incision_PorB_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                             selectInput("Incision_PorB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_PorB_2=='Partial'",
                                                              numericInput("Incision_PorB_3","Approximate percentage of length of incision with porosity",value=50),
                                                              textInput("Incision_PorB_4","Describe location of porosity",value=NA))),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                             selectInput("Incision_CFB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_CFB_2=='Partial'",
                                                              numericInput("Incision_CFB_3","Approximate percentage of length of incision with flaking",value=50),
                                                              textInput("Incision_CFB_4","Describe location of flaking",value=NA))),
                            
                            conditionalPanel("input.Incision_SurfaceB.indexOf('New bone growth')>=0",h4("New bone growth"),
                                             selectInput("Incision_NBGB_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                             selectInput("Incision_NBGB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_NBGB_2=='Partial'",
                                                              numericInput("Incision_NBGB_3","Approximate percentage of length of incision with bone growth",value=50),
                                                              textInput("Incision_NBGB_4","Describe location of new bone",value=NA))),
                            conditionalPanel("input.Incision_SurfaceB.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                             selectInput("Incision_ETB_2","Extent",c("Full length of incision","Partial","Unknown")),
                                             conditionalPanel("input.Incision_ETB_2=='Partial'",
                                                              numericInput("Incision_ETB_3","Approximate percentage of length of incision with exposed trabeculae",value=50),
                                                              textInput("Incision_ETB_4","Describe location of exposed trabeculae",value=NA)))),
                     column(width=1,h4("R.M")))
Incision_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#ChopMark####
ChopMark_UI<-tagList(h3("ChopMark Description"),
                     column(width=4,
                            strong("Cross section Shapes"),
                            img(src="Chop.png",height=225),
                            strong("Layout of cut"),
                            img(src="cut.png",height=150),
                            numericInput("Chop_Number","Number of distinct Chop Marks",value=1),
                            conditionalPanel("input.Chop_Number>1",
                                             selectInput("Chop_Relationship","Relative postion of multiple Chop Marks",c("Parrell","Crosssing","Other")),
                                             conditionalPanel("input.Chop_Relationship=='Other'",textInput("Chop_Relationship2","Define Other",value=NA)),
                                             h5("If the cross sectional shape varies across multiple chop Marks you should consider recording these separately, and then linking using the link tab")),
                            selectInput("Chop_CrossSection","Cross section shape",c("1/2 V","1/2 U","1/2 Broad V","1/2 Broad U","1/2 Irregular","Box","Flat base 1/2 u","Flat base 1/2 v","Flat base 1/2 broad V","Flat base 1/2 broad U","Flat base 1/2 irregular","Raised base 1/2 u","Raised base 1/2 v","Rasied base 1/2 broad V","Raised base 1/2 broad U","Raised base 1/2 irregular","Raised base box","Other")),
                            conditionalPanel("input.Chop_CrossSection=='Other'",textInput("Chop_CrossSection2","Define Other",value=NA))),
                     column(width=4,
                            checkboxInput("Chop_Fragmentation","Fragmentation of bone",value=FALSE),
                            conditionalPanel("input.Chop_Fragmentation",
                                             numericInput("Chop_NFragment","Approximate number of fragments",value=1),
                                             selectInput("Chop_FragmentLevel","Level of fragmentation",c("Complete","Incomplete","Mixed"))),
                            selectInput("Chop_SideA","Bone surface on side A",c("Smooth","Verticle striations","Horizontal striations","Other")),
                            conditionalPanel("input.Chop_SideA=='Other'",textInput("Chop_SideA2","Define Other",value=NA)),
                            selectInput("Chop_SideB","Bone Surface on side B",c("Smooth","Verticle striations","Horizontal striations","Other")),
                            conditionalPanel("input.Chop_SideB=='Other'",textInput("Chop_SideB2","Define Other",value=NA)),
                            selectInput("Chop_Base","Bone Surface on Base",c("NA","Smooth","Verticle striations","Horizontal striations","Other")),
                            conditionalPanel("input.Chop_Base=='Other'",textInput("Chop_Base","Define Other",value=NA))),
                     column(width=4,
                            selectInput("Chop_Internal","Abnormalities within chopmark",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                            conditionalPanel("input.Chop_Internal.indexOf('Other')>=0",textInput("Chop_Internal2","Define Other Abnormality",value=NA)),
                            conditionalPanel("input.Chop_Internal.indexOf('Fracture')>=0",h4("Fracturing"),
                                             selectInput("Chop_Fract_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_Fract_1=='Other'",textInput("Chop_Fract_1B","Define Other",value=NA)),
                                             selectInput("Chop_Fract_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_Fract_2=='Partial'",
                                                              numericInput("Chop_Fract_3","Approximate percentage of length of chop mark with fracturing",value=50),
                                                              textInput("Chop_Fract_4","Describe location of fracturing",value=NA))),
                            conditionalPanel("input.Chop_Internal.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                             selectInput("Chop_MFract_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_MFract_1=='Other'",textInput("Chop_MFract_1B","Define Other",value=NA)),
                                             selectInput("Chop_MFract_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_MFract_2=='Partial'",
                                                              numericInput("Chop_MFract_3","Approximate percentage of length of chop mark with Microfracturing",value=50),
                                                              textInput("Chop_MFract_4","Describe location of Microfracturing",value=NA))),
                            conditionalPanel("input.Chop_Internal.indexOf('Striations')>=0",h4("Striations"),
                                             selectInput("Chop_stri_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_stri_1=='Other'",textInput("Chop_stri_B","Define Other",value=NA)),
                                             selectInput("Chop_stri_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_stri_2=='Partial'",
                                                              numericInput("Chop_stri_3","Approximate percentage of length of chop mark with striations",value=50),
                                                              textInput("Chop_stri_4","Describe location of striations",value=NA))),
                            conditionalPanel("input.Chop_Internal.indexOf('Porosity')>=0",h4("Porosity"),
                                             selectInput("Chop_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                             selectInput("Chop_Por_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                             selectInput("Chop_Por_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_Por_2=='Partial'",
                                                              numericInput("Chop_Por_3","Approximate percentage of length of chop mark with porosity",value=50),
                                                              textInput("Chop_Por_4","Describe location of porosity",value=NA))),
                            conditionalPanel("input.Chop_Internal.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                             selectInput("Chop_CF_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_CF_2=='Partial'",
                                                              numericInput("Chop_CF_3","Approximate percentage of length of chop mark with flaking",value=50),
                                                              textInput("Chop_CF_4","Describe location of flaking",value=NA))),
                            conditionalPanel("input.Chop_Internal.indexOf('New bone growth')>=0",h4("New bone growth"),
                                             selectInput("Chop_NBG_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                             selectInput("Chop_NBG_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_NBG_2=='Partial'",
                                                              numericInput("Chop_NBG_3","Approximate percentage of length of chop mark with bone growth",value=50),
                                                              textInput("Chop_NBG_4","Describe location of new bone",value=NA))),
                            conditionalPanel("input.Chop_Internal.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                             selectInput("Chop_ET_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_ET_2=='Partial'",
                                                              numericInput("Chop_ET_3","Approximate percentage of length of chop mark with exposed trabeculae",value=50),
                                                              textInput("Chop_ET_4","Describe location of exposed trabeculae",value=NA))),
                            selectInput("Chop_SurfaceA","Abnormalities on Surface A",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Other')>=0",textInput("Chop_SurfaceA2","Define Other Abnormality",value=NA)),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Fracture')>=0",h4("Fracturing"),
                                             selectInput("Chop_FractA_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_FractA_1=='Other'",textInput("Chop_FractA_1B","Define Other",value=NA)),
                                             selectInput("Chop_FractA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_FractA_2=='Partial'",
                                                              numericInput("Chop_FractA_3","Approximate percentage of length of chop mark with fracturing",value=50),
                                                              textInput("Chop_FractA_4","Describe location of fracturing",value=NA))),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                             selectInput("Chop_MFractA_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_MFractA_1=='Other'",textInput("Chop_MFractA_1B","Define Other",value=NA)),
                                             selectInput("Chop_MFractA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_MFractA_2=='Partial'",
                                                              numericInput("Chop_MFractA_3","Approximate percentage of length of chop mark with Microfracturing",value=50),
                                                              textInput("Chop_MFractA_4","Describe location of Microfracturing",value=NA))),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Striations')>=0",h4("Striations"),
                                             selectInput("Chop_striA_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_striA_1=='Other'",textInput("Chop_striA_B","Define Other",value=NA)),
                                             selectInput("Chop_striA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_striA_2=='Partial'",
                                                              numericInput("Chop_striA_3","Approximate percentage of length of chop mark with striations",value=50),
                                                              textInput("Chop_striA_4","Describe location of striations",value=NA))),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Porosity')>=0",h4("Porosity"),
                                             selectInput("Chop_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                             selectInput("Chop_PorA_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                             selectInput("Chop_PorA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_PorA_2=='Partial'",
                                                              numericInput("Chop_PorA_3","Approximate percentage of length of chop mark with porosity",value=50),
                                                              textInput("Chop_PorA_4","Describe location of porosity",value=NA))),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                             selectInput("Chop_CFA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_CFA_2=='Partial'",
                                                              numericInput("Chop_CFA_3","Approximate percentage of length of chop mark with flaking",value=50),
                                                              textInput("Chop_CFA_4","Describe location of flaking",value=NA))),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('New bone growth')>=0",h4("New bone growth"),
                                             selectInput("Chop_NBGA_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                             selectInput("Chop_NBGA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_NBGA_2=='Partial'",
                                                              numericInput("Chop_NBGA_3","Approximate percentage of length of chop mark with bone growth",value=50),
                                                              textInput("Chop_NBGA_4","Describe location of new bone",value=NA))),
                            conditionalPanel("input.Chop_SurfaceA.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                             selectInput("Chop_ETA_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_ETA_2=='Partial'",
                                                              numericInput("Chop_ETA_3","Approximate percentage of length of chop mark with exposed trabeculae",value=50),
                                                              textInput("Chop_ETA_4","Describe location of exposed trabeculae",value=NA))),
                            
                            selectInput("Chop_SurfaceB","Abnormalities on Surface B",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Other')>=0",textInput("Chop_SurfaceB2","Define Other Abnormality",value=NA)),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Fracture')>=0",h4("Fracturing"),
                                             selectInput("Chop_FractB_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_FractB_1=='Other'",textInput("Chop_FractB_1B","Define Other",value=NA)),
                                             selectInput("Chop_FractB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_FractB_2=='Partial'",
                                                              numericInput("Chop_FractB_3","Approximate percentage of length of chop mark with fracturing",value=50),
                                                              textInput("Chop_FractB_4","Describe location of fracturing",value=NA))),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                             selectInput("Chop_MFractB_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_MFractB_1=='Other'",textInput("Chop_MFractB_1B","Define Other",value=NA)),
                                             selectInput("Chop_MFractB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_MFractB_2=='Partial'",
                                                              numericInput("Chop_MFractB_3","Approximate percentage of length of chop mark with Microfracturing",value=50),
                                                              textInput("Chop_MFractB_4","Describe location of Microfracturing",value=NA))),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Striations')>=0",h4("Striations"),
                                             selectInput("Chop_striB_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                             conditionalPanel("input.Chop_striB_1=='Other'",textInput("Chop_striB_B","Define Other",value=NA)),
                                             selectInput("Chop_striB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_striB_2=='Partial'",
                                                              numericInput("Chop_striB_3","Approximate percentage of length of chop mark with striations",value=50),
                                                              textInput("Chop_striB_4","Describe location of striations",value=NA))),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Porosity')>=0",h4("Porosity"),
                                             selectInput("Chop_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                             selectInput("Chop_PorB_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                             selectInput("Chop_PorB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_PorB_2=='Partial'",
                                                              numericInput("Chop_PorB_3","Approximate percentage of length of chop mark with porosity",value=50),
                                                              textInput("Chop_PorB_4","Describe location of porosity",value=NA))),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                             selectInput("Chop_CFB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_CFB_2=='Partial'",
                                                              numericInput("Chop_CFB_3","Approximate percentage of length of chop mark with flaking",value=50),
                                                              textInput("Chop_CFB_4","Describe location of flaking",value=NA))),
                            
                            conditionalPanel("input.Chop_SurfaceB.indexOf('New bone growth')>=0",h4("New bone growth"),
                                             selectInput("Chop_NBGB_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                             selectInput("Chop_NBGB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_NBGB_2=='Partial'",
                                                              numericInput("Chop_NBGB_3","Approximate percentage of length of chop mark with bone growth",value=50),
                                                              textInput("Chop_NBGB_4","Describe location of new bone",value=NA))),
                            conditionalPanel("input.Chop_SurfaceB.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                             selectInput("Chop_ETB_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                             conditionalPanel("input.Chop_ETB_2=='Partial'",
                                                              numericInput("Chop_ETB_3","Approximate percentage of length of chop mark with exposed trabeculae",value=50),
                                                              textInput("Chop_ETB_4","Describe location of exposed trabeculae",value=NA))))
)
ChopMark_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Furrow####
Furrow_UI<-tagList(h3("Furrow Description"),
                   column(width=4,
                          strong("Cross Section Shape"),
                          img(src="Furrow.png",height=225),
                          strong("Layout of cut"),
                          img(src="cut.png",height=150)),
                   column(width=4,
                          numericInput("Furrow_Number","Number of distinct furrows",value=1),
                          conditionalPanel("input.Furrow_Number>1",
                                           selectInput("Furrow_Relationship","Relative postion of multiple furrows",c("Parrell","Crosssing","Other")),
                                           conditionalPanel("input.Furrow_Relationship=='Other'",textInput("Furrow_Relationship2","Define Other",value=NA)),
                                           h5("If the cross sectional shape varies across multiple furrows you should consider recording these separately, and then linking using the link tab")),
                          selectInput("Furrow_CrossSection","Cross section shape",c("Broad V","Broad U","Irregular","Flat base Broad V","Flat base Broad U","Flat base Irregular","1/2 Broad V","1/2 Broad U","1/2 Irregular","Broad Step","Broad rounded Step","Box","Raised base box","Rasied base Broad V","Raised base Broad U","Raised base Irregular","Other")),
                          conditionalPanel("input.Furrow_CrossSection=='Other'",textInput("Furrow_CrossSection2","Define Other",value=NA)),
                          selectInput("Furrow_SideA","Texture of side A",c("Smooth","Verticle striations","Horizontal striations","Other")),
                          conditionalPanel("input.Furrow_SideA=='Other'",textInput("Furrow_SideA2","Define Other",value=NA)),
                          selectInput("Furrow_SideB","Texture of side B",c("Smooth","Verticle striations","Horizontal striations","Other")),
                          conditionalPanel("input.Furrow_SideB=='Other'",textInput("Furrow_SideB2","Define Other",value=NA)),
                          selectInput("Furrow_Base","Texture of base",c("NA","Smooth","Verticle striations","Horizontal striations","Other")),
                          conditionalPanel("input.Furrow_Base=='Other'",textInput("Furrow_Base","Define Other",value=NA))),
                   column(width=4,
                          selectInput("Furrow_Internal","Abnormalities within chopmark",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                          conditionalPanel("input.Furrow_Internal.indexOf('Other')>=0",textInput("Furrow_Internal2","Define Other Abnormality",value=NA)),
                          conditionalPanel("input.Furrow_Internal.indexOf('Fracture')>=0",h4("Fracturing"),
                                           selectInput("Furrow_Fract_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_Fract_1=='Other'",textInput("Furrow_Fract_1B","Define Other",value=NA)),
                                           selectInput("Furrow_Fract_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_Fract_2=='Partial'",
                                                            numericInput("Furrow_Fract_3","Approximate percentage of length of chop mark with fracturing",value=50),
                                                            textInput("Furrow_Fract_4","Describe location of fracturing",value=NA))),
                          conditionalPanel("input.Furrow_Internal.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                           selectInput("Furrow_MFract_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_MFract_1=='Other'",textInput("Furrow_MFract_1B","Define Other",value=NA)),
                                           selectInput("Furrow_MFract_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_MFract_2=='Partial'",
                                                            numericInput("Furrow_MFract_3","Approximate percentage of length of chop mark with Microfracturing",value=50),
                                                            textInput("Furrow_MFract_4","Describe location of Microfracturing",value=NA))),
                          conditionalPanel("input.Furrow_Internal.indexOf('Striations')>=0",h4("Striations"),
                                           selectInput("Furrow_stri_1","Orientation relative to chop mark",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_stri_1=='Other'",textInput("Furrow_stri_B","Define Other",value=NA)),
                                           selectInput("Furrow_stri_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_stri_2=='Partial'",
                                                            numericInput("Furrow_stri_3","Approximate percentage of length of chop mark with striations",value=50),
                                                            textInput("Furrow_stri_4","Describe location of striations",value=NA))),
                          conditionalPanel("input.Furrow_Internal.indexOf('Porosity')>=0",h4("Porosity"),
                                           selectInput("Furrow_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                           selectInput("Furrow_Por_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                           selectInput("Furrow_Por_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_Por_2=='Partial'",
                                                            numericInput("Furrow_Por_3","Approximate percentage of length of chop mark with porosity",value=50),
                                                            textInput("Furrow_Por_4","Describe location of porosity",value=NA))),
                          conditionalPanel("input.Furrow_Internal.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                           selectInput("Furrow_CF_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_CF_2=='Partial'",
                                                            numericInput("Furrow_CF_3","Approximate percentage of length of chop mark with flaking",value=50),
                                                            textInput("Furrow_CF_4","Describe location of flaking",value=NA))),
                          conditionalPanel("input.Furrow_Internal.indexOf('New bone growth')>=0",h4("New bone growth"),
                                           selectInput("Furrow_NBG_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                           selectInput("Furrow_NBG_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_NBG_2=='Partial'",
                                                            numericInput("Furrow_NBG_3","Approximate percentage of length of chop mark with bone growth",value=50),
                                                            textInput("Furrow_NBG_4","Describe location of new bone",value=NA))),
                          conditionalPanel("input.Furrow_Internal.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                           selectInput("Furrow_ET_2","Extent",c("Full length of chop mark","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_ET_2=='Partial'",
                                                            numericInput("Furrow_ET_3","Approximate percentage of length of chop mark with exposed trabeculae",value=50),
                                                            textInput("Furrow_ET_4","Describe location of exposed trabeculae",value=NA))),
                          selectInput("Furrow_SurfaceA","Abnormalities on Surface A",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Other')>=0",textInput("Furrow_SurfaceA2","Define Other Abnormality",value=NA)),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Fracture')>=0",h4("Fracturing"),
                                           selectInput("Furrow_FractA_1","Orientation relative to furrow",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_FractA_1=='Other'",textInput("Furrow_FractA_1B","Define Other",value=NA)),
                                           selectInput("Furrow_FractA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_FractA_2=='Partial'",
                                                            numericInput("Furrow_FractA_3","Approximate percentage of length of furrow with fracturing",value=50),
                                                            textInput("Furrow_FractA_4","Describe location of fracturing",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                           selectInput("Furrow_MFractA_1","Orientation relative to furrow",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_MFractA_1=='Other'",textInput("Furrow_MFractA_1B","Define Other",value=NA)),
                                           selectInput("Furrow_MFractA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_MFractA_2=='Partial'",
                                                            numericInput("Furrow_MFractA_3","Approximate percentage of length of furrow with Microfracturing",value=50),
                                                            textInput("Furrow_MFractA_4","Describe location of Microfracturing",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Striations')>=0",h4("Striations"),
                                           selectInput("Furrow_striA_1","Orientation relative to furrow",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_striA_1=='Other'",textInput("Furrow_striA_B","Define Other",value=NA)),
                                           selectInput("Furrow_striA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_striA_2=='Partial'",
                                                            numericInput("Furrow_striA_3","Approximate percentage of length of furrow with striations",value=50),
                                                            textInput("Furrow_striA_4","Describe location of striations",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Porosity')>=0",h4("Porosity"),
                                           selectInput("Furrow_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                           selectInput("Furrow_PorA_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                           selectInput("Furrow_PorA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_PorA_2=='Partial'",
                                                            numericInput("Furrow_PorA_3","Approximate percentage of length of furrow with porosity",value=50),
                                                            textInput("Furrow_PorA_4","Describe location of porosity",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                           selectInput("Furrow_CFA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_CFA_2=='Partial'",
                                                            numericInput("Furrow_CFA_3","Approximate percentage of length of furrow with flaking",value=50),
                                                            textInput("Furrow_CFA_4","Describe location of flaking",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('New bone growth')>=0",h4("New bone growth"),
                                           selectInput("Furrow_NBGA_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                           selectInput("Furrow_NBGA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_NBGA_2=='Partial'",
                                                            numericInput("Furrow_NBGA_3","Approximate percentage of length of furrow with bone growth",value=50),
                                                            textInput("Furrow_NBGA_4","Describe location of new bone",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceA.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                           selectInput("Furrow_ETA_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_ETA_2=='Partial'",
                                                            numericInput("Furrow_ETA_3","Approximate percentage of length of furrow with exposed trabeculae",value=50),
                                                            textInput("Furrow_ETA_4","Describe location of exposed trabeculae",value=NA))),
                          
                          selectInput("Furrow_SurfaceB","Abnormalities on Surface B",multiple=TRUE,selected="None",c("None","Porosity","Fracture","Microfractures","Cortical flaking","Exposed Trabeculae","New bone growth","Striations","Other")),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Other')>=0",textInput("Furrow_SurfaceB2","Define Other Abnormality",value=NA)),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Fracture')>=0",h4("Fracturing"),
                                           selectInput("Furrow_FractB_1","Orientation relative to furrow",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_FractB_1=='Other'",textInput("Furrow_FractB_1B","Define Other",value=NA)),
                                           selectInput("Furrow_FractB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_FractB_2=='Partial'",
                                                            numericInput("Furrow_FractB_3","Approximate percentage of length of furrow with fracturing",value=50),
                                                            textInput("Furrow_FractB_4","Describe location of fracturing",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Microfractures')>=0",h4("MicroFracturing"),
                                           selectInput("Furrow_MFractB_1","Orientation relative to furrow",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_MFractB_1=='Other'",textInput("Furrow_MFractB_1B","Define Other",value=NA)),
                                           selectInput("Furrow_MFractB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_MFractB_2=='Partial'",
                                                            numericInput("Furrow_MFractB_3","Approximate percentage of length of furrow with Microfracturing",value=50),
                                                            textInput("Furrow_MFractB_4","Describe location of Microfracturing",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Striations')>=0",h4("Striations"),
                                           selectInput("Furrow_striB_1","Orientation relative to furrow",c("Parallel","Perpendiular","Other")),
                                           conditionalPanel("input.Furrow_striB_1=='Other'",textInput("Furrow_striB_B","Define Other",value=NA)),
                                           selectInput("Furrow_striB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_striB_2=='Partial'",
                                                            numericInput("Furrow_striB_3","Approximate percentage of length of furrow with striations",value=50),
                                                            textInput("Furrow_striB_4","Describe location of striations",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Porosity')>=0",h4("Porosity"),
                                           selectInput("Furrow_PorA","Size of holes(select all aplicable)",multiple=TRUE,choices=c("<0.5mm","0.5-<1mm","1mm-<2mm",">2mm")),
                                           selectInput("Furrow_PorB_1","Hole size variabilty(select the most appropriate)",c("The size is roughly consitant across the whole lesion","There is some variabilty that is randomly distrubuted across the lesion","There is some variablity with some geographic grouping by size","There is significant variablity that is randomly distrubuted across the lesion","There is significant variablity with some geographic grouping by size")),
                                           selectInput("Furrow_PorB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_PorB_2=='Partial'",
                                                            numericInput("Furrow_PorB_3","Approximate percentage of length of furrow with porosity",value=50),
                                                            textInput("Furrow_PorB_4","Describe location of porosity",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Cortical flaking')>=0",h4("Cortical flaking"),
                                           selectInput("Furrow_CFB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_CFB_2=='Partial'",
                                                            numericInput("Furrow_CFB_3","Approximate percentage of length of furrow with flaking",value=50),
                                                            textInput("Furrow_CFB_4","Describe location of flaking",value=NA))),
                          
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('New bone growth')>=0",h4("New bone growth"),
                                           selectInput("Furrow_NBGB_1","Type of New Bone",c("reactive woven bone"="Woven","sclerotic reaction"="Sclerotic","Mixture of sclerotic and woven"="Mixed")),
                                           selectInput("Furrow_NBGB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_NBGB_2=='Partial'",
                                                            numericInput("Furrow_NBGB_3","Approximate percentage of length of furrow with bone growth",value=50),
                                                            textInput("Furrow_NBGB_4","Describe location of new bone",value=NA))),
                          conditionalPanel("input.Furrow_SurfaceB.indexOf('Exposed Trabeculae')>=0",h4("Exposed Trabeculae"),
                                           selectInput("Furrow_ETB_2","Extent",c("Full length of furrow","Partial","Unknown")),
                                           conditionalPanel("input.Furrow_ETB_2=='Partial'",
                                                            numericInput("Furrow_ETB_3","Approximate percentage of length of furrow with exposed trabeculae",value=50),
                                                            textInput("Furrow_ETB_4","Describe location of exposed trabeculae",value=NA)))))
Furrow_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Impression####
Impression_UI<-tagList(h3("Impression Description"))
Impression_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}

#Depression####
Depression_UI<-tagList(h3("Depression Description"))
Depression_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Inclusion####
Inclusion_UI<-tagList(h3("Inclusion Description"))
Inclusion_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}

#Fracture####
Fracture_UI<-tagList(fixedPage(h3("Fracture Description"),
                     column(width=6,h4("Type"),
                            selectInput("Fracture_NLine","Number of fracture lines",c("Single","Multiple")),
                            conditionalPanel("input.Fracture_NLine=='Multiple'",
                                             numericInput("Fracture_NLine2","Minimum possible number unique fracture lines",value=1),
                                             numericInput("Fracture_NLine3","Maximum possible number unique fracture lines",value=NA)),
                            checkboxInput("Fracture_Complete","Complete fracture?",value=TRUE),
                            conditionalPanel("input.Fracture_NLine == 'Single-1' && input.Fracture_Complete",
                                             selectInput("Fracture_TypeA","Type of fracture",c("Simple","Avulsion","Compression","Impacted","Other")),
                                             conditionalPanel("input.Fracture_TypeA=='Other'",textInput("Fracture_Type2A","Define other",value=NA)),
                                             selectInput("Fracture_PatternA","Fracture Pattern",c("Straight Transverse"="Transverse","Oblique","Straight Vertical/Linear"="Linear","Spiral","Other")),
                                             conditionalPanel("input.Fracture_PatternA=='Other'",textInput("Fracture_PatternA2","Define other",value=NA))),
                            conditionalPanel("input.Fracture_NLine == 'Single-1' && input.Fracture_Complete==false",
                                             selectInput("Fracture_TypeB","Type of fracture",c("Greenstick","Hinge","Buckle","Compression","Other")),
                                             conditionalPanel("input.Fracture_TypeB=='Other'",textInput("Fracture_Type2B","Define other",value=NA)),
                                             selectInput("Fracture_PatternB","Fracture Pattern",c("Straight Transverse"="Transverse","Oblique","Straight Vertical/Linear"="Linear","Spiral","Wedge","Other")),
                                             conditionalPanel("input.Fracture_PatternB=='Other'",textInput("Fracture_Pattern2B","Define other",value=NA))),
                            conditionalPanel("input.Fracture_NLine == 'Multiple' && input.Fracture_Complete",
                                             selectInput("Fracture_TypeC","Type of fracture",c("Comminuted","Depressed","Compression","Impacted","Other")),
                                             conditionalPanel("input.Fracture_TypeC=='Other'",textInput("Fracture_Type2C","Define other",value=NA)),
                                             selectInput("Fracture_PatternC","Fracture Pattern",c("Radiating","Concentric","Segmented","Butterfly","Hoop","Wedge","Other")),
                                             conditionalPanel("input.Fracture_PatternC=='Other'",textInput("Fracture_Pattern2C","Define other",value=NA))),
                            conditionalPanel("input.Fracture_NLine == 'Multiple' && input.Fracture_Complete==false",
                                             selectInput("Fracture_TypeD","Type of fracture",c("Greenstick","Hinge","Depressed","Buckle","Compression","Other")),
                                             conditionalPanel("input.Fracture_TypeD=='Other'",textInput("Fracture_Type2D","Define other",value=NA)),
                                             selectInput("Fracture_PatternD","Fracture Pattern",c("Radiating","Concentric","Segmented","Butterfly","Hoop","Wedge","Other")),
                                             conditionalPanel("input.Fracture_PatternD=='Other'",textInput("Fracture_Pattern2D","Define other",value=NA)))),
                     column(width=6,h4("Healing"),
                            checkboxInput("Fracture_Displaced","Displaced?",value=FALSE),
                            conditionalPanel("input.Fracture_Displaced",selectInput("Fracture_Displaced2","Type of displacement",c("Translated","Angulated","Rotated","Shortened","Other")),
                                             conditionalPanel("input.Fracture_Displaced2 == 'Other'",textInput("Fracture_Displaced3","Define other",value=NA))),
                            checkboxInput("Fracture_Callus","Callus Formation?",value=FALSE),
                            checkboxInput("Fracture_NonUnion","Non Union?",value=FALSE),
                            conditionalPanel("input.Fracture_NonUnion",checkboxInput("Fracture_NonUnion2","Healing on ununited edges?",value=FALSE),
                                             conditionalPanel("input.Fracture_NonUnion2",textInput("Fracture_Nonunion3","Describe evidence of healing",value="Rounding of edges")),
                                             selectInput("Fracture_NonUnion4","Extent of Non-union",c("Complete","Partial")),
                                             conditionalPanel("input.Fracture_NonUnion4=='Partial'",numericInput("Fracture_NonUnion5","Approximate Percentage of fracture united",value=50))),
                            selectInput("Fracture_Medical","Medical intervention",multiple=TRUE,selected="None",c("None","Pins","Plate","Screw","Splint","Periprosthetic fracture","Other")),
                            conditionalPanel("input.Fracture_Medical.indexOf('Other')>=0",textInput("Fracture_Medical2","Define Other",value=NA)))
                     ))
Fracture_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
  if(input$Fracture_Complete){Table$Des1<-paste("Custom",input$Fracture_NLine,"Complete fracture")}else{Table$Des1<-paste("Custom",input$Fracture_NLine,"incomplete fracture")}
  NatureNames<-"FractureLines,Complete,FractureType,FraturePattern,Displaced,Callus,NonUnion,MedialIntervention"
  if(input$Fracture_NLine=='Multiple'){NatureValue<-paste0(input$Fracture_NLine2,"-",input$Fracture_NLine3)}else{NatureValue<-"1-1"}
  
}
#Amputation####
Amputation_UI<-tagList(h3("Amputation Description"))
Amputation_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Displacement####
Displacement_UI<-tagList(h3("Displacement Description"),
                         column(width=4,
                                img(src="Displacement.png",height=350)),
                         column(width=4,
                                selectInput("Displacement_Type","Type of Displacement abnormality",c("Break in bone continuity"="Continuity Break","Joint displacement")),
                                selectInput("Displacement_Direction","Direction of displacement",multiple=TRUE,c("Superior","Inferior","Medial","Lateral","Anterior","Posterior")),
                                selectInput("Displacement_Degree","Degree of displacment",c("100%","75-<100%","50-<75%","25-<50%","<25%"))),
                         column(width=4,
                                conditionalPanel("input.Displacement_Type=='Continuity Break'",
                                                 selectInput("Displacment_CB1","Surface Joining",c("None","Partial","Complete"))),
                                conditionalPanel("input.Displacement_Type=='Joint displacement'",
                                                 checkboxInput("Displacement_JD_Fusion","Joint Fusion"),
                                                 conditionalPanel("input.Displacement_JD_Fusion",selectInput("Displacement_JD_Fusion2","Extent of fusion",c("Complete","Partial","Unknown"))),
                                                 h3("Side A (Concave)"),
                                                 checkboxInput("Displacement_JDA_Extension","Extension of articular surface"),
                                                 conditionalPanel("input.Displacement_JDA_Extension",selectInput("Displacement_JDA_Extension2","Extension Bone surface",c("Smooth","Pitted","Polished","Other")),
                                                                  conditionalPanel("input.Displacement_JDA_Extension2=='Other'"),textInput("Displacement_JDA_Extension3","Define Other",value=NA)),
                                                 checkboxInput("Displacement_JDA_Facet","New Articular facet formation"),
                                                 conditionalPanel("input.Displacement_JDA_Facet",selectInput("Displacement_JDA_Facet2","Facet Bone surface",c("Smooth","Pitted","Polished","Other")),
                                                                  conditionalPanel("input.Displacement_JDA_Facet2=='Other'"),textInput("Displacement_JD_Facet3","Define Other",value=NA)),
                                                 checkboxInput("Displacement_JDA_NewBone","New bone growth"),
                                                 conditionalPanel("input.Displacement_JDA_NewBone",
                                                                  textInput("Displacement_JDA_NewBone2","Location of new bone",value=NA),
                                                                  selectInput("Displacement_JDA_NewBone3","Type of bone growth",c("Woven","Scerlotic","Mixed"))),
                                                 h3("Side B (Convex)"),
                                                 checkboxInput("Displacement_JDB_Extension","Extension of articular surface"),
                                                 conditionalPanel("input.Displacement_JDB_Extension",selectInput("Displacement_JDB_Extension2","Extension Bone surface",c("Smooth","Pitted","Polished","Other")),
                                                                  conditionalPanel("input.Displacement_JDB_Extenion2=='Other'"),textInput("Displacement_JDB_Extension3","Define Other",value=NA)),
                                                 checkboxInput("Displacement_JDB_Facet","New Articular facet formation"),
                                                 conditionalPanel("input.Displacement_JDB_Facet",selectInput("Displacement_JDB_Facet2","Facet Bone surface",c("Smooth","Pitted","Polished","Other")),
                                                                  conditionalPanel("input.Displacement_JDB_Facet2=='Other'"),textInput("Displacement_JDB_Facet3","Define Other",value=NA)),
                                                 checkboxInput("Displacement_JDB_NewBone","New bone growth"),
                                                 conditionalPanel("input.Displacement_JDB_NewBone",
                                                                  textInput("Displacement_JDB_NewBone2","Location of new bone",value=NA),
                                                                  selectInput("Displacement_JDB_NewBone3","Type of bone growth",c("Woven","Scerlotic","Mixed"))))))
Displacement_RC<-function(input){
  Table<-data.frame(NatureNames=NA,NatureValues=NA,Des1=NA)
}
#Other####
Other_UI<-tagList(h3("Other Description"),textInput("OtherTrauma","Describe Other Trauma",value=NA))
Other_RC<-function(input){
  Table<-data.frame(NatureNames="Other-Description",NatureValues=input$OtherTrauma,Des1="Other Trauma")
}