library(shiny);library(markdown)

shinyUI(navbarPage("Inventory",
                   tabPanel("Skull",
                            fluidPage(
                              column(width=4,
                                     h3("Present"),
                                     checkboxGroupInput("SkullPresent","tick if present",
                                                        choices=list("Right Incus"="rI","Left Incus"="lI","Right Malleous"="rM","Left Malleous"="lM","Right Stapes"="rS","Left Stapes"="lS",
                                                                     "vomer"="V","Right Inferior Nasal Concha"="rINC","Left Inferior Nasal Concha"="lINC","Right Palatine"="rPl","Left Palatine"="lPl",
                                                                     "Ethmoid"="E","Right Nasal"="rN","Left Nasal"="lN","Right Lacrimal"="rL","Left Lacrimal"="lL","Right Parietal"="rPr","Left Parietal"="lPr",
                                                                     "Right Zygomatic"="rZ","Left Zygomatic"="lZ","Frontal squama"="FS","Frontal Pars Orbitalis"="FPO","Frontal Supra-orbital"="FSO",
                                                                     "Right Temporal Squama"="rTS","Right Temporal Mastoid"="rTM","Right Temporal Petrous"="rTP","Right Temporal Zygomatic"="rTZ",
                                                                     "Left Temporal squama"="lTS","Left Temporal Mastoid"="lTM","Left Temporal Petrous"="lTP","Left Temporal Zygomatic"="lTZ",
                                                                     "Occipital Squamous"="OS","Occipital Basal"="OB","Occiptal Condylar Right"="rOC","Occiptal Condylar Left"="lOC",
                                                                     "Sphenoid Body"="SB","Sphenoid Pterygoid Right"="rSP","Sphenoid Pterygoid Left"="lSP","Sphenoid Wings Right"="rSW","Sphenoid Wings Left"="lSW","Mandible Corpus"="MC","Mandible Ramus Right"="rMR","Mandible Ramus Left"="lMR",
                                                                     "Right Maxilla alveolar"="rMA","Right Maxilla Palatine"="rMP","Right Maxilla Frontal"="rMF","Left Maxilla alveolar"="lMA","Left Maxilla Palatine"="lMP","Left Maxilla Frontal"="lMF"))
                                     ),
                              column(width=4,
                                     h3("Complete"),
                                     checkboxGroupInput("SkullComplete","tick if 100% complete",
                                                        choices=list("Right Incus"="rI","Left Incus"="lI","Right Malleous"="rM","Left Malleous"="lM","Right Stapes"="rS","Left Stapes"="lS",
                                                                     "vomer"="V","Right Inferior Nasal Concha"="rINC","Left Inferior Nasal Concha"="lINC","Right Palatine"="rPl","Left Palatine"="lPl",
                                                                     "Ethmoid"="E","Right Nasal"="rN","Left Nasal"="lN","Right Lacrimal"="rL","Left Lacrimal"="lL","Right Parietal"="rPr","Left Parietal"="lPr",
                                                                     "Right Zygomatic"="rZ","Left Zygomatic"="lZ","Frontal squama"="FS","Frontal Pars Orbitalis"="FPO","Frontal Supra-orbital"="FSO",
                                                                     "Right Temporal Squama"="rTS","Right Temporal Mastoid"="rTM","Right Temporal Petrous"="rTP","Right Temporal Zygomatic"="rTZ",
                                                                     "Left Temporal squama"="lTS","Left Temporal Mastoid"="lTM","Left Temporal Petrous"="lTP","Left Temporal Zygomatic"="lTZ",
                                                                     "Occipital Squamous"="OS","Occipital Basal"="OB","Occiptal Condylar Right"="rOC","Occiptal Condylar Left"="lOC",
                                                                     "Sphenoid Body"="SB","Sphenoid Pterygoid Right"="rSP","Sphenoid Pterygoid Left"="lSP","Sphenoid Wings Right"="rSW","Sphenoid Wings Left"="lSW","Mandible Corpus"="MC","Mandible Ramus Right"="rMR","Mandible Ramus Left"="lMR",
                                                                     "Right Maxilla alveolar"="rMA","Right Maxilla Palatine"="rMP","Right Maxilla Frontal"="rMF","Left Maxilla alveolar"="lMA","Left Maxilla Palatine"="lMP","Left Maxilla Frontal"="lMF"))
                              ),
                              column(width=4,
                                     h3("Results"),
                                     h4("Score"),
                                     h5(textOutput("SkullScore")),
                                     h4("Count"),
                                     h5(textOutput("SkullRecorded")),
                                     h5(textOutput("SkullComplete")),
                                     h4("Errors"),
                                     h5(textOutput("SkullErrors"))
                                     )
                            )),
                   
                   tabPanel("Vertebrae",
                            fluidPage(column(width=4,
                                             h4("Present"),
                                             checkboxGroupInput("VertPresent","Tick if present",
                                                                choices=list("Hyoid"="H","Atlas"="C1","Axis"="C2","Axis Odentoid"="C2O",
                                                                             "C3-7 body[3]"="C3b","C3-7 arch[3]"="C3a","C3-7 body[4]"="C4b","C3-7 arch[4]"="C4a","C3-7 body[5]"="C5b","C3-7 arch[5]"="C5a",
                                                                             "C3-7 body[6]"="C6b","C3-7 arch[6]"="C6a","C3-7 body[7]"="C7b","C3-7 arch[7]"="C7a",
                                                                             "T1-12 body[1]"="T1b","T1-12 arch[1]"="T1a","T1-12 body[2]"="T2b","T1-12 arch[1]"="T2a","T1-12 body[3]"="T3b","T1-12 arch[3]"="T3a","T1-12 body[4]"="T4b","T1-12 arch[4]"="T4a",
                                                                             "T1-12 body[5]"="T5b","T1-12 arch[5]"="T5a","T1-12 body[6]"="T6b","T1-12 arch[6]"="T6a","T1-12 body[7]"="T7b","T1-12 arch[7]"="T7a","T1-12 body[8]"="T8b","T1-12 arch[8]"="T8a",
                                                                             "T1-12 body[9]"="T9b","T1-12 arch[9]"="T9a","T1-12 body[10]"="T10b","T1-12 arch[10]"="T10a","T1-12 body[11]"="T11b","T1-12 arch[11]"="T11a","T1-12 body[12]"="T12b","T1-12 arch[12]"="T12a",
                                                                             "L1-5 body[1]"="L1b","L1-5 arch[1]"="L1a","L1-5 body[2]"="L2b","L1-5 arch[2]"="L2a","L1-5 body[3]"="L3b","L1-5 arch[3]"="L3a","L1-5 body[4]"="L4b","L1-5 arch[4]"="L4a","L1-5 body[5]"="L5b","L1-5 arch[5]"="L5a"))
                            ),
                            column(width=4,
                                   h4("Complete"),
                                   checkboxGroupInput("VertComplete","Tick if 100% complete",
                                                      choices=list("Hyoid"="H","Atlas"="C1","Axis"="C2","Axis Odentoid"="C2O",
                                                                   "C3 body"="C3b","C3 arch"="C3a","C4 body"="C4b","C4 arch"="C4a","C5 body"="C5b","C5 arch"="C5a",
                                                                   "C6 body"="C6b","C6 arch"="C6a","C7 body"="C7b","C7 arch"="C7a",
                                                                   "T1 body"="T1b","T1 arch"="T1a","T2 body"="T2b","T2 arch"="T2a","T3 body"="T3b","T3 arch"="T3a","T4 body"="T4b","T4 arch"="T4a",
                                                                   "T5 body"="T5b","T5 arch"="T5a","T6 body"="T6b","T6 arch"="T6a","T7 body"="T7b","T7 arch"="T7a","T8 body"="T8b","T8 arch"="T8a",
                                                                   "T9 body"="T9b","T9 arch"="T9a","T10 body"="T10b","T10 arch"="T10a","T11 body"="T11b","T11 arch"="T11a","T12 body"="T12b","T12 arch"="T12a",
                                                                   "L1 body"="L1b","L1 arch"="L1a","L2 body"="L2b","L2 arch"="L2a","L3 body"="L3b","L3 arch"="L3a","L4 body"="L4b","L4 arch"="L4a","L5 body"="L5b","L5 arch"="L5a"))
                            ),
                            column(width=4,
                                   h4("Results"),
                                   h4("Score"),
                                   h5(textOutput("VertScore")),
                                   h4("Count"),
                                   h5(textOutput("VertRecorded")),
                                   h5(textOutput("VertComplete")),
                                   h4("Errors"),
                                   h5(textOutput("VertErrors"))
                            )
                            )
                   ),
                   tabPanel("Thorax",
                            fluidPage(column(width=4,
                                             h3("Present"),
                                             checkboxGroupInput("ThoraxPresent","tick if present",
                                                                choices=list("Manubrium"="M","Corpus Sterni"="CS","Xiphoid"="X",
                                                                             "Right 1st Rib"="r1","Left 1st Rib"="l1","Right 2nd rib"="r2","Left 2nd Rib"="l2",
                                                                             "Right 12th Rib"="r12","Left 12th Rib"="l12","Right 11th Rib"="r11","Left 11th Rib"="l11",
                                                                             "Right 3rd -10th(3)"="r3","Right 3rd -10th(4)"="r4","Right 3rd -10th(5)"="r5","Right 3rd -10th(6)"="r6",
                                                                             "Right 3rd -10th(7)"="r7","Right 3rd -10th(8)"="r8","Right 3rd -10th(9)"="r9","Right 3rd -10th(10)"="r10",
                                                                             "Left 3rd -10th(3)"="l3","Left 3rd -10th(4)"="l4","Left 3rd -10th(5)"="l5","Left 3rd -10th(6)"="l6",
                                                                             "Left 3rd -10th(7)"="l7","Left 3rd -10th(8)"="l8","Left 3rd -10th(9)"="l9","Left 3rd -10th(10)"="l10"))
                                             ),
                                      column(width=4,
                                             h3("Complete"),
                                             checkboxGroupInput("ThoraxComplete","tick if 100% Complete",
                                                                choices=list("Manubrium"="M","Corpus Sterni"="CS","Xiphoid"="X",
                                                                             "Right 1st Rib"="r1","Left 1st Rib"="l1","Right 2nd rib"="r2","Left 2nd Rib"="l2",
                                                                             "Right 12th Rib"="r12","Left 12th Rib"="l12","Right 11th Rib"="r11","Left 11th Rib"="l11",
                                                                             "Right 3rd -10th(3)"="r3","Right 3rd -10th(4)"="r4","Right 3rd -10th(5)"="r5","Right 3rd -10th(6)"="r6",
                                                                             "Right 3rd -10th(7)"="r7","Right 3rd -10th(8)"="r8","Right 3rd -10th(9)"="r9","Right 3rd -10th(10)"="r10",
                                                                             "Left 3rd -10th(3)"="l3","Left 3rd -10th(4)"="l4","Left 3rd -10th(5)"="l5","Left 3rd -10th(6)"="l6",
                                                                             "Left 3rd -10th(7)"="l7","Left 3rd -10th(8)"="l8","Left 3rd -10th(9)"="l9","Left 3rd -10th(10)"="l10"
                                                                ))
                                             ),
                                      column(width=4,
                                             h3("Results"),
                                             h4("Score"),
                                             h5(textOutput("ThoraxScore")),
                                             h4("Count"),
                                             h5(textOutput("ThoraxRecorded")),
                                             h5(textOutput("ThoraxComplete")),
                                             h4("Errors"),
                                             h5(textOutput("ThoraxErrors"))
                                             )
                                               )
                   ),
                   
                   tabPanel("Girdles",
                            fluidPage(column(width=4,
                                             h4("Present"),
                                             checkboxGroupInput("ShoulderPresent","Tick if present",
                                                                choices=list("Right Clavicle"="rC","Left Clavicle"="lC",
                                                                             "Right Scapula body"="rSB","Right Glenoid cavity"="rG","Right Scapular spine"="rSS","Right Coracoid"="rCC","Right Acromion"="rA",
                                                                             "Left Scapula body"="lSB","Left Glenoid cavity"="lG","Left Scapular spine"="lSS","Left Coracoid"="lCC","Left Acromion"="lA")),
                                             checkboxGroupInput("PelvisPresent",label=NULL,
                                                                choices=list("Right Auricular surface (sacrum)"="rASS","Left Auricular surface (sacrum)"="lASS","Right alae"="rAl","Left Alae"="lAL",
                                                                             "Sacrum neural arch"="Sa","S1 body"="S1b","S2 body"="S2b","Lower Sacrum body"="LSb","Coccyx"="C",
                                                                             "Right Illium"="rIL","Right Ischium"="rIS","Right Pubis"="rp","Right Acetabulum"="rAC","Right Pubic Synthesis"="rPS","Right Auricular surface (os coxa)"="rASOS",
                                                                             "Left Illium"="lIL","Left Ischium"="lIS","Left Pubis"="lp","Left Acetabulum"="lAC","Left Pubic Synthesis"="lPS","Left Auricular surface (os coxa)"="lASOS"))
                            ),
                            column(width=4,
                                   h4("Complete"),
                                   checkboxGroupInput("ShoulderComplete","Tick if 100% complete",
                                                      choices=list("Right Clavicle"="rC","Left Clavicle"="lC",
                                                                   "Right Scapula body"="rSB","Right Glenoid cavity"="rG","Right Scapular spine"="rSS","Right Coracoid"="rCC","Right Acromion"="rA",
                                                                   "Left Scapula body"="lSB","Left Glenoid cavity"="lG","Left Scapular spine"="lSS","Left Coracoid"="lCC","Left Acromion"="lA")),
                                   checkboxGroupInput("PelvisComplete",label=NULL,
                                                      choices=list("Right Auricular surface (sacrum)"="rASS","Left Auricular surface (sacrum)"="lASS","Right alae"="rAl","Left Alae"="lAL",
                                                                   "Sacrum neural arch"="Sa","S1 body"="S1b","S2 body"="S2b","Lower Sacrum body"="LSb","Coccyx"="C",
                                                                   "Right Illium"="rIL","Right Ischium"="rIS","Right Pubis"="rp","Right Acetabulum"="rAC","Right Pubic Synthesis"="rPS","Right Auricular surface (os coxa)"="rASOS",
                                                                   "Left Illium"="lIL","Left Ischium"="lIS","Left Pubis"="lp","Left Acetabulum"="lAC","Left Pubic Synthesis"="lPS","Left Auricular surface (os coxa)"="lASOS"))
                            ),
                            column(width=4,
                                   h3("Results"),
                                   h4("Scores"),
                                   h5(textOutput("ShoulderScore")),
                                   h5(textOutput("PelvisScore")),
                                   h4("Counts"),
                                   h5(textOutput("ShoulderRecorded")),
                                   h5(textOutput("ShoulderComplete")),
                                   h5(textOutput("PelvisRecorded")),
                                   h5(textOutput("PelvisComplete")),
                                   h4("Errors"),
                                   h5(textOutput("ShoulderErrors")),
                                   h5(textOutput("PelvisErrors"))
                            )
                            )
                   ),
                   tabPanel("Upper limb",
                            fluidPage(column(width=4,
                                             h4("Present"),
                                             checkboxGroupInput("ArmPresent","Tick if present",
                                                                choices=list("Right Humeral Head"="rHH","Right Humerus Proximal End"="rHP","Right Humeral Shaft"="rHS","Right Humerus Distal end"="rHD",
                                                                             "Left Humeral Head"="lHH","Left Humerus Proximal End"="lHP","Left Humeral Shaft"="lHS","Left Humerus Distal end"="lHD",
                                                                             "Right Radial Head"="rRH","Right Radius Proximal Shaft"="rRP","Right Radial Shaft"="rRS","Right Radius Distal end"="rRD",
                                                                             "Left Radial Head"="lRH","Left Radius Proximal end"="lRP","Left Radial Shaft"="lRS","Left Radius Distal end"="lRD",
                                                                             "Right Olecranon Process"="rO","Right Coronid process"="rC","Right Ulna Proximal shaft"="rUP","Right Ulna Shaft"="rUS","Right Ulna head"="rUH",
                                                                             "Left Olecranon Process"="lO","Left Coronid process"="lC","Left Ulna Proximal shaft"="lUP","Left Ulna Shaft"="lUS","Left Ulna head"="lUH")),
                                             checkboxGroupInput("HandPresent",label=NULL,
                                                                choices=list("Right Scaphoid"="rS","Right Lunate"="rL","Right Triquetral"="rTQ","Right Pisiform"="rP","Right Trapezium"="rTM","Right Trapezoid"="rTD","Right Capitate"="rC","Right Hamate"="rH",
                                                                             "Left Scaphoid"="lS","Left Lunate"="lL","Left Triquetral"="lTQ","Left Pisiform"="lP","Left Trapezium"="lTM","Left Trapezoid"="lTD","Left Capitate"="lC","Left Hamate"="lH",
                                                                             "Right Metacarpal 1"="rM1","Right Metacarpal 2"="rM2","Right Metacarpal 3"="rM3","Right Metacarpal 4"="rM4","Right Metacarpal 5"="rM5",
                                                                             "Left Metacarpal 1"="lM1","Left Metacarpal 2"="lM2","Left Metacarpal 3"="lM3","Left Metacarpal 4"="lM4","Left Metacarpal 5"="lM5",
                                                                             "Right Proximal Phalanx 1"="rPP1","Right Proximal Phalanx 2"="rPP2","Right Proximal Phalanx 3"="rPP3","Right Proximal Phalanx 4"="rPP4","Right Proximal Phalanx 5"="rPP5",
                                                                             "Right Intermediate Phalanx 2"="rIP2","Right Intermediate Phalanx 3"="rIP3","Right Intermediate Phalanx 4"="rIP4","Right Intermediate Phalanx 5"="rIP5",
                                                                             "Right Distal Phalanx 1"="rDP1","Right Distal Phalanx 2"="rDP2","Right Distal Phalanx 3"="rDP3","Right Distal Phalanx 4"="rDP4","Right Distal Phalanx 5"="rDP5",
                                                                             "Left Proximal Phalanx 1"="lPP1","Left Proximal Phalanx 2"="lPP2","Left Proximal Phalanx 3"="lPP3","Left Proximal Phalanx 4"="lPP4","Left Proximal Phalanx 5"="lPP5",
                                                                             "Left Intermediate Phalanx 2"="lIP2","Left Intermediate Phalanx 3"="lIP3","Left Intermediate Phalanx 4"="lIP4","Left Intermediate Phalanx 5"="lIP5",
                                                                             "Left Distal Phalanx 1"="lDP1","Left Distal Phalanx 2"="lDP2","Left Distal Phalanx 3"="lDP3","Left Distal Phalanx 4"="lDP4","Left Distal Phalanx 5"="lDP5",
                                                                             "Tick if all Metacarpals are ordered"="MO","Tick if all phalanges are ordered"="PO","Tick if all Metacarpals sided"="MS","Tick if all Phalanges sided"="PS"))
                            ),
                            column(width=4,
                                   h4("Complete"),
                                   checkboxGroupInput("ArmComplete","Tick if 100% complete",
                                                      choices=list("Right Humeral Head"="rHH","Right Humerus Proximal End"="rHP","Right Humeral Shaft"="rHS","Right Humerus Distal end"="rHD",
                                                                   "Left Humeral Head"="lHH","Left Humerus Proximal End"="lHP","Left Humeral Shaft"="lHS","Left Humerus Distal end"="lHD",
                                                                   "Right Radial Head"="rRH","Right Radius Proximal Shaft"="rRP","Right Radial Shaft"="rRS","Right Radius Distal end"="rRD",
                                                                   "Left Radial Head"="lRH","Left Radius Proximal end"="lRP","Left Radial Shaft"="lRS","Left Radius Distal end"="lRD",
                                                                   "Right Olecranon Process"="rO","Right Coronid process"="rC","Right Ulna Proximal shaft"="rUP","Right Ulna Shaft"="rUS","Right Ulna head"="rUH",
                                                                   "Left Olecranon Process"="lO","Left Coronid process"="lC","Left Ulna Proximal shaft"="lUP","Left Ulna Shaft"="lUS","Left Ulna head"="lUH")),
                                   checkboxGroupInput("HandComplete",label=NULL,
                                                      choices=list("Right Scaphoid"="rS","Right Lunate"="rL","Right Triquetral"="rTQ","Right Pisiform"="rP","Right Trapezium"="rTM","Right Trapezoid"="rTD","Right Capitate"="rC","Right Hamate"="rH",
                                                                   "Left Scaphoid"="lS","Left Lunate"="lL","Left Triquetral"="lTQ","Left Pisiform"="lP","Left Trapezium"="lTM","Left Trapezoid"="lTD","Left Capitate"="lC","Left Hamate"="lH",
                                                                   "Right Metacarpal 1"="rM1","Right Metacarpal 2"="rM2","Right Metacarpal 3"="rM3","Right Metacarpal 4"="rM4","Right Metacarpal 5"="rM5",
                                                                   "Left Metacarpal 1"="lM1","Left Metacarpal 2"="lM2","Left Metacarpal 3"="lM3","Left Metacarpal 4"="lM4","Left Metacarpal 5"="lM5",
                                                                   "Right Proximal Phalanx 1"="rPP1","Right Proximal Phalanx 2"="rPP2","Right Proximal Phalanx 3"="rPP3","Right Proximal Phalanx 4"="rPP4","Right Proximal Phalanx 5"="rPP5",
                                                                   "Right Intermediate Phalanx 2"="rIP2","Right Intermediate Phalanx 3"="rIP3","Right Intermediate Phalanx 4"="rIP4","Right Intermediate Phalanx 5"="rIP5",
                                                                   "Right Distal Phalanx 1"="rDP1","Right Distal Phalanx 2"="rDP2","Right Distal Phalanx 3"="rDP3","Right Distal Phalanx 4"="rDP4","Right Distal Phalanx 5"="rDP5",
                                                                   "Left Proximal Phalanx 1"="lPP1","Left Proximal Phalanx 2"="lPP2","Left Proximal Phalanx 3"="lPP3","Left Proximal Phalanx 4"="lPP4","Left Proximal Phalanx 5"="lPP5",
                                                                   "Left Intermediate Phalanx 2"="lIP2","Left Intermediate Phalanx 3"="lIP3","Left Intermediate Phalanx 4"="lIP4","Left Intermediate Phalanx 5"="lIP5",
                                                                   "Left Distal Phalanx 1"="lDP1","Left Distal Phalanx 2"="lDP2","Left Distal Phalanx 3"="lDP3","Left Distal Phalanx 4"="lDP4","Left Distal Phalanx 5"="lDP5"))
                            ),
                            column(width=4,
                                   h3("Results"),
                                   h4("Scores"),
                                   h5(textOutput("ArmScore")),
                                   h5(textOutput("HandScore")),
                                   h4("Counts"),
                                   h5(textOutput("ArmRecorded")),
                                   h5(textOutput("ArmComplete")),
                                   h5(textOutput("HandRecorded")),
                                   h5(textOutput("HandComplete")),
                                   h4("Errors"),
                                   h5(textOutput("ArmErrors")),
                                   h5(textOutput("HandErrors"))
                            )
                            )
                   ),
                   tabPanel("Lower limb",
                            fluidPage(column(width=4,
                                             h4("Present"),
                                             checkboxGroupInput("LegPresent","Tick if present",
                                                                choices=list("Right Femoral head"="rFH","Right Femur Neck"="rFN","Right Femur trochanteric region"="rFT","Right Femur shaft"="rFS","Right femur distal end"="rFD","Right Patella"="rP",
                                                                             "Left Femoral head"="lFH","Left Femur Neck"="lFN","Left Femur trochanteric region"="lFT","Left Femur shaft"="lFS","Left femur distal end"="lFD","Left Patella"="lP",
                                                                             "Right Tibial Plateau"="rTP","Right Tibia Proximal end"="rPT","Right Tibial shaft"="rTS","Right Tibia Distal end"="rTD",
                                                                             "Left Tibial Plateau"="lTP","Left Tibia Proximal end"="lPT","Left Tibial shaft"="lTS","Left Tibia Distal end"="lTD",
                                                                             "Right Fibula Proximal end"="rFIP","Right Fibula shaft"="rFIS","Right Fibula distal end"="rFID","Left Fibula Proximal end"="lFIP","Left Fibula shaft"="lFIS","Left Fibula distal end"="lFID")),
                                             checkboxGroupInput("FootPresent",label=NULL,
                                                                choices=list("Right Talus"="rT","Right Calcaneus"="rCL","Right Cuboid"="rCB","Right Navicular"="rN","Right Lateral Cuneiform"="rLC","Right Intermediate Cuneiform"="rIC","Right Medial Cuneiform"="rMC",
                                                                             "Left Talus"="lT","Left Calcaneus"="lCL","Left Cuboid"="lCB","Left Navicular"="lN","Left Lateral Cuneiform"="lLC","Left Intermediate Cuneiform"="lIC","Left Medial Cuneiform"="lMC",
                                                                             "Right Metatarsal 1"="rM1","Right Metatarsal 2"="rM2","Right Metatarsal 3"="rM3","Right Metatarsal 4"="rM4","Right Metatarsal 5"="rM5",
                                                                             "Left Metatarsal 1"="lM1","Left Metatarsal 2"="lM2","Left Metatarsal 3"="lM3","Left Metatarsal 4"="lM4","Left Metatarsal 5"="lM5",
                                                                             "Right Proximal Phalanx 1"="rPP1","Right Proximal Phalanx 2"="rPP2","Right Proximal Phalanx 3"="rPP3","Right Proximal Phalanx 4"="rPP4","Right Proximal Phalanx 5"="rPP5",
                                                                             "Right Intermediate Phalanx 2"="rIP2","Right Intermediate Phalanx 3"="rIP3","Right Intermediate Phalanx 4"="rIP4","Right Intermediate Phalanx 5"="rIP5",
                                                                             "Right Distal Phalanx 1"="rDP1","Right Distal Phalanx 2"="rDP2","Right Distal Phalanx 3"="rDP3","Right Distal Phalanx 4"="rDP4","Right Distal Phalanx 5"="rDP5",
                                                                             "Left Proximal Phalanx 1"="lPP1","Left Proximal Phalanx 2"="lPP2","Left Proximal Phalanx 3"="lPP3","Left Proximal Phalanx 4"="lPP4","Left Proximal Phalanx 5"="lPP5",
                                                                             "Left Intermediate Phalanx 2"="lIP2","Left Intermediate Phalanx 3"="lIP3","Left Intermediate Phalanx 4"="lIP4","Left Intermediate Phalanx 5"="lIP5",
                                                                             "Left Distal Phalanx 1"="lDP1","Left Distal Phalanx 2"="lDP2","Left Distal Phalanx 3"="lDP3","Left Distal Phalanx 4"="lDP4","Left Distal Phalanx 5"="lDP5",
                                                                             "Tick if all Metatarsals are ordered"="MO","Tick if all phalanges are ordered"="PO","Tick if all Metatarsals sided"="MS","Tick if all Phalanges sided"="PS"))
                            ),
                            column(width=4,
                                   h4("Complete"),
                                   checkboxGroupInput("LegComplete","Tick if 100% complete",
                                                      choices=list("Right Femoral head"="rFH","Right Femur Neck"="rFN","Right Femur trochanteric region"="rFT","Right Femur shaft"="rFS","Right femur distal end"="rFD","Right Patella"="rP",
                                                                   "Left Femoral head"="lFH","Left Femur Neck"="lFN","Left Femur trochanteric region"="lFT","Left Femur shaft"="lFS","Left femur distal end"="lFD","Left Patella"="lP",
                                                                   "Right Tibial Plateau"="rTP","Right Tibia Proximal end"="rPT","Right Tibial shaft"="rTS","Right Tibia Distal end"="rTD",
                                                                   "Left Tibial Plateau"="lTP","Left Tibia Proximal end"="lPT","Left Tibial shaft"="lTS","Left Tibia Distal end"="lTD",
                                                                   "Right Fibula Proximal end"="rFIP","Right Fibula shaft"="rFIS","Right Fibula distal end"="rFID","Left Fibula Proximal end"="lFIP","Left Fibula shaft"="lFIS","Left Fibula distal end"="lFID")),
                                   checkboxGroupInput("FootComplete",label=NULL,
                                                      choices=list("Right Talus"="rT","Right Calcaneus"="rCL","Right Cuboid"="rCB","Right Navicular"="rN","Right Lateral Cuneiform"="rLC","Right Intermediate Cuneiform"="rIC","Right Medial Cuneiform"="rMC",
                                                                   "Left Talus"="lT","Left Calcaneus"="lCL","Left Cuboid"="lCB","Left Navicular"="lN","Left Lateral Cuneiform"="lLC","Left Intermediate Cuneiform"="lIC","Left Medial Cuneiform"="lMC",
                                                                   "Right Metatarsal 1"="rM1","Right Metatarsal 2"="rM2","Right Metatarsal 3"="rM3","Right Metatarsal 4"="rM4","Right Metatarsal 5"="rM5",
                                                                   "Left Metatarsal 1"="lM1","Left Metatarsal 2"="lM2","Left Metatarsal 3"="lM3","Left Metatarsal 4"="lM4","Left Metatarsal 5"="lM5",
                                                                   "Right Proximal Phalanx 1"="rPP1","Right Proximal Phalanx 2"="rPP2","Right Proximal Phalanx 3"="rPP3","Right Proximal Phalanx 4"="rPP4","Right Proximal Phalanx 5"="rPP5",
                                                                   "Right Intermediate Phalanx 2"="rIP2","Right Intermediate Phalanx 3"="rIP3","Right Intermediate Phalanx 4"="rIP4","Right Intermediate Phalanx 5"="rIP5",
                                                                   "Right Distal Phalanx 1"="rDP1","Right Distal Phalanx 2"="rDP2","Right Distal Phalanx 3"="rDP3","Right Distal Phalanx 4"="rDP4","Right Distal Phalanx 5"="rDP5",
                                                                   "Left Proximal Phalanx 1"="lPP1","Left Proximal Phalanx 2"="lPP2","Left Proximal Phalanx 3"="lPP3","Left Proximal Phalanx 4"="lPP4","Left Proximal Phalanx 5"="lPP5",
                                                                   "Left Intermediate Phalanx 2"="lIP2","Left Intermediate Phalanx 3"="lIP3","Left Intermediate Phalanx 4"="lIP4","Left Intermediate Phalanx 5"="lIP5",
                                                                   "Left Distal Phalanx 1"="lDP1","Left Distal Phalanx 2"="lDP2","Left Distal Phalanx 3"="lDP3","Left Distal Phalanx 4"="lDP4","Left Distal Phalanx 5"="lDP5"))
                            ),
                            column(width=4,
                                   h3("Results"),
                                   h4("Scores"),
                                   h5(textOutput("LegScore")),
                                   h5(textOutput("FootScore")),
                                   h4("Counts"),
                                   h5(textOutput("LegRecorded")),
                                   h5(textOutput("LegComplete")),
                                   h5(textOutput("FootRecorded")),
                                   h5(textOutput("FootComplete")),
                                   h4("Errors"),
                                   h5(textOutput("LegErrors")),
                                   h5(textOutput("FootErrors"))
                            )
                            )
                   ),
                   tabPanel("Unidentified fragments",
                            fluidPage(
                              h4("Enter number of fragments"),
                              column(width=4,
                                             
                                             numericInput("USkull","Skull",value=0,width='50%'),
                                             numericInput("ULimb","Limb Long bone",value=0,width='50%'),
                                             numericInput("UVert","Vertebrae",value=0,width='50%')
                                             
                                             
                            ),
                            column(width=4,
                                   numericInput("UHandFoot","Hand/foot",value=0,width='50%'),
                                   numericInput("UClavScap","Clavicle/Scapula",value=0,width='50%'),
                                   numericInput("UOsCoxae","Os coxae",value=0,width='50%')
                                   
                            ),
                            column(width=4,
                                   numericInput("UOther","Other fragments",value=0,width='50%'),
                                   h3("Score"),
                                   h4(textOutput("UFs"))
                                   )
                            
                          
                            )
                   ),
                   tabPanel("Non Metric traits",
                            fluidPage(column(width=4,
                                             h4("Cranial"),
                                             checkboxGroupInput("NMCPresent","Tick if present",
                                                                choices=list("Highest Nuchal line"="HNL","Ossicle at Lambda"="OL","Ossicle(s)in lambdoid suture"="OLS","Parietal foramen"="PF","Ossicle at bregma"="OB","Metopic suture"="MS",
                                                                             "Osscile(s) in coronal suture"="OCS","Ossicle at Pterion"="OP","Fronto-temporal articulation"="FTA","Ossicle at Parietal notch"="OPN","Ossicle at asterion"="OA","Auditory torus"="AT",
                                                                             "Foramen of Huschke"="FH","Mastoid formen absent"="MFA","Posterior Condylar canal open"="PCC","Double condylar facet"="DCF","Precondylar tubercle"="PCT",
                                                                             "Double anterior condylar canal"="ACC","Incomplete foramen ovale"="IFO","Open foramen spinosum"="OFS","Accessory lesser palatine foramen"="ALPF","Palatine torus"="PT","Maxillary torus"="MT",
                                                                             "Absent Zygomaticofacial foramen"="AZF","Bridging of supraorbital notch"="BSON","Accessory supraorbital foramen"="ASOF","Anterior ethmoid formen extrasutural"="AEFE","Posterior ethmoid formen absent"="PEFA","Accessory infraorbital foramen"="AIOF"))
                            ),
                            column(width=4,
                                   h4("PostCranial"),
                                   checkboxGroupInput("NMPCPresent","Tick if present",
                                                      choices=list("Allen's Fossa"="AF","Poirier's Facet"="PF","Plaque"="P","Hypotrochanteric fossa"="HTF","Exostosis in trochanteric fossa"="ETF","Third Throchanter"="3T",
                                                                   "Medial tibial squatting facet"="MTSF","Lateral tibial squatting facet"="LTSF","Supracondyloid process"="SCP","Septal aperture"="SA","Acetabular crease"="AC","Sternal foramen"="SF",
                                                                   "Accessory sacral facet(s)"="ASF","Acromial articular facet"="AAF","Bridging of suprascapular notch"="BSSN","Circumflex Sulcus"="CS","Vastus notch"="VN","Vastus Fossa"="VF",
                                                                   "Emarginate Patella"="EP","Os trigonum"="OT","Medial talar facet"="MTF","Lateral Talar extension"="LTE","Double inferior calcaneal faset"="DICF","Double anterior calcaneal facet"="DACF",
                                                                   "Absent anterior calcaneal facet"="AACF","Peroneal tubercle"="PT","Double atlas facet"="DAF","Posterior atlas bridging"="PAB","Lateral atlas bridging"="LAB","Transverse foramen bipartite"="TFB"))
                            ),
                            column(width=4,
                                   h3("Results"),
                                   h4("Score"),
                                   h5(textOutput("NMScore")),
                                   h4("Counts"),
                                   h5(textOutput("NMCRecorded")),
                                   h5(textOutput("NMPCRecorded"))
                            )
                            )
                   ),
                   tabPanel("Custom feature",
                            fluidPage(column(width=4,
                                             h4("Feature names"),
                                             textInput("C1","Feature1",value="NA"),
                                             textInput("C2","Feature2",value="NA"),
                                             textInput("C3","Feature3",value="NA"),
                                             textInput("C4","Feature4",value="NA"),
                                             textInput("C5","Feature5",value="NA"),
                                             textInput("C6","Feature6",value="NA"),
                                             textInput("C7","Feature7",value="NA"),
                                             textInput("C8","Feature8",value="NA")
                            ),
                            column(width=4,
                                   h4("Present/Complete"),
                                   checkboxGroupInput("CustomPresent","tick if present",
                                                      choices=list("Feature 1"="C1","Feature 2"="C2","Feature 3"="C3","Feature 4"="C4",
                                                                   "Feature 5"="C5","Feature 6"="C6","Feature 7"="C7","Feature 8"="C8")),
                                   checkboxGroupInput("CustomComplete","tick if 100% complete",
                                                      choices=list("Feature 1"="C1","Feature 2"="C2","Feature 3"="C3","Feature 4"="C4",
                                                                   "Feature 5"="C5","Feature 6"="C6","Feature 7"="C7","Feature 8"="C8"))
                            ),
                            column(width=4,
                                   h3("Results"),
                                   h4("Score"),
                                   h5(textOutput("CustomScore")),
                                   h4("Count"),
                                   h5(textOutput("CustomRecorded")),
                                   h5(textOutput("CustomComplete")),
                                   h4("Errors"),
                                   h5(textOutput("CustomErrors")),
                                   h4("Features"),
                                   h5(textOutput("CustomFeatures"))
                            )
                            )
                   ),
                   tabPanel("Additional",
                            column(width=6,h3("Ordering and Siding"),
                                   #textOutput("O_S"),
                                   column(width=6,selectInput("CVOrder","Cervicle Vertebrae (3-7) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.CVOrder=='Partial'",textInput("CVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("TVOrder","Thorasic Vertebrae (1-12) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.TVOrder=='Partial'",textInput("TVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("LVOrder","Lumbar Vertebrae (1-5) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.LVOrder=='Partial'",textInput("LVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("ROrder","Ribs (3-10) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.ROrder=='Partial'",textInput("ROrder2","Describe partial ordering",value="NA")),
                                          selectInput("RSide","Ribs (1-12) siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.RSide=='Partial'",textInput("RSide2","Describe partial Siding",value="NA")),
                                          selectInput("MCOrder","Metacarpal ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.MCOrder=='Partial'",textInput("MCOrder2","Describe partial ordering",value="NA")),
                                          selectInput("MCSide","Metacarpal siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          h1(br()),
                                          h1(br())),
                                   column(width=6,conditionalPanel("input.MCSide=='Partial'",textInput("MCSide2","Describe partial Siding",value="NA")),
                                          selectInput("HPOrder","Hand phalanges ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.HPOrder=='Partial'",textInput("HPOrder2","Describe partial ordering",value="NA")),
                                          selectInput("HPSide","Hand halanges siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.HPSide=='Partial'",textInput("HPSide2","Describe partial Siding",value="NA")),
                                          selectInput("MTOrder","Metatarsal ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.MTOrder=='Partial'",textInput("MTOrder2","Describe partial ordering",value="NA")),
                                          selectInput("MTSide","Metatarsal siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.MTSide=='Partial'",textInput("MTSide2","Describe partial Siding",value="NA")),
                                          selectInput("FPOrder","Foot phalanges ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.FPOrder=='Partial'",textInput("FPOrder2","Describe partial ordering",value="NA")),
                                          selectInput("FPSide","Foot phalanges siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.FPSide=='Partial'",textInput("FPSide2","Describe partial Siding",value="NA")),
                                          h1(br()),
                                          h1(br()))
                            ),
                            column(width=6,h3("Photographic record"),
                                   h5("Please enter photographic reference number(s) or filepath(s)separate multiple entries with /"),
                                   column(width=6,textInput("Photo1","Full Skeleton",value="NA"),
                                          textInput("Photo2","Cranium Anterior",value='NA'),
                                          textInput("Photo3","Cranium Lateral",value='NA'),
                                          textInput("Photo4","Cranium Superior",value='NA'),
                                          textInput("Photo5","Cranium Basilar",value='NA'),
                                          textInput("Photo6","Skull Fragmented",value='NA'),
                                          textInput("Photo7","Mandible",value='NA'),
                                          textInput("Photo8","Hand",value='NA')),
                                   column(width=6,textInput("Photo9","Foot",value='NA'),
                                          textInput("Photo10","Arm",value='NA'),
                                          textInput("Photo11","Leg",value='NA'),
                                          textInput("Photo12","Pelvis",value='NA'),
                                          textInput("Photo13","Shoulder",value='NA'),
                                          textInput("Photo14","Thorax",value='NA'),
                                          textInput("Photo15","Vertebrae",value='NA'),
                                          textInput("Photo16","Unidentified Fragments",value='NA')))),
                   tabPanel("write",
                            textInput("dir","Data Folder",value="../../data/"),
                            column(width=4,
                                   h3("Population Info"),
                                   textInput("POPID","Population ID",value="NA"),
                                   textInput("POPName","Population name",value="NA"),
                                   textInput("Person1","Investigator",value="NA"),
                                   actionButton("Create","Create new file"),
                                   h4(textOutput("PMessage"))
                            ),
                            column(width=4,
                                   h3("Individual Info"),
                                   textInput("ID","Individual ID",value="NA"),
                                   textInput("Person2","Investigator intials",value="NA"),
                                   actionButton("Append","Add individual"),
                                   h4(textOutput("IMessage"))
                            ),
                            column(width=4,
                                   h3("Compatability check"),
                                   actionButton("Compat","Check file"),
                                   h4(textOutput("ComMessage"))
                            )
                   )
)
)