source("Functions.R",local=TRUE)
shinyServer(function(input,output){
  #Help
  output$chelp<-renderText({as.character(HelpMetrics(input$cHelp,skip=0,nrows=30))})
  output$mhelp<-renderText({as.character(HelpMetrics(input$mHelp,skip=31,nrows=10))})
  output$shelp<-renderText({as.character(HelpMetrics(input$sHelp,skip=42,nrows=11))})
  output$phelp<-renderText({as.character(HelpMetrics(input$pHelp,skip=54,nrows=19))})
  output$ahelp<-renderText({as.character(HelpMetrics(input$aHelp,skip=74,nrows=22))})
  output$lhelp<-renderText({as.character(HelpMetrics(input$lHelp,skip=97,nrows=34))})
  output$ohelp<-renderText({as.character(HelpMetrics(input$oHelp,skip=132,nrows=14))})
  output$vhelp<-renderText({as.character(HelpMetrics(input$vHelp,skip=132,nrows=14))})
  output$athelp<-renderText({as.character(HelpMetrics(input$atHelp,skip=132,nrows=14))})
  output$fhelp<-renderText({as.character(HelpMetrics(input$fHelp,skip=74,nrows=56))})
  
  #collation of data into fields
  output$Cr<-renderText({Cr()})
  Cr<-reactive({c(paste(input$C_g_op,input$C_eu_eu,input$C_zy_zy,input$C_ba_b,input$C_ba_n,input$C_ba_pr,input$C_ecm_ecm,input$C_pr_alv,input$C_au_au,input$C_n_pr,input$C_ft_ft,input$C_fmt_fmt,input$C_n_ns,input$C_al_al,paste(input$C_d_ec_r,input$C_d_ec_l,sep="/"),paste(input$C_OH_r,input$C_OH_l,sep="/"),input$C_ec_ec,input$C_d_d,
                        input$C_n_b,input$C_b_l,input$C_l_o,input$C_ba_o,paste(input$C_ML_r,input$C_ML_l,sep="/"),input$C_po_b,input$C_mfb,input$C_mob,input$C_acb,input$C_nmfs,input$C_nzos,input$C_nas,sep=":"),
                  paste(input$C_g_op2,input$C_eu_eu2,input$C_zy_zy2,input$C_ba_b2,input$C_ba_n2,input$C_ba_pr2,input$C_ecm_ecm2,input$C_pr_alv2,input$C_au_au2,input$C_n_pr2,input$C_ft_ft2,input$C_fmt_fmt2,input$C_n_ns2,input$C_al_al2,paste(input$C_d_ec_r2,input$C_d_ec_l2,sep="/"),paste(input$C_OH_r2,input$C_OH_l2,sep="/"),input$C_ec_ec2,input$C_d_d2,
                        input$C_n_b2,input$C_b_l2,input$C_l_o2,input$C_ba_o2,paste(input$C_ML_r2,input$C_ML_l2,sep="/"),input$C_po_b2,input$C_mfb2,input$C_mob2,input$C_acb2,input$C_nmfs2,input$C_nzos2,input$C_nas2,sep=":"),
                  paste(input$C_g_op3,input$C_eu_eu3,input$C_zy_zy3,input$C_ba_b3,input$C_ba_n3,input$C_ba_pr3,input$C_ecm_ecm3,input$C_pr_alv3,input$C_au_au3,input$C_n_pr3,input$C_ft_ft3,input$C_fmt_fmt3,input$C_n_ns3,input$C_al_al3,paste(input$C_d_ec_r3,input$C_d_ec_l3,sep="/"),paste(input$C_OH_r3,input$C_OH_l3,sep="/"),input$C_ec_ec3,input$C_d_d3,
                        input$C_n_b3,input$C_b_l3,input$C_l_o3,input$C_ba_o3,paste(input$C_ML_r3,input$C_ML_l3,sep="/"),input$C_po_b3,input$C_mfb3,input$C_mob3,input$C_acb3,input$C_nmfs3,input$C_nzos3,input$C_nas3,sep=":"))})
  
  M<-reactive({c(paste(input$M_id_gn,input$M_mbh,input$M_mbb,input$M_go_go,input$M_cdl_cdl,paste(input$M_minrb_r,input$M_minrb_l,sep="/"),paste(input$M_maxrb_r,input$M_maxrb_l,sep="/"),paste(input$M_maxrh_r,input$M_maxrh_l,sep="/"),input$M_ml,input$M_MA,sep=":"),
                 paste(input$M_id_gn2,input$M_mbh2,input$M_mbb2,input$M_go_go2,input$M_cdl_cdl2,paste(input$M_minrb_r2,input$M_minrb_l2,sep="/"),paste(input$M_maxrb_r2,input$M_maxrb_l2,sep="/"),paste(input$M_maxrh_r2,input$M_maxrh_l2,sep="/"),input$M_ml2,input$M_MA2,sep=":"),
                 paste(input$M_id_gn3,input$M_mbh3,input$M_mbb3,input$M_go_go3,input$M_cdl_cdl3,paste(input$M_minrb_r3,input$M_minrb_l3,sep="/"),paste(input$M_maxrb_r3,input$M_maxrb_l3,sep="/"),paste(input$M_maxrh_r3,input$M_maxrh_l3,sep="/"),input$M_ml3,input$M_MA3,sep=":"))})
  
  Sh<-reactive({c(paste(paste(input$Sh_cl_r,input$Sh_cl_l,sep="/"),paste(input$Sh_csd_r,input$Sh_csd_l,sep="/"),paste(input$Sh_cvd_r,input$Sh_cvd_l,sep="/"),paste(input$Sh_sh_r,input$Sh_sh_l,sep="/"),paste(input$Sh_sb_r,input$Sh_sb_l,sep="/"),paste(input$Sh_gh_r,input$Sh_gh_l,sep="/"),paste(input$Sh_gb_r,input$Sh_gb_l,sep="/"),paste(input$Sh_ssl_r,input$Sh_ssl_l,sep="/"),paste(input$Sh_ssw_r,input$Sh_ssw_l,sep="/"),paste(input$Sh_al_r,input$Sh_al_l,sep="/"),paste(input$Sh_cpl_r,input$Sh_cpl_l,sep="/"),sep=":"),
                  paste(paste(input$Sh_cl_r2,input$Sh_cl_l2,sep="/"),paste(input$Sh_csd_r2,input$Sh_csd_l2,sep="/"),paste(input$Sh_cvd_r2,input$Sh_cvd_l2,sep="/"),paste(input$Sh_sh_r2,input$Sh_sh_l2,sep="/"),paste(input$Sh_sb_r2,input$Sh_sb_l2,sep="/"),paste(input$Sh_gh_r2,input$Sh_gh_l2,sep="/"),paste(input$Sh_gb_r2,input$Sh_gb_l2,sep="/"),paste(input$Sh_ssl_r2,input$Sh_ssl_l2,sep="/"),paste(input$Sh_ssw_r2,input$Sh_ssw_l2,sep="/"),paste(input$Sh_al_r2,input$Sh_al_l2,sep="/"),paste(input$Sh_cpl_r2,input$Sh_cpl_l2,sep="/"),sep=":"),
                  paste(paste(input$Sh_cl_r3,input$Sh_cl_l3,sep="/"),paste(input$Sh_csd_r3,input$Sh_csd_l3,sep="/"),paste(input$Sh_cvd_r3,input$Sh_cvd_l3,sep="/"),paste(input$Sh_sh_r3,input$Sh_sh_l3,sep="/"),paste(input$Sh_sb_r3,input$Sh_sb_l3,sep="/"),paste(input$Sh_gh_r3,input$Sh_gh_l3,sep="/"),paste(input$Sh_gb_r3,input$Sh_gb_l3,sep="/"),paste(input$Sh_ssl_r3,input$Sh_ssl_l3,sep="/"),paste(input$Sh_ssw_r3,input$Sh_ssw_l3,sep="/"),paste(input$Sh_al_r3,input$Sh_al_l3,sep="/"),paste(input$Sh_cpl_r3,input$Sh_cpl_l3,sep="/"),sep=":"))})
  
  P<-reactive({c(paste(paste(input$P_och_r,input$P_och_l,sep="/"),paste(input$P_ib_r,input$P_ib_l,sep="/"),paste(input$P_pl_r,input$P_pl_l,sep="/"),paste(input$P_pl2_r,input$P_pl2_l,sep="/"),paste(input$P_pl3_r,input$P_pl3_l,sep="/"),paste(input$P_il_r,input$P_il_l,sep="/"),paste(input$P_il2_r,input$P_il2_l,sep="/"),paste(input$P_il3_r,input$P_il3_l,sep="/"),paste(input$P_psh_r,input$P_psh_l,sep="/"),paste(input$P_midpw_r,input$P_midpw_l,sep="/"),
                     paste(input$P_minpw_r,input$P_minpw_l,sep="/"),paste(input$P_iprw_r,input$P_iprw_l,sep="/"),paste(input$P_pa_r,input$P_pa_l,sep="/"),paste(input$P_snw_r,input$P_snw_l,sep="/"),paste(input$P_snd_r,input$P_snd_l,sep="/"),paste(input$P_ad_r,input$P_ad_l,sep="/"),input$P_sl,input$P_sb,input$P_s1b,sep=":"),
                paste(paste(input$P_och_r2,input$P_och_l2,sep="/"),paste(input$P_ib_r2,input$P_ib_l2,sep="/"),paste(input$P_pl_r2,input$P_pl_l2,sep="/"),paste(input$P_pl2_r2,input$P_pl2_l2,sep="/"),paste(input$P_pl3_r2,input$P_pl3_l2,sep="/"),paste(input$P_il_r2,input$P_il_l2,sep="/"),paste(input$P_il2_r2,input$P_il2_l2,sep="/"),paste(input$P_il3_r2,input$P_il3_l2,sep="/"),paste(input$P_psh_r2,input$P_psh_l2,sep="/"),paste(input$P_midpw_r2,input$P_midpw_l2,sep="/"),
                      paste(input$P_minpw_r2,input$P_minpw_l2,sep="/"),paste(input$P_iprw_r2,input$P_iprw_l2,sep="/"),paste(input$P_pa_r2,input$P_pa_l2,sep="/"),paste(input$P_snw_r2,input$P_snw_l2,sep="/"),paste(input$P_snd_r2,input$P_snd_l2,sep="/"),paste(input$P_ad_r2,input$P_ad_l2,sep="/"),input$P_sl2,input$P_sb2,input$P_s1b2,sep=":"),
                paste(paste(input$P_och_r3,input$P_och_l3,sep="/"),paste(input$P_ib_r3,input$P_ib_l3,sep="/"),paste(input$P_pl_r3,input$P_pl_l3,sep="/"),paste(input$P_pl2_r3,input$P_pl2_l3,sep="/"),paste(input$P_pl3_r3,input$P_pl3_l3,sep="/"),paste(input$P_il_r3,input$P_il_l3,sep="/"),paste(input$P_il2_r3,input$P_il2_l3,sep="/"),paste(input$P_il3_r3,input$P_il3_l3,sep="/"),paste(input$P_psh_r3,input$P_psh_l3,sep="/"),paste(input$P_midpw_r3,input$P_midpw_l3,sep="/"),
                      paste(input$P_minpw_r3,input$P_minpw_l3,sep="/"),paste(input$P_iprw_r3,input$P_iprw_l3,sep="/"),paste(input$P_pa_r3,input$P_pa_l3,sep="/"),paste(input$P_snw_r3,input$P_snw_l3,sep="/"),paste(input$P_snd_r3,input$P_snd_l3,sep="/"),paste(input$P_ad_r3,input$P_ad_l3,sep="/"),input$P_sl3,input$P_sb3,input$P_s1b3,sep=":"))})
  
  UL<-reactive({c(paste(paste(input$UL_mhl_r,input$UL_mhl_l,sep="/"),paste(input$UL_heb_r,input$UL_heb_l,sep="/"),paste(input$UL_vhhd_r,input$UL_vhhd_l,sep="/"),paste(input$UL_mxhd_r,input$UL_mxhd_l,sep="/"),paste(input$UL_minhd_r,input$UL_minhd_l,sep="/"),paste(input$UL_mrl_r,input$UL_mrl_l,sep="/"),paste(input$UL_srd_r,input$UL_srd_l,sep="/"),
                      paste(input$UL_trd_r,input$UL_trd_l,sep="/"),paste(input$UL_rhd_r,input$UL_rhd_l,sep="/"),paste(input$UL_mul_r,input$UL_mul_l,sep="/"),paste(input$UL_pul_r,input$UL_pul_l,sep="/"),paste(input$UL_sud_r,input$UL_sud_l,sep="/"),paste(input$UL_tud_r,input$UL_tud_l,sep="/"),paste(input$UL_muc_r,input$UL_muc_l,sep="/"),sep=":"),
                 paste(paste(input$UL_mhl_r2,input$UL_mhl_l2,sep="/"),paste(input$UL_heb_r2,input$UL_heb_l2,sep="/"),paste(input$UL_vhhd_r2,input$UL_vhhd_l2,sep="/"),paste(input$UL_mxhd_r2,input$UL_mxhd_l2,sep="/"),paste(input$UL_minhd_r2,input$UL_minhd_l2,sep="/"),paste(input$UL_mrl_r2,input$UL_mrl_l2,sep="/"),paste(input$UL_srd_r2,input$UL_srd_l2,sep="/"),
                       paste(input$UL_trd_r2,input$UL_trd_l2,sep="/"),paste(input$UL_rhd_r2,input$UL_rhd_l2,sep="/"),paste(input$UL_mul_r2,input$UL_mul_l2,sep="/"),paste(input$UL_pul_r2,input$UL_pul_l2,sep="/"),paste(input$UL_sud_r2,input$UL_sud_l2,sep="/"),paste(input$UL_tud_r2,input$UL_tud_l2,sep="/"),paste(input$UL_muc_r2,input$UL_muc_l2,sep="/"),sep=":"),
                 paste(paste(input$UL_mhl_r3,input$UL_mhl_l3,sep="/"),paste(input$UL_heb_r3,input$UL_heb_l3,sep="/"),paste(input$UL_vhhd_r3,input$UL_vhhd_l3,sep="/"),paste(input$UL_mxhd_r3,input$UL_mxhd_l3,sep="/"),paste(input$UL_minhd_r3,input$UL_minhd_l3,sep="/"),paste(input$UL_mrl_r3,input$UL_mrl_l3,sep="/"),paste(input$UL_srd_r3,input$UL_srd_l3,sep="/"),
                       paste(input$UL_trd_r3,input$UL_trd_l3,sep="/"),paste(input$UL_rhd_r3,input$UL_rhd_l3,sep="/"),paste(input$UL_mul_r3,input$UL_mul_l3,sep="/"),paste(input$UL_pul_r3,input$UL_pul_l3,sep="/"),paste(input$UL_sud_r3,input$UL_sud_l3,sep="/"),paste(input$UL_tud_r3,input$UL_tud_l3,sep="/"),paste(input$UL_muc_r3,input$UL_muc_l3,sep="/"),sep=":"))})
  
  LL<-reactive({c(paste(paste(input$LL_mfl_r,input$LL_mfl_l,sep="/"),paste(input$LL_bfl_r,input$LL_bfl_l,sep="/"),paste(input$LL_efb_r,input$LL_efb_l,sep="/"),paste(input$LL_mfhd_r,input$LL_mfhd_l,sep="/"),paste(input$LL_sfsd_r,input$LL_sfsd_l,sep="/"),paste(input$LL_tfsd_r,input$LL_tfsd_l,sep="/"),paste(input$LL_sfmd_r,input$LL_sfmd_l,sep="/"),paste(input$LL_tfmd_r,input$LL_tfmd_l,sep="/"),
                      paste(input$LL_mfc_r,input$LL_mfc_l,sep="/"),paste(input$LL_lfcd_r,input$LL_lfcd_l,sep="/"),paste(input$LL_mfcd_r,input$LL_mfcd_l,sep="/"),paste(input$LL_lfcw_r,input$LL_lfcw_l,sep="/"),paste(input$LL_mfcw_r,input$LL_mfcw_l,sep="/"),paste(input$LL_icw_r,input$LL_icw_l,sep="/"),paste(input$LL_icd_r,input$LL_icd_l,sep="/"),paste(input$LL_stl_r,input$LL_stl_l,sep="/"),
                      paste(input$LL_mtl_r,input$LL_mtl_l,sep="/"),paste(input$LL_ptl_r,input$LL_ptl_l,sep="/"),paste(input$LL_mptb_r,input$LL_mptb_l,sep="/"),paste(input$LL_mdtb_r,input$LL_mdtb_l,sep="/"),paste(input$LL_std_r,input$LL_std_l,sep="/"),paste(input$LL_ttd_r,input$LL_ttd_l,sep="/"),paste(input$LL_tc_r,input$LL_tc_l,sep="/"),paste(input$LL_mfbl_r,input$LL_mfbl_l,sep="/"),paste(input$LL_mfbd_r,input$LL_mfbd_l,sep="/"),sep=":"),
                 paste(paste(input$LL_mfl_r2,input$LL_mfl_l2,sep="/"),paste(input$LL_bfl_r2,input$LL_bfl_l2,sep="/"),paste(input$LL_efb_r2,input$LL_efb_l2,sep="/"),paste(input$LL_mfhd_r2,input$LL_mfhd_l2,sep="/"),paste(input$LL_sfsd_r2,input$LL_sfsd_l2,sep="/"),paste(input$LL_tfsd_r2,input$LL_tfsd_l2,sep="/"),paste(input$LL_sfmd_r2,input$LL_sfmd_l2,sep="/"),paste(input$LL_tfmd_r2,input$LL_tfmd_l2,sep="/"),
                       paste(input$LL_mfc_r2,input$LL_mfc_l2,sep="/"),paste(input$LL_lfcd_r2,input$LL_lfcd_l2,sep="/"),paste(input$LL_mfcd_r2,input$LL_mfcd_l2,sep="/"),paste(input$LL_lfcw_r2,input$LL_lfcw_l2,sep="/"),paste(input$LL_mfcw_r2,input$LL_mfcw_l2,sep="/"),paste(input$LL_icw_r2,input$LL_icw_l2,sep="/"),paste(input$LL_icd_r2,input$LL_icd_l2,sep="/"),paste(input$LL_stl_r2,input$LL_stl_l2,sep="/"),
                       paste(input$LL_mtl_r2,input$LL_mtl_l2,sep="/"),paste(input$LL_ptl_r2,input$LL_ptl_l2,sep="/"),paste(input$LL_mptb_r2,input$LL_mptb_l2,sep="/"),paste(input$LL_mdtb_r2,input$LL_mdtb_l2,sep="/"),paste(input$LL_std_r2,input$LL_std_l2,sep="/"),paste(input$LL_ttd_r2,input$LL_ttd_l2,sep="/"),paste(input$LL_tc_r2,input$LL_tc_l2,sep="/"),paste(input$LL_mfbl_r2,input$LL_mfbl_l2,sep="/"),paste(input$LL_mfbd_r2,input$LL_mfbd_l2,sep="/"),sep=":"),
                 paste(paste(input$LL_mfl_r3,input$LL_mfl_l3,sep="/"),paste(input$LL_bfl_r3,input$LL_bfl_l3,sep="/"),paste(input$LL_efb_r3,input$LL_efb_l3,sep="/"),paste(input$LL_mfhd_r3,input$LL_mfhd_l3,sep="/"),paste(input$LL_sfsd_r3,input$LL_sfsd_l3,sep="/"),paste(input$LL_tfsd_r3,input$LL_tfsd_l3,sep="/"),paste(input$LL_sfmd_r3,input$LL_sfmd_l3,sep="/"),paste(input$LL_tfmd_r3,input$LL_tfmd_l3,sep="/"),
                       paste(input$LL_mfc_r3,input$LL_mfc_l3,sep="/"),paste(input$LL_lfcd_r3,input$LL_lfcd_l3,sep="/"),paste(input$LL_mfcd_r3,input$LL_mfcd_l3,sep="/"),paste(input$LL_lfcw_r3,input$LL_lfcw_l3,sep="/"),paste(input$LL_mfcw_r3,input$LL_mfcw_l3,sep="/"),paste(input$LL_icw_r3,input$LL_icw_l3,sep="/"),paste(input$LL_icd_r3,input$LL_icd_l3,sep="/"),paste(input$LL_stl_r3,input$LL_stl_l3,sep="/"),
                       paste(input$LL_mtl_r3,input$LL_mtl_l3,sep="/"),paste(input$LL_ptl_r3,input$LL_ptl_l3,sep="/"),paste(input$LL_mptb_r3,input$LL_mptb_l3,sep="/"),paste(input$LL_mdtb_r3,input$LL_mdtb_l3,sep="/"),paste(input$LL_std_r3,input$LL_std_l3,sep="/"),paste(input$LL_ttd_r3,input$LL_ttd_l3,sep="/"),paste(input$LL_tc_r3,input$LL_tc_l3,sep="/"),paste(input$LL_mfbl_r3,input$LL_mfbl_l3,sep="/"),paste(input$LL_mfbd_r3,input$LL_mfbd_l3,sep="/"),sep=":"))})
  
  FLB<-reactive({c(paste(paste(input$FLB_fhhl_r,input$FLB_fhhl_l,sep="/"),paste(input$FLB_fhsl_r,input$FLB_fhsl_l,sep="/"),paste(input$FLB_fhol_r,input$FLB_fhol_l,sep="/"),paste(input$FLB_fhtl_r,input$FLB_fhtl_l,sep="/"),paste(input$FLB_frhl_r,input$FLB_frhl_l,sep="/"),paste(input$FLB_frpl_r,input$FLB_frpl_l,sep="/"),paste(input$FLB_frsl_r,input$FLB_frsl_l,sep="/"),paste(input$FLB_frdl_r,input$FLB_frdl_l,sep="/"),
                         paste(input$FLB_ffpl_r,input$FLB_ffpl_l,sep="/"),paste(input$FLB_ffsl_r,input$FLB_ffsl_l,sep="/"),paste(input$FLB_ffscl_r,input$FLB_ffscl_l,sep="/"),paste(input$FLB_ffdl_r,input$FLB_ffdl_l,sep="/"),paste(input$FLB_ftpl_r,input$FLB_ftpl_l,sep="/"),paste(input$FLB_fttl_r,input$FLB_fttl_l,sep="/"),paste(input$FLB_ftsl_r,input$FLB_ftsl_l,sep="/"),paste(input$FLB_ftdl_r,input$FLB_ftdl_l,sep="/"),paste(input$FLB_ftml_r,input$FLB_ftml_l,sep="/"),sep=":"),
                   paste(paste(input$FLB_fhhl_r2,input$FLB_fhhl_l2,sep="/"),paste(input$FLB_fhsl_r2,input$FLB_fhsl_l2,sep="/"),paste(input$FLB_fhol_r2,input$FLB_fhol_l2,sep="/"),paste(input$FLB_fhtl_r2,input$FLB_fhtl_l2,sep="/"),paste(input$FLB_frhl_r2,input$FLB_frhl_l2,sep="/"),paste(input$FLB_frpl_r2,input$FLB_frpl_l2,sep="/"),paste(input$FLB_frsl_r2,input$FLB_frsl_l2,sep="/"),paste(input$FLB_frdl_r2,input$FLB_frdl_l2,sep="/"),
                         paste(input$FLB_ffpl_r2,input$FLB_ffpl_l2,sep="/"),paste(input$FLB_ffsl_r2,input$FLB_ffsl_l2,sep="/"),paste(input$FLB_ffscl_r2,input$FLB_ffscl_l2,sep="/"),paste(input$FLB_ffdl_r2,input$FLB_ffdl_l2,sep="/"),paste(input$FLB_ftpl_r2,input$FLB_ftpl_l2,sep="/"),paste(input$FLB_fttl_r2,input$FLB_fttl_l2,sep="/"),paste(input$FLB_ftsl_r2,input$FLB_ftsl_l2,sep="/"),paste(input$FLB_ftdl_r2,input$FLB_ftdl_l2,sep="/"),paste(input$FLB_ftml_r2,input$FLB_ftml_l2,sep="/"),sep=":"),
                   paste(paste(input$FLB_fhhl_r3,input$FLB_fhhl_l3,sep="/"),paste(input$FLB_fhsl_r3,input$FLB_fhsl_l3,sep="/"),paste(input$FLB_fhol_r3,input$FLB_fhol_l3,sep="/"),paste(input$FLB_fhtl_r3,input$FLB_fhtl_l3,sep="/"),paste(input$FLB_frhl_r3,input$FLB_frhl_l3,sep="/"),paste(input$FLB_frpl_r3,input$FLB_frpl_l3,sep="/"),paste(input$FLB_frsl_r3,input$FLB_frsl_l3,sep="/"),paste(input$FLB_frdl_r3,input$FLB_frdl_l3,sep="/"),
                         paste(input$FLB_ffpl_r3,input$FLB_ffpl_l3,sep="/"),paste(input$FLB_ffsl_r3,input$FLB_ffsl_l3,sep="/"),paste(input$FLB_ffscl_r3,input$FLB_ffscl_l3,sep="/"),paste(input$FLB_ffdl_r3,input$FLB_ffdl_l3,sep="/"),paste(input$FLB_ftpl_r3,input$FLB_ftpl_l3,sep="/"),paste(input$FLB_fttl_r3,input$FLB_fttl_l3,sep="/"),paste(input$FLB_ftsl_r3,input$FLB_ftsl_l3,sep="/"),paste(input$FLB_ftdl_r3,input$FLB_ftdl_l3,sep="/"),paste(input$FLB_ftml_r3,input$FLB_ftml_l3,sep="/"),sep=":"))})
  
  A<-reactive({c(paste(paste(input$A_ah_r,input$A_ah_l,sep="/"),input$A_bid,input$A_cv,input$A_tpd,input$A_n_gn,sep=":"),
                 paste(paste(input$A_ah_r2,input$A_ah_l2,sep="/"),input$A_bid2,input$A_cv2,input$A_tpd2,input$A_n_gn2,sep=":"),
                 paste(paste(input$A_ah_r3,input$A_ah_l3,sep="/"),input$A_bid3,input$A_cv3,input$A_tpd3,input$A_n_gn3,sep=":"))})
  
  V<-reactive({c(paste(input$V_c1,input$V_c2,input$V_c3,input$V_c4,input$V_c5,input$V_c6,input$V_c7,input$V_T1,input$V_T2,input$V_T3,input$V_T4,input$V_T5,input$V_T6,input$V_T7,input$V_T8,input$V_T9,input$V_T10,input$V_T11,input$V_T12,input$V_L1,input$V_L2,input$V_L3,input$V_L4,input$V_L5,sep=":"),
                paste(input$V_c12,input$V_c22,input$V_c32,input$V_c42,input$V_c52,input$V_c62,input$V_c72,input$V_T1_2,input$V_T22,input$V_T32,input$V_T42,input$V_T52,input$V_T62,input$V_T72,input$V_T82,input$V_T92,input$V_T102,input$V_T112,input$V_T122,input$V_L12,input$V_L22,input$V_L32,input$V_L42,input$V_L52,sep=":"),
                paste(input$V_c13,input$V_c23,input$V_c33,input$V_c43,input$V_c53,input$V_c63,input$V_c73,input$V_T13,input$V_T23,input$V_T33,input$V_T43,input$V_T53,input$V_T63,input$V_T73,input$V_T83,input$V_T93,input$V_T103,input$V_T113,input$V_T123,input$V_L13,input$V_L23,input$V_L33,input$V_L43,input$V_L53,sep=":"))})
  
  MT<-reactive({c(paste(paste(input$MT_m1_r,input$MT_m1_l,sep="/"),paste(input$MT_m2_r,input$MT_m2_l,sep="/"),paste(input$MT_m3_r,input$MT_m3_l,sep="/"),paste(input$MT_m4_r,input$MT_m4_l,sep="/"),paste(input$MT_m5_r,input$MT_m5_l,sep="/"),sep=":"),
                 paste(paste(input$MT_m1_r2,input$MT_m1_l2,sep="/"),paste(input$MT_m2_r2,input$MT_m2_l2,sep="/"),paste(input$MT_m3_r2,input$MT_m3_l2,sep="/"),paste(input$MT_m4_r2,input$MT_m4_l2,sep="/"),paste(input$MT_m5_r2,input$MT_m5_l2,sep="/"),sep=":"),
                 paste(paste(input$MT_m1_r3,input$MT_m1_l3,sep="/"),paste(input$MT_m2_r3,input$MT_m2_l3,sep="/"),paste(input$MT_m3_r3,input$MT_m3_l3,sep="/"),paste(input$MT_m4_r3,input$MT_m4_l3,sep="/"),paste(input$MT_m5_r3,input$MT_m5_l3,sep="/"),sep=":"))})
  
  O<-reactive({c(paste(paste(input$O_mcl_r,input$O_mcl_l,sep="/"),paste(input$O_cb_r,input$O_cb_l,sep="/"),paste(input$O_mtl_r,input$O_mtl_l,sep="/"),input$O_manl,input$O_msl,input$O_s1w,input$O_s3w,sep=":"),
                paste(paste(input$O_mcl_r2,input$O_mcl_l2,sep="/"),paste(input$O_cb_r2,input$O_cb_l2,sep="/"),paste(input$O_mtl_r2,input$O_mtl_l2,sep="/"),input$O_manl2,input$O_msl2,input$O_s1w2,input$O_s3w2,sep=":"),
                paste(paste(input$O_mcl_r3,input$O_mcl_l3,sep="/"),paste(input$O_cb_r3,input$O_cb_l3,sep="/"),paste(input$O_mtl_r3,input$O_mtl_l3,sep="/"),input$O_manl3,input$O_msl3,input$O_s1w3,input$O_s3w3,sep=":"))})
  
  equip<-reactive({na.omit(c(input$Equipment,input$equipment2))})
  
  #create file
  PMessage<-eventReactive(input$Create,{
    CreateMetric(input$POPID,input$POPName,input$Person1,input$dir,equip())
  })
  output$PMessage<-renderPrint({PMessage()})
  
  #Compatability Check
  ComMessage<-eventReactive(input$Compat,{
    CompCheck(input$POPID,input$POPName,input$Person1,input$dir,equip())
  })
  output$ComMessage<-renderPrint({ComMessage()})
  
  #add individual
  IMessage<-eventReactive(input$Append,{
    AppendMetric(input$POPID,input$ID,input$Person2,input$dir,C=Cr(),M=M(),Sh=Sh(),P=P(),UL=UL(),LL=LL(),FLB=FLB(),A=A(),V=V(),MT=MT(),O=O())
  })
  output$IMessage<-renderPrint({IMessage()})
})