library(shiny);library(markdown)

shinyUI(navbarPage("TotalMetrics",
                   tabPanel("Cranial",
                            selectInput("cHelp","Help",c("Maximum Cranial Length"="g_op","Maximum Cranial Breadth"="eu_eu","Bizygomatic Diameter"="zy_zy","Basion-Bregma Height"="ba_b","Cranial Base Length"="ba_n",
                                                        "Basion-Prosthion Length"="ba_pr","Maxillo-Alveolar Breadth"="ecm_ecm","Maxillo-Alveolar Length"="pr_alv","Biauricular Breadth"="au_au","Upper facial Height"="n_pr",
                                                        "Minimum Frontal Breadth"="ft_ft","Upper Facial breadth"="fmt_fmt","Nasal Height"="n_ns","Nasal Breadth"="al_al","Orbital Breadth"="d_ec","Orbital Height"="OH","Biorbital Breadth"="ec_ec",
                                                        "Interorbital Breadth"="d_d","Frontal Cord"="n_b","Parietal Cord"="b_l","Occipital Cord"="l_o","Formen magnum length"="ba_o","Mastoid Length"="ML","Porion bregma height"="po_b",
                                                        "Maxillofrontal breadth"="mfb","Midorbital breadth"="mob","Alpha cord breadth"="acb","Nasomaxillofrontal subtense"="nmfs","Nasozygoorbital subtense"="nzos","Nasoalpha subtense"="nas")),
                            h4(textOutput("chelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=3,
                                   numericInput("C_g_op","Maximum Cranial Length",value=NA),
                                   numericInput("C_eu_eu","Maximum Cranial Breadth",value=NA),
                                   numericInput("C_zy_zy","Bizygomatic Diameter",value=NA),
                                   numericInput("C_ba_b","Basion-Bregma Height",value=NA),
                                   numericInput("C_ba_n","Cranial Base Length",value=NA),
                                   numericInput("C_ba_pr","Basion-Prosthion Length",value=NA),
                                   numericInput("C_ecm_ecm","Maxillo-Alveolar Breadth",value=NA),
                                   numericInput("C_pr_alv","Maxillo-Alveolar Length",value=NA),
                                   numericInput("C_au_au","Biauricular Breadth",value=NA)),
                            column(width=3,
                                   numericInput("C_n_pr","Upper facial Height",value=NA),
                                   numericInput("C_ft_ft","Minimum Frontal Breadth",value=NA),
                                   numericInput("C_fmt_fmt","Upper Facial breadth",value=NA),
                                   numericInput("C_n_ns","Nasal Height",value=NA),
                                   numericInput("C_al_al","Nasal Breadth",value=NA),
                                   numericInput("C_d_ec_r","Right Orbital Breadth",value=NA),
                                   numericInput("C_d_ec_l","Left Orbital Breadth",value=NA),
                                   numericInput("C_OH_r","Right Orbital Height",value=NA),
                                   numericInput("C_OH_l","Left Orbital Height",value=NA)),
                            column(width=3,
                                   numericInput("C_ec_ec","Biorbital Breadth",value=NA),
                                   numericInput("C_d_d","Interorbital Breadth",value=NA),
                                   numericInput("C_n_b","Frontal cord",value=NA),
                                   numericInput("C_b_l","Parietal cord",value=NA),
                                   numericInput("C_l_o","Occipital cord",value=NA),
                                   numericInput("C_ba_o","Formen magnum length",value=NA),
                                   numericInput("C_ML_r","Right mastoid Length",value=NA),
                                   numericInput("C_ML_l","Left mastoid Length",value=NA),
                                   numericInput("C_po_b","Porion bregma height",value=NA)),
                            column(width=3,
                                   numericInput("C_mfb","Maxillofrontal breadth",value=NA),
                                   numericInput("C_mob","Midorbital breadth",value=NA),
                                   numericInput("C_acb","Alpha cord breadth",value=NA),
                                   numericInput("C_nmfs","Nasomaxillofrontal subtense",value=NA),
                                   numericInput("C_nzos","Nasozygoorbital subtense",value=NA),
                                   numericInput("C_nas","Nasoalpha subtense",value=NA))
                            ),
                   tabPanel("Mandible",
                            selectInput("mHelp","Help",choices=c("Chin Height"="id_gn","Height of mandibular body"="mbh","Breadth of the mandibular body"="mbb",
                                                                 "Bigonial Width"="go_go","Bicondylar Breadth"="cdl_cdl","Minimum Ramus Breadth"="minrb","Maximum Ramus Breadth"="maxrb",
                                                                 "Maximum Ramus Height"="maxrh","Mandibular Length"="ML","Mandibular Angle"="MA")),
                            h4(textOutput("mhelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=4,
                                   numericInput("M_id_gn","Chin Height",value=NA),
                                   numericInput("M_mbh","Height of mandibular body",value=NA),
                                   numericInput("M_mbb","Breadth of mandibular body",value=NA),
                                   numericInput("M_go_go","Bigonial Width",value=NA),
                                   numericInput("M_cdl_cdl","Bicondylar Breadth",value=NA)),
                            column(width=4,
                                   numericInput("M_minrb_r","Minimum Right Ramus Breadth",value=NA),
                                   numericInput("M_minrb_l","Minimum Left Ramus Breadth",value=NA),
                                   numericInput("M_maxrb_r","Maximum Right Ramus Breadth",value=NA),
                                   numericInput("M_maxrb_l","Maximum Left Ramus Breadth",value=NA)),
                            column(width=4,
                                   numericInput("M_maxrh_r","Maximum right ramus height",value=NA),
                                   numericInput("M_maxrh_l","Maximum left ramus height(l)",value=NA),
                                   numericInput("M_ml","Mandibular Length",value=NA),
                                   numericInput("M_MA","Mandibular Angle",value=NA))
                            ),
                   tabPanel("Shoulder",
                            selectInput("sHelp","Help",choices=c("Clavicle Maximum Length"="cl","Clavicle sagittal diameter"="csd","Clavicle Verticle Diameter"="cvd",
                                                                 "Scapula Height"="sh","Scapula Breadth"="sb","Glenoid Height"="gh","Glenoid Breadth"="gb",
                                                                 "Scapular spine length"="ssl","Scapular spine width"="ssw","Acromion length"="al","Coracoid process length"="cpl")),
                            h4(textOutput("shelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=4,
                                   numericInput("Sh_cl_r","Right clavicle maximum length",value=NA),
                                   numericInput("Sh_cl_l","Left clavicle maximum length",value=NA),
                                   numericInput("Sh_csd_r","Right clavicle sagittal diameter",value=NA),
                                   numericInput("Sh_csd_l","Left clavicle sagittal diameter",value=NA),
                                   numericInput("Sh_cvd_r","Right clavicle verticle diameter",value=NA),
                                   numericInput("Sh_cvd_l","Left clavicle verticle diameter",value=NA)),
                            column(width=4,
                                   numericInput("Sh_sh_r","Right scapula height",value=NA),
                                   numericInput("Sh_sh_l","Left scapula height",value=NA),
                                   numericInput("Sh_sb_r","Right scapula breadth",value=NA),
                                   numericInput("Sh_sb_l","Left scapula breadth",value=NA),
                                   numericInput("Sh_gh_r","Right glenoid height",value=NA),
                                   numericInput("Sh_gh_l","Left glenoid height",value=NA),
                                   numericInput("Sh_gb_r","Right glenoid breadth",value=NA),
                                   numericInput("Sh_gb_l","Left glenoid breadth",value=NA)),
                            column(width=4,
                                   numericInput("Sh_ssl_r","Right scapular spine length",value=NA),
                                   numericInput("Sh_ssl_l","Left scapular spine length",value=NA),
                                   numericInput("Sh_ssw_r","Right scapular spine width",value=NA),
                                   numericInput("Sh_ssw_l","Left scapula spine width",value=NA),
                                   numericInput("Sh_al_r","Right acromion length",value=NA),
                                   numericInput("Sh_al_l","Left acromion length",value=NA),
                                   numericInput("Sh_cpl_r","Right coracoid process length",value=NA),
                                   numericInput("Sh_cpl_l","Left coracoid process length",value=NA))
                            ),
                   tabPanel("Pelvis",
                            selectInput("pHelp","Help",choices=c("Os coxa height"="och","Iliac breadth"="ib","Standard Pubic Length"="pl","Pubic length from the acetabular rim"="pl2","Pubic length from the iliac origin"="pl3",
                                                                 "Standard Ishial Length"="il","Ishial Length from the acetabular rim"="il2","Ishial Length from the iliac origin"="il3","Height of the pubic symphysis"="psh",
                                                                 "Mid pubic width"="midpw","Minimum pubic width"="minpw","Minimum width of the ishiopubic ramus"="iprw","Pubic angle"="pa","Width of the greater sciatic notch"="snw",
                                                                 "Maximum depth of the greater sciatic notch"="snd","Acetabular diameter"="ad","Anterior length of the sacrum"="sl","Anterior breadth of the sacrum"="sb","Maximum breadth of s1"="s1b")),
                            h4(textOutput("phelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=3,
                                   numericInput("P_och_r","Right os coxa height",value=NA),
                                   numericInput("P_och_l","Left os coxa height",value=NA),
                                   numericInput("P_ib_r","Right iliac breadth",value=NA),
                                   numericInput("P_ib_l","Left iliac breadth",value=NA),
                                   numericInput("P_pl_r","Right Standard Pubic Length",value=NA),
                                   numericInput("P_pl_l","Left Standard Pubic Length",value=NA),
                                   numericInput("P_pl2_r","Right Pubic length from the acetabular rim",value=NA),
                                   numericInput("P_pl2_l","Left Pubic length from the acetabular rim",value=NA),
                                   numericInput("P_pl3_r","Right Pubic Length from the iliac origin",value=NA),
                                   numericInput("P_pl3_l","Left Pubic Length from the iliac origin",value=NA)),
                            column(width=3,
                                   numericInput("P_il_r","Right Standard ishial Length",value=NA),
                                   numericInput("P_il_l","Left Standard ishial Length",value=NA),
                                   numericInput("P_il2_r","Right ishial length from the acetabular rim",value=NA),
                                   numericInput("P_il2_l","Left ishial length from the acetabular rim",value=NA),
                                   numericInput("P_il3_r","Right ishial Length from the iliac origin",value=NA),
                                   numericInput("P_il3_l","Left ishial Length from the iliac origin",value=NA),
                                   numericInput("P_psh_r","Right pubic symphysis height",value=NA),
                                   numericInput("P_psh_l","Left pubic symphysis height",value=NA),
                                   numericInput("P_midpw_r","Right mid pubic width",value=NA),
                                   numericInput("P_midpw_l","Left mid pubic width",value=NA)),
                            column(width=3,
                                   numericInput("P_minpw_r","Right minimum pubic width",value=NA),
                                   numericInput("P_minpw_l","Left minimum pubic width",value=NA),
                                   numericInput("P_iprw_r","Minimum width of the right ishiopubic ramus",value=NA),
                                   numericInput("P_iprw_l","Minimum width of the left ishiopubic ramus",value=NA),
                                   numericInput("P_pa_r","Right pubic angle",value=NA),
                                   numericInput("P_pa_l","Left pubic angle",value=NA),
                                   numericInput("P_snw_r","Width of the right greater sciatic notch",value=NA),
                                   numericInput("P_snw_l","Width of the left greater sciatic notch",value=NA),
                                   numericInput("P_snd_r","Maximum depth of the right greater sciatic notch",value=NA),
                                   numericInput("P_snd_l","Maximum depth of the left greater sciatic notch",value=NA)),
                            column(width=3,
                                   numericInput("P_ad_r","Right Acetabular diameter",value=NA),
                                   numericInput("P_ad_l","Left Acetabular diameter",value=NA),
                                   numericInput("P_sl","Anterior length of the sacrum",value=NA),
                                   numericInput("P_sb","Anterior breadth of the sacrum",value=NA),
                                   numericInput("P_s1b","Maximum breadth of s1",value=NA))
                            ),
                   tabPanel("Upper Limb",
                            selectInput("aHelp","Help",choices=c("Maximum humeral length"="mhl","Humerus epicondylar breadth"="heb","Vertical humeral head diameter"="vhhd","Maximum humeral diameter"="mxhd",
                                                                 "Minimum humeral diameter"="minhd","Maximum radial length"="mrl","Sagittal radial diameter"="srd","Transverse radial diamter"="trd","Radial head diameter"="rhd",
                                                                 "Maximum ulna length"="mul","Physiological ulna length"="pul","Sagittal ulna diameter"="sud","Transverse ulna diameter"="tud","Minimum ulna circumference"="muc",
                                                                 "Fragmented Humerus head length"="fhhl","Fragmented Humerus Shaft length"="fhsl","Fragmented humerus olecranon length"="fhol","Fragment humerus trochlea length"="fhtl",
                                                                 "Fragmented radius head length"="frhl","Fragmented Radius proximal length"="frpl","Fragmented radius shaft length"="frsl","Fragmented radius distal length"="frdl")),
                            h4(textOutput("ahelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=3,
                                   numericInput("UL_mhl_r","Maximum right humeral length",value=NA),
                                   numericInput("UL_mhl_l","Maximum left humeral length",value=NA),
                                   numericInput("UL_heb_r","Right humerus epicondylar breadth",value=NA),
                                   numericInput("UL_heb_l","Left humerus epicondylar breadth",value=NA),
                                   numericInput("UL_vhhd_r","Vertical right humeral head diameter",value=NA),
                                   numericInput("UL_vhhd_l","Vertical left humeral head diameter",value=NA),
                                   numericInput("UL_mxhd_r","Maximum right humeral diameter",value=NA),
                                   numericInput("UL_mxhd_l","Maximum left humeral diameter",value=NA),
                                   numericInput("UL_minhd_r","Minimum right humeral diameter",value=NA),
                                   numericInput("UL_minhd_l","Minimum left humeral diameter",value=NA)),
                            column(width=3,
                                   numericInput("UL_mrl_r","Maximum right radial length",value=NA),
                                   numericInput("UL_mrl_l","Maximum left radial length",value=NA),
                                   numericInput("UL_srd_r","Right sagittal radial diameter",value=NA),
                                   numericInput("UL_srd_l","Left sagittal radial diameter",value=NA),
                                   numericInput("UL_trd_r","Right transverse radial diameter",value=NA),
                                   numericInput("UL_trd_l","Left transverse radial diameter",value=NA),
                                   numericInput("UL_rhd_r","Right radial head diameter",value=NA),
                                   numericInput("UL_rhd_l","Left radial head diameter",value=NA)),
                            column(width=3,
                                   numericInput("UL_mul_r","Maximum right ulna length",value=NA),
                                   numericInput("UL_mul_l","Maximum left ulna length",value=NA),
                                   numericInput("UL_pul_r","Right physiological ulna length",value=NA),
                                   numericInput("UL_pul_l","Left physiological ulna length",value=NA),
                                   numericInput("UL_sud_r","Right sagittal ulna diameter",value=NA),
                                   numericInput("UL_sud_l","Left sagittal ulna diameter",value=NA),
                                   numericInput("UL_tud_r","Right transverse ulna diameter",value=NA),
                                   numericInput("UL_tud_l","Left transverse ulna diameter",value=NA),
                                   numericInput("UL_muc_r","Minimum right ulna circumference",value=NA),
                                   numericInput("UL_muc_l","Minimum left ulna circumference",value=NA)),
                            column(width=3,
                                   numericInput("FLB_fhhl_r","Fragmented right humerus head length",value=NA),
                                   numericInput("FLB_fhhl_l","Fragmented left humerus head length",value=NA),
                                   numericInput("FLB_fhsl_r","Fragmented right humerus Shaft length",value=NA),
                                   numericInput("FLB_fhsl_l","Fragmented left humerus Shaft length",value=NA),
                                   numericInput("FLB_fhol_r","Fragmented right humerus olecranon length",value=NA),
                                   numericInput("FLB_fhol_l","Fragmented left humerus olecranon length",value=NA),
                                   numericInput("FLB_fhtl_r","Fragmented right humerus trochlea length",value=NA),
                                   numericInput("FLB_fhtl_l","Fragmented left humerus trochlea length",value=NA),
                                   numericInput("FLB_frhl_r","Fragmented right radius head length",value=NA),
                                   numericInput("FLB_frhl_l","Fragmented left radius head length",value=NA),
                                   numericInput("FLB_frpl_r","Fragmented right radius proximal length",value=NA),
                                   numericInput("FLB_frpl_l","Fragmented left radius proximal length",value=NA),
                                   numericInput("FLB_frsl_r","Fragmented right radius shaft length",value=NA),
                                   numericInput("FLB_frsl_l","Fragmented left radius shaft length",value=NA),
                                   numericInput("FLB_frdl_r","Fragmented right radius distal length",value=NA),
                                   numericInput("FLB_frdl_l","Fragmented left radius distal length",value=NA))
                   ),
                   tabPanel("Lower Limb",
                            selectInput("lHelp","Help",choices=c("Maximum femur length"="mfl","Bicondylar femur length"="bfl","Epicondylar femur breadth"="efb","Maximum femoral head diamter"="mfhd","Sagitial femoral subtrochanteric diamter"="sfsd","Tranverse femoral subtrochanteric diamter"="tfsd",
                                                                 "Sagittal femoral midshaft diamter"="sfmd","Tranverse femoral midshaft diamter"="tfmd","Midshaft femoral circumference"="mfc","Lateral femur condylar depth"="lfcd",
                                                                 "Medial femur condylar depth"="mfcd","Lateral femur condylar width"="lfcw","Medial femur condylar width"="mfcw","Intercondylar width"="icw","Intercondylar depth"="icd",
                                                                 "Standard tibial length"="stl","Maximum tibial Length"="mtl","Physiological tibial length"="ptl","Maximum proximal tibial breadth"="mptb","Maximum distal tibial breadth"="mdtb","Sagittal tibial diamter"="std","Transverse tibial diamter"="ttd",
                                                                 "Tibial circumference"="tc","Maximum fibula length"="mfbl","Maximum fibula diameter"="mfbd","Fragmented femur proximal length"="ffpl","Fragmented femur shaft length"="ffsl",
                                                                 "Fragmented femur supracondylar length"="ffscl","Fragmented femur distal length"="ffdl","Fragmented tibia proximal length"="ftpl","Fragmented tibia tuberosity length"="fttl",
                                                                 "Fragmented tibia shaft length"="ftsl","Fragmented tibia distal length"="ftdl","Fragmented tibia malleolus length"="ftml")),
                            h4(textOutput("lhelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=3,
                                   numericInput("LL_mfl_r","Maximum right femur length",value=NA),
                                   numericInput("LL_mfl_l","Maximum left femur length",value=NA),
                                   numericInput("LL_bfl_r","Bicondylar right femur length",value=NA),
                                   numericInput("LL_bfl_l","Bicondylar left femur length",value=NA),
                                   numericInput("LL_efb_r","Right epicondylar femur breadth",value=NA),
                                   numericInput("LL_efb_l","Left epicondylar femur breadth",value=NA),
                                   numericInput("LL_mfhd_r","Maximum right femoral head diameter",value=NA),
                                   numericInput("LL_mfhd_l","Maximum left femoral head diameter",value=NA),
                                   numericInput("LL_sfsd_r","Right sagitial femoral subtrochanteric diamter",value=NA),
                                   numericInput("LL_sfsd_l","Left sagitial femoral subtrochanteric diamter",value=NA),
                                   numericInput("LL_tfsd_r","Right tranverse femoral subtrochanteric diamter",value=NA),
                                   numericInput("LL_tfsd_l","Left tranverse femoral subtrochanteric diamter",value=NA),
                                   numericInput("LL_sfmd_r","Right sagittal femoral midshaft diamter",value=NA),
                                   numericInput("LL_sfmd_l","Left sagittal femoral midshaft diamter",value=NA),
                                   numericInput("LL_tfmd_r","Right tranverse femoral midshaft diamter",value=NA),
                                   numericInput("LL_tfmd_l","Left tranverse femoral midshaft diamter",value=NA),
                                   numericInput("LL_mfc_r","Right midshaft femoral circumference",value=NA),
                                   numericInput("LL_mfc_l","Left midshaft femoral circumference",value=NA)),
                            column(width=3,
                                   numericInput("LL_lfcd_r","Right lateral femur condylar depth",value=NA),
                                   numericInput("LL_lfcd_l","Left lateral femur condylar depth",value=NA),
                                   numericInput("LL_mfcd_r","Right medial femur condylar depth",value=NA),
                                   numericInput("LL_mfcd_l","Left medial femur condylar depth",value=NA),
                                   numericInput("LL_lfcw_r","Right lateral femur condylar width",value=NA),
                                   numericInput("LL_lfcw_l","Left lateral femur condylar width",value=NA),
                                   numericInput("LL_mfcw_r","Right medial femur condylar width",value=NA),
                                   numericInput("LL_mfcw_l","Left medial femur condylar width",value=NA),
                                   numericInput("LL_icw_r","Right intercondylar width",value=NA),
                                   numericInput("LL_icw_l","Left intercondylar width",value=NA),
                                   numericInput("LL_icd_r","Right intercondylar depth",value=NA),
                                   numericInput("LL_icd_l","Left intercondylar depth",value=NA),
                                   numericInput("LL_mfbl_r","Maximum right fibula length",value=NA),
                                   numericInput("LL_mfbl_l","Maximum left fibula length",value=NA),
                                   numericInput("LL_mfbd_r","Maximum right fibula diameter",value=NA),
                                   numericInput("LL_mfbd_l","Maximum left fibula diameter",value=NA)),
                            column(width=3,
                                   numericInput("LL_stl_r","Standard right tibial length",value=NA),
                                   numericInput("LL_stl_l","Standard left tibial length",value=NA),
                                   numericInput("LL_mtl_r","Maximum right tibial Length",value=NA),
                                   numericInput("LL_mtl_l","Maximum left tibial Length",value=NA),
                                   numericInput("LL_ptl_r","Physiological right tibial length",value=NA),
                                   numericInput("LL_ptl_l","Physiological left tibial length",value=NA),
                                   numericInput("LL_mptb_r","Maximum right proximal tibial breadth",value=NA),
                                   numericInput("LL_mptb_l","Maximum left proximal tibial breadth",value=NA),
                                   numericInput("LL_mdtb_r","Maximum right distal tibial breadth",value=NA),
                                   numericInput("LL_mdtb_l","Maximum right distal tibial breadth",value=NA),
                                   numericInput("LL_std_r","Right sagittal tibial diamter",value=NA),
                                   numericInput("LL_std_l","Left sagittal tibial diamter",value=NA),
                                   numericInput("LL_ttd_r","Right transverse tibial diamter",value=NA),
                                   numericInput("LL_ttd_l","Left transverse tibial diamter",value=NA),
                                   numericInput("LL_tc_r","Right tibial circumference",value=NA),
                                   numericInput("LL_tc_l","Left tibial circumference",value=NA)),
                            
                            column(width=3,
                                   numericInput("FLB_ffpl_r","Fragmented right femur proximal length",value=NA),
                                   numericInput("FLB_ffpl_l","Fragmented left femur proximal length",value=NA),
                                   numericInput("FLB_ffsl_r","Fragmented right femur shaft length",value=NA),
                                   numericInput("FLB_ffsl_l","Fragmented left femur shaft length",value=NA),
                                   numericInput("FLB_ffscl_r","Fragmented right femur supracondylar length",value=NA),
                                   numericInput("FLB_ffscl_l","Fragmented left femur supracondylar length",value=NA),
                                   numericInput("FLB_ffdl_r","Fragmented right femur distal length",value=NA),
                                   numericInput("FLB_ffdl_l","Fragmented left femur distal length",value=NA),
                                   numericInput("FLB_ftpl_r","Fragmented right tibia proximal length",value=NA),
                                   numericInput("FLB_ftpl_l","Fragmented left tibia proximal length",value=NA),
                                   numericInput("FLB_fttl_r","Fragmented right tibia tuberosity length",value=NA),
                                   numericInput("FLB_fttl_l","Fragmented left tibia tuberosity length",value=NA),
                                   numericInput("FLB_ftsl_r","Fragmented right tibia shaft length",value=NA),
                                   numericInput("FLB_ftsl_l","Fragmented left tibia shaft length",value=NA),
                                   numericInput("FLB_ftdl_r","Fragmented right tibia distal length",value=NA),
                                   numericInput("FLB_ftdl_l","Fragmented left tibia distal length",value=NA),
                                   numericInput("FLB_ftml_r","Fragmented right tibia malleolus length",value=NA),
                                   numericInput("FLB_ftml_l","Fragmented left tibia malleolus length",value=NA))
                   
                   ),
                   tabPanel("Other",
                            selectInput("oHelp","Help",choices=c("Vertebral body thickness"="vbt","Metatarsal Length"="mtl","Maximum Calcaneal Length"="mcl","Calcaneal Breadth"="cb","Maximum talus Length"="mtl",
                                                                 "Manubrium length"="manl","Mesosternum length"="msl","Sternebra 1 width"="s1w","Sternebra 3 width"="s3w",
                                                                 "Ankle height"="AH","Bi-iliac diameter"="bid","Conjugata vera"="cv","Transverse pelvic diamter"="tpd","Total face height"="n_gn"
                                                                 )),
                            h4(textOutput("ohelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=2,
                                   h4("Vertebral body thickness"),
                                   numericInput("V_c1","c1",value=NA),
                                   numericInput("V_c2","c2",value=NA),
                                   numericInput("V_c3","c3",value=NA),
                                   numericInput("V_c4","c4",value=NA),
                                   numericInput("V_c5","c5",value=NA),
                                   numericInput("V_c6","c6",value=NA),
                                   numericInput("V_c7","c7",value=NA),
                                   numericInput("V_T1","T1",value=NA),
                                   numericInput("V_T2","T2",value=NA),
                                   numericInput("V_T3","T3",value=NA),
                                   numericInput("V_T4","T4",value=NA),
                                   numericInput("V_T5","T5",value=NA)),
                            column(width=2,
                                   numericInput("V_T6","T6",value=NA),
                                   numericInput("V_T7","T7",value=NA),
                                   numericInput("V_T8","T8",value=NA),
                                   numericInput("V_T9","T9",value=NA),
                                   numericInput("V_T10","T10",value=NA),
                                   numericInput("V_T11","T11",value=NA),
                                   numericInput("V_T12","T12",value=NA),
                                   numericInput("V_L1","L1",value=NA),
                                   numericInput("V_L2","L2",value=NA),
                                   numericInput("V_L3","L3",value=NA),
                                   numericInput("V_L4","L4",value=NA),
                                   numericInput("V_L5","L5",value=NA)),
                            column(width=2,
                                   h4("Metatarsal Length"),
                                   numericInput("MT_m1_r","Right m1",value=NA),
                                   numericInput("MT_m2_r","Right m2",value=NA),
                                   numericInput("MT_m3_r","Right m3",value=NA),
                                   numericInput("MT_m4_r","Right m4",value=NA),
                                   numericInput("MT_m5_r","Right m5",value=NA),
                                   numericInput("MT_m1_l","Left m1",value=NA),
                                   numericInput("MT_m2_l","Left m2",value=NA),
                                   numericInput("MT_m3_l","Left m3",value=NA),
                                   numericInput("MT_m4_l","Left m4",value=NA),
                                   numericInput("MT_m5_l","left m5",value=NA)),
                            column(width=3,
                                   numericInput("O_mcl_r","Right maximum Calcaneal Length",value=NA),
                                   numericInput("O_mcl_l","Left maximum Calcaneal Length",value=NA),
                                   numericInput("O_cb_r","Right calcaneal Breadth",value=NA),
                                   numericInput("O_cb_l","Left calcaneal Breadth",value=NA),
                                   numericInput("O_mtl_r","Right maximum talus length",value=NA),
                                   numericInput("O_mtl_l","Left maximum talus length",value=NA),
                                   numericInput("O_manl","Manubrium length",value=NA),
                                   numericInput("O_msl","Mesosternum length",value=NA),
                                   numericInput("O_s1w","Sternebra 1 width",value=NA),
                                   numericInput("O_s3w","Sternebra 3 width",value=NA)),
                            column(width=3,
                                   h4("Measurements that require articulation:"),
                                   numericInput("A_ah_r","Right ankle height",value=NA),
                                   numericInput("A_ah_l","Left ankle height",value=NA),
                                   numericInput("A_bid","Bi-iliac diameter",value=NA),
                                   numericInput("A_cv","Conjugata vera",value=NA),
                                   numericInput("A_tpd","Transverse pelvic diamter",value=NA),
                                   numericInput("A_n_gn","Total face height",value=NA))
                            
                   ),
                   tabPanel("Write",
                            h3(textOutput("score")),
                            textInput("dir","Data Folder",value="../../data/"),
                            column(width=3,
                                   checkboxInput("Average","Average of 3 measurements?",value=FALSE),
                                   checkboxGroupInput("Equipment","Please tick all available equipment",choices=c("Digital sliding calipers","Analog sliding calipers","Spreading calipers","Osteometric board","Tape","Mandibulometer","Craniophore","Coordinate calipers","digitizer tablet","Other")),
                                   conditionalPanel("input.Equipment.indexOf('Other') >= 0 ",
                                                    textInput("equipment2","Specify other",value=NA))
                                   
                            ),
                            column(width=3,
                                   h3("Population Info"),
                                   textInput("POPID","Population ID",value="NA"),
                                   textInput("POPName","Population name",value="NA"),
                                   textInput("Person1","Investigator",value="NA"),
                                   actionButton("Create","Create new file"),
                                   h4(textOutput("PMessage"))
                                   ),
                            column(width=3,
                                   h3("Individual Info"),
                                   textInput("ID","Individual ID",value="NA"),
                                   textInput("Person2","Investigator intials",value="NA"),
                                   actionButton("Append","Add individual"),
                                   h4(textOutput("IMessage"))
                            ),
                            column(width=3,
                                   h3("Compatability check"),
                                   actionButton("Compat","Check file"),
                                   h4(textOutput("ComMessage"))
                            )
                   )
                   ))