library(shiny);library(markdown)

shinyUI(navbarPage("Juvenille Metrics",
                   #Cranial 1:illustrated metrics####
                   tabPanel("Cranial",
                            selectInput("cHelp","Help",c("Occipital:Maximum width of basilaris"="O_MWB","Occipital:Sagital basilaris length"="O_SLB","Occipital:Maximum basilaris length"="O_MLB","Occipital:Maximum lateralis length"="O_MLL","Occipital:Maximum lateralis width"="O_MWL",
                                                         "Temporal:Squama height"="T_SH","Temporal:Squama width"="T_SW","Temporal:Squama length"="T_SL","Temporal:Pars patrosa length"="T_PPL","Temporal:Pars patrosa width"="T_PPW","Temporal:Tympanic ring diameter"="T_TRD",
                                                         "Sphenoid:Body length"="S_BL","Sphenoid:Body width"="S_BW","Sphenoid:Lesser wing length"="S_LWL","Sphenoid:Lesser wing width"="S_LWW","Sphenoid:Greater wing length"="S_GWL","Sphenoid:Greater wing width"="S_GWW",
                                                         "Zygomatic:Length"="Z_L","Zygomatic:Oblique height"="Z_OH","Palatine:Oblique height"="Pl_OH","Maxilla:length"="Mx_L","Maxilla:Height"="Mx_H","Maxilla:Width"="Mx_W","Maxilla:Longest oblique length"="Mx_OL","Mandible:Body length"="Mn_BL","Mandible:Width"="Mn_W","Mandible:Oblique length"="Mn_OL")),
                            h4(textOutput("chelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            #h4(textOutput("Ctest")),
                            column(width=2,
                                   h4("Occipital"),
                                   numericInput("C_O_MWB","Maximum width of basilaris",value=NA),
                                   numericInput("C_O_MWB2",label=NULL,value=NA),
                                   numericInput("C_O_MWB3",label=NULL,value=NA),
                                   numericInput("C_O_SLB","Sagittal basilaris length",value=NA),
                                   numericInput("C_O_SLB2",label=NULL,value=NA),
                                   numericInput("C_O_SLB3",label=NULL,value=NA),
                                   numericInput("C_O_MLB","Maximum basilaris length",value=NA),
                                   numericInput("C_O_MLB2",label=NULL,value=NA),
                                   numericInput("C_O_MLB3",label=NULL,value=NA),
                                   numericInput("C_O_MLL_l","Maximum left lateralis length",value=NA),
                                   numericInput("C_O_MLL2_l",label=NULL,value=NA),
                                   numericInput("C_O_MLL3_l",label=NULL,value=NA),
                                   numericInput("C_O_MWL_l","Maximum left lateralis width",value=NA),
                                   numericInput("C_O_MWL2_l",label=NULL,value=NA),
                                   numericInput("C_O_MWL3_l",label=NULL,value=NA),
                                   numericInput("C_O_MLL_r","Maximum right lateralis length",value=NA),
                                   numericInput("C_O_MLL2_r",label=NULL,value=NA),
                                   numericInput("C_O_MLL3_r",label=NULL,value=NA),
                                   numericInput("C_O_MWL_r","Maximum right lateralis width",value=NA),
                                   numericInput("C_O_MWL2_r",label=NULL,value=NA),
                                   numericInput("C_O_MWL3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Temporal"),
                                   numericInput("C_T_SH_r","Squama height",value=NA),
                                   numericInput("C_T_SH2_r",label=NULL,value=NA),
                                   numericInput("C_T_SH3_r",label=NULL,value=NA),
                                   numericInput("C_T_SW_r","Squama Width",value=NA),
                                   numericInput("C_T_SW2_r",label=NULL,value=NA),
                                   numericInput("C_T_SW3_r",label=NULL,value=NA),
                                   numericInput("C_T_SL_r","Squama length",value=NA),
                                   numericInput("C_T_SL2_r",label=NULL,value=NA),
                                   numericInput("C_T_SL3_r",label=NULL,value=NA),
                                   numericInput("C_T_PPL_r","Pars petrosa length",value=NA),
                                   numericInput("C_T_PPL2_r",label=NULL,value=NA),
                                   numericInput("C_T_PPL3_r",label=NULL,value=NA),
                                   numericInput("C_T_PPW_r","Pars petrosa width",value=NA),
                                   numericInput("C_T_PPW2_r",label=NULL,value=NA),
                                   numericInput("C_T_PPW3_r",label=NULL,value=NA),
                                   numericInput("C_T_TRD_r","Tympanic ring diameter",value=NA),
                                   numericInput("C_T_TRD2_r",label=NULL,value=NA),
                                   numericInput("C_T_TRD3_r",label=NULL,value=NA),
                                   h4("Left Temporal"),
                                   numericInput("C_T_SH_l","Squama height",value=NA),
                                   numericInput("C_T_SH2_l",label=NULL,value=NA),
                                   numericInput("C_T_SH3_l",label=NULL,value=NA),
                                   numericInput("C_T_SW_l","Squama Width",value=NA),
                                   numericInput("C_T_SW2_l",label=NULL,value=NA),
                                   numericInput("C_T_SW3_l",label=NULL,value=NA),
                                   numericInput("C_T_SL_l","Squama length",value=NA),
                                   numericInput("C_T_SL2_l",label=NULL,value=NA),
                                   numericInput("C_T_SL3_l",label=NULL,value=NA),
                                   numericInput("C_T_PPL_l","Pars petrosa length",value=NA),
                                   numericInput("C_T_PPL2_l",label=NULL,value=NA),
                                   numericInput("C_T_PPL3_l",label=NULL,value=NA),
                                   numericInput("C_T_PPW_l","Pars petrosa width",value=NA),
                                   numericInput("C_T_PPW2_l",label=NULL,value=NA),
                                   numericInput("C_T_PPW3_l",label=NULL,value=NA),
                                   numericInput("C_T_TRD_l","Tympanic ring diameter",value=NA),
                                   numericInput("C_T_TRD2_l",label=NULL,value=NA),
                                   numericInput("C_T_TRD3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Sphenoid"),
                                   numericInput("C_S_BL","Body length",value=NA),
                                   numericInput("C_S_BL2",label=NULL,value=NA),
                                   numericInput("C_S_BL3",label=NULL,value=NA),
                                   numericInput("C_S_BW","Body Width",value=NA),
                                   numericInput("C_S_BW2",label=NULL,value=NA),
                                   numericInput("C_S_BW3",label=NULL,value=NA),
                                   numericInput("C_S_LWL_r","Right Lesser wing length",value=NA),
                                   numericInput("C_S_LWL2_r",label=NULL,value=NA),
                                   numericInput("C_S_LWL3_r",label=NULL,value=NA),
                                   numericInput("C_S_LWL_l","Left Lesser wing length",value=NA),
                                   numericInput("C_S_LWL2_l",label=NULL,value=NA),
                                   numericInput("C_S_LWL3_l",label=NULL,value=NA),
                                   numericInput("C_S_LWW_r","Right Lesser wing width",value=NA),
                                   numericInput("C_S_LWW2_r",label=NULL,value=NA),
                                   numericInput("C_S_LWW3_r",label=NULL,value=NA),
                                   numericInput("C_S_LWW_l","Left Lesser wing width",value=NA),
                                   numericInput("C_S_LWW2_l",label=NULL,value=NA),
                                   numericInput("C_S_LWW3_l",label=NULL,value=NA),
                                   numericInput("C_S_GWL_r","Right Greater wing length",value=NA),
                                   numericInput("C_S_GWL2_r",label=NULL,value=NA),
                                   numericInput("C_S_GWL3_r",label=NULL,value=NA),
                                   numericInput("C_S_GWL_l","Left Greater wing length",value=NA),
                                   numericInput("C_S_GWL2_l",label=NULL,value=NA),
                                   numericInput("C_S_GWL3_l",label=NULL,value=NA),
                                   numericInput("C_S_GWW_r","Right Greater wing width",value=NA),
                                   numericInput("C_S_GWW2_r",label=NULL,value=NA),
                                   numericInput("C_S_GWW3_r",label=NULL,value=NA),
                                   numericInput("C_S_GWW_l","Left Greater wing width",value=NA),
                                   numericInput("C_S_GWW2_l",label=NULL,value=NA),
                                   numericInput("C_S_GWW3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Zygomatic"),
                                   numericInput("C_Z_L_r","Right length",value=NA),
                                   numericInput("C_Z_L2_r",label=NULL,value=NA),
                                   numericInput("C_Z_L3_r",label=NULL,value=NA),
                                   numericInput("C_Z_L_l","Left length",value=NA),
                                   numericInput("C_Z_L2_l",label=NULL,value=NA),
                                   numericInput("C_Z_L3_l",label=NULL,value=NA),
                                   numericInput("C_Z_OH_r","Right oblique height",value=NA),
                                   numericInput("C_Z_OH2_r",label=NULL,value=NA),
                                   numericInput("C_Z_OH3_r",label=NULL,value=NA),
                                   numericInput("C_Z_OH_l","Left oblique height",value=NA),
                                   numericInput("C_Z_OH2_l",label=NULL,value=NA),
                                   numericInput("C_Z_OH3_l",label=NULL,value=NA),
                                   h4("Palatine"),
                                   numericInput("C_Pl_OH_r","Right oblique height",value=NA),
                                   numericInput("C_Pl_OH2_r",label=NULL,value=NA),
                                   numericInput("C_Pl_OH3_r",label=NULL,value=NA),
                                   numericInput("C_Pl_OH_l","Left oblique height",value=NA),
                                   numericInput("C_Pl_OH2_l",label=NULL,value=NA),
                                   numericInput("C_Pl_OH3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Maxilla"),
                                   numericInput("C_Mx_L_r","Length",value=NA),
                                   numericInput("C_Mx_L2_r",label=NULL,value=NA),
                                   numericInput("C_Mx_L3_r",label=NULL,value=NA),
                                   numericInput("C_Mx_H_r","Height",value=NA),
                                   numericInput("C_Mx_H2_r",label=NULL,value=NA),
                                   numericInput("C_Mx_H3_r",label=NULL,value=NA),
                                   numericInput("C_Mx_W_r","Width",value=NA),
                                   numericInput("C_Mx_W2_r",label=NULL,value=NA),
                                   numericInput("C_Mx_W3_r",label=NULL,value=NA),
                                   numericInput("C_Mx_OL_r","Longest oblique length",value=NA),
                                   numericInput("C_Mx_OL2_r",label=NULL,value=NA),
                                   numericInput("C_Mx_OL3_r",label=NULL,value=NA),
                                   h4("Left Maxilla"),
                                   numericInput("C_Mx_L_l","Length",value=NA),
                                   numericInput("C_Mx_L2_l",label=NULL,value=NA),
                                   numericInput("C_Mx_L3_l",label=NULL,value=NA),
                                   numericInput("C_Mx_H_l","Height",value=NA),
                                   numericInput("C_Mx_H2_l",label=NULL,value=NA),
                                   numericInput("C_Mx_H3_l",label=NULL,value=NA),
                                   numericInput("C_Mx_W_l","Width",value=NA),
                                   numericInput("C_Mx_W2_l",label=NULL,value=NA),
                                   numericInput("C_Mx_W3_l",label=NULL,value=NA),
                                   numericInput("C_Mx_OL_l","Longest oblique length",value=NA),
                                   numericInput("C_Mx_OL2_l",label=NULL,value=NA),
                                   numericInput("C_Mx_OL3_l",label=NULL,value=NA)
                                   ),
                            column(width=2,
                                   h4("RightMandible"),
                                   numericInput("C_Mn_BL_r","Body length",value=NA),
                                   numericInput("C_Mn_BL2_r",label=NULL,value=NA),
                                   numericInput("C_Mn_BL3_r",label=NULL,value=NA),
                                   numericInput("C_Mn_W_r","Width",value=NA),
                                   numericInput("C_Mn_W2_r",label=NULL,value=NA),
                                   numericInput("C_Mn_W3_r",label=NULL,value=NA),
                                   numericInput("C_Mn_OL_r","Oblique length",value=NA),
                                   numericInput("C_Mn_OL2_r",label=NULL,value=NA),
                                   numericInput("C_Mn_OL3_r",label=NULL,value=NA),
                                   h4("Left Mandible"),
                                   numericInput("C_Mn_BL_l","Body length",value=NA),
                                   numericInput("C_Mn_BL2_l",label=NULL,value=NA),
                                   numericInput("C_Mn_BL3_l",label=NULL,value=NA),
                                   numericInput("C_Mn_W_l","Width",value=NA),
                                   numericInput("C_Mn_W2_l",label=NULL,value=NA),
                                   numericInput("C_Mn_W3_l",label=NULL,value=NA),
                                   numericInput("C_Mn_OL_l","Oblique length",value=NA),
                                   numericInput("C_Mn_OL2_l",label=NULL,value=NA),
                                   numericInput("C_Mn_OL3_l",label=NULL,value=NA))),
                   #Cranial 2: other described metrics####
                   tabPanel("Cranial2",
                            selectInput("c2Help","Help",c("Parietal:Chord Height"="P_CH","Parietal:Chord width"="P_CW","Parietal:Arc height"="P_AH","Parietal:Arc width"="P_AW","Parietal:Bregma-Lambda chord"="P_BLC","Parietal:Bregma-Lambda arc"="P_BLA",
                                                         "Frontal:Chord Height"="F_CH","Frontal:Chord width"="F_CW","Frontal:Arc height"="F_AH","Frontal:Arc width"="F_AW","Frontal:Nasion-Bregma chord"="F_NBC","Frontal:Nasion-Bregma arc"="F_NBA",
                                                         "Nasal:Length"="N_L","Nasal:Width"="N_W","Nasal:Aperture Height"="N_AH","Nasal:Superior Aperture Width"="N_SAW","Nasal:Maximum Aperture width"="N_MAW","Nasal:Internasal suture length"="N_INSL","Nasal:Breadth"="N_B",
                                                         "Inferior nasal concha:Length"="INC_L","Vomer:Length"="V_L")),
                            h4(textOutput("c2help")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=2,
                                   h4("Right Parietal"),
                                   numericInput("C2_P_CH_r","Chord height",value=NA),
                                   numericInput("C2_P_CH2_r",label=NULL,value=NA),
                                   numericInput("C2_P_CH3_r",label=NULL,value=NA),
                                   numericInput("C2_P_CW_r","Chord width",value=NA),
                                   numericInput("C2_P_CW2_r",label=NULL,value=NA),
                                   numericInput("C2_P_CW3_r",label=NULL,value=NA),
                                   numericInput("C2_P_AH_r","Arc height",value=NA),
                                   numericInput("C2_P_AH2_r",label=NULL,value=NA),
                                   numericInput("C2_P_AH3_r",label=NULL,value=NA),
                                   numericInput("C2_P_AW_r","Arc width",value=NA),
                                   numericInput("C2_P_AW2_r",label=NULL,value=NA),
                                   numericInput("C2_P_AW3_r",label=NULL,value=NA),
                                   numericInput("C2_P_BLC_r","Bregma-Lambda chord",value=NA),
                                   numericInput("C2_P_BLC2_r",label=NULL,value=NA),
                                   numericInput("C2_P_BLC3_r",label=NULL,value=NA),
                                   numericInput("C2_P_BLA_r","Bregma-Lambda arc",value=NA),
                                   numericInput("C2_P_BLA2_r",label=NULL,value=NA),
                                   numericInput("C2_P_BLA3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left Parietal"),
                                   numericInput("C2_P_CH_l","Chord height",value=NA),
                                   numericInput("C2_P_CH2_l",label=NULL,value=NA),
                                   numericInput("C2_P_CH3_l",label=NULL,value=NA),
                                   numericInput("C2_P_CW_l","Chord width",value=NA),
                                   numericInput("C2_P_CW2_l",label=NULL,value=NA),
                                   numericInput("C2_P_CW3_l",label=NULL,value=NA),
                                   numericInput("C2_P_AH_l","Arc height",value=NA),
                                   numericInput("C2_P_AH2_l",label=NULL,value=NA),
                                   numericInput("C2_P_AH3_l",label=NULL,value=NA),
                                   numericInput("C2_P_AW_l","Arc width",value=NA),
                                   numericInput("C2_P_AW2_l",label=NULL,value=NA),
                                   numericInput("C2_P_AW3_l",label=NULL,value=NA),
                                   numericInput("C2_P_BLC_l","Bregma-Lambda chord",value=NA),
                                   numericInput("C2_P_BLC2_l",label=NULL,value=NA),
                                   numericInput("C2_P_BLC3_l",label=NULL,value=NA),
                                   numericInput("C2_P_BLA_l","Bregma-Lambda arc",value=NA),
                                   numericInput("C2_P_BLA2_l",label=NULL,value=NA),
                                   numericInput("C2_P_BLA3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Frontal"),
                                   numericInput("C2_F_CH_r","Chord height",value=NA),
                                   numericInput("C2_F_CH2_r",label=NULL,value=NA),
                                   numericInput("C2_F_CH3_r",label=NULL,value=NA),
                                   numericInput("C2_F_CW_r","Chord width",value=NA),
                                   numericInput("C2_F_CW2_r",label=NULL,value=NA),
                                   numericInput("C2_F_CW3_r",label=NULL,value=NA),
                                   numericInput("C2_F_AH_r","Arc height",value=NA),
                                   numericInput("C2_F_AH2_r",label=NULL,value=NA),
                                   numericInput("C2_F_AH3_r",label=NULL,value=NA),
                                   numericInput("C2_F_AW_r","Arc width",value=NA),
                                   numericInput("C2_F_AW2_r",label=NULL,value=NA),
                                   numericInput("C2_F_AW3_r",label=NULL,value=NA),
                                   numericInput("C2_F_NBC_r","Nasion-Bregma chord",value=NA),
                                   numericInput("C2_F_NBC2_r",label=NULL,value=NA),
                                   numericInput("C2_F_NBC3_r",label=NULL,value=NA),
                                   numericInput("C2_F_NBA_r","Nasion-Bregma arc",value=NA),
                                   numericInput("C2_F_NBA2_r",label=NULL,value=NA),
                                   numericInput("C2_F_NBA3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left Frontal"),
                                   numericInput("C2_F_CH_l","Chord height",value=NA),
                                   numericInput("C2_F_CH2_l",label=NULL,value=NA),
                                   numericInput("C2_F_CH3_l",label=NULL,value=NA),
                                   numericInput("C2_F_CW_l","Chord width",value=NA),
                                   numericInput("C2_F_CW2_l",label=NULL,value=NA),
                                   numericInput("C2_F_CW3_l",label=NULL,value=NA),
                                   numericInput("C2_F_AH_l","Arc height",value=NA),
                                   numericInput("C2_F_AH2_l",label=NULL,value=NA),
                                   numericInput("C2_F_AH3_l",label=NULL,value=NA),
                                   numericInput("C2_F_AW_l","Arc width",value=NA),
                                   numericInput("C2_F_AW2_l",label=NULL,value=NA),
                                   numericInput("C2_F_AW3_l",label=NULL,value=NA),
                                   numericInput("C2_F_NBC_l","Nasion-Bregma chord",value=NA),
                                   numericInput("C2_F_NBC2_l",label=NULL,value=NA),
                                   numericInput("C2_F_NBC3_l",label=NULL,value=NA),
                                   numericInput("C2_F_NBA_l","Nasion-Bregma arc",value=NA),
                                   numericInput("C2_F_NBA2_l",label=NULL,value=NA),
                                   numericInput("C2_F_NBA3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Nasal"),
                                   numericInput("C2_N_L_r","Right Length",value=NA),
                                   numericInput("C2_N_L2_r",label=NULL,value=NA),
                                   numericInput("C2_N_L3_r",label=NULL,value=NA),
                                   numericInput("C2_N_L_l","Left Length",value=NA),
                                   numericInput("C2_N_L2_l",label=NULL,value=NA),
                                   numericInput("C2_N_L3_l",label=NULL,value=NA),
                                   numericInput("C2_N_W_r","Right width",value=NA),
                                   numericInput("C2_N_W2_r",label=NULL,value=NA),
                                   numericInput("C2_N_W3_r",label=NULL,value=NA),
                                   numericInput("C2_N_W_l","Left width",value=NA),
                                   numericInput("C2_N_W2_l",label=NULL,value=NA),
                                   numericInput("C2_N_W3_l",label=NULL,value=NA),
                                   numericInput("C2_N_AH","Aperture Height",value=NA),
                                   numericInput("C2_N_AH2",label=NULL,value=NA),
                                   numericInput("C2_N_AH3",label=NULL,value=NA),
                                   numericInput("C2_N_SAW","Superior Aperture  width",value=NA),
                                   numericInput("C2_N_SAW2",label=NULL,value=NA),
                                   numericInput("C2_N_SAW3",label=NULL,value=NA),
                                   numericInput("C2_N_MAW","Maximum Aperture width",value=NA),
                                   numericInput("C2_N_MAW2",label=NULL,value=NA),
                                   numericInput("C2_N_MAW3",label=NULL,value=NA),
                                   numericInput("C2_N_INSL","Internasal suture length",value=NA),
                                   numericInput("C2_N_INSL2",label=NULL,value=NA),
                                   numericInput("C2_N_INSL3",label=NULL,value=NA),
                                   numericInput("C2_N_B","Breadth",value=NA),
                                   numericInput("C2_N_B2",label=NULL,value=NA),
                                   numericInput("C2_N_B3",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Inferior nasal concha"),
                                   numericInput("C2_INC_L_r","Right length",value=NA),
                                   numericInput("C2_INC_L2_r",label=NULL,value=NA),
                                   numericInput("C2_INC_L3_r",label=NULL,value=NA),
                                   numericInput("C2_INC_L_l","Left length",value=NA),
                                   numericInput("C2_INC_L2_l",label=NULL,value=NA),
                                   numericInput("C2_INC_L3_l",label=NULL,value=NA),
                                   h4("Vomer"),
                                   numericInput("C2_V_L_r","Right length",value=NA),
                                   numericInput("C2_V_L2_r",label=NULL,value=NA),
                                   numericInput("C2_V_L3_r",label=NULL,value=NA),
                                   numericInput("C2_V_L_l","Left length",value=NA),
                                   numericInput("C2_V_L2_l",label=NULL,value=NA),
                                   numericInput("C2_V_L3_l",label=NULL,value=NA))),
                   #Shoulder:Scapula and clavicle####
                   tabPanel("Shoulder",
                            selectInput("sHelp","Help",c("Scapula:Length of glenoid surface"="S_GSL","Scapula:Mid glenoid diameter"="S_MGD","Scapula:Glenoid mass length"="S_GML","Scapula:Spine length"="S_SL","Scapula:Width"="S_W",
                                                         "Scapula:Length"="S_L","Scapula:Infra-scapular height"="S_ISH","Scapula:Supra-scapular height"="S_SSH","Scapula:Acromial width"="S_AW","Clavicle:Maximum length"="C_L")),
                            h4(textOutput("shelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=2,
                                   h4("Right Scapula"),
                                   numericInput("SH_S_GSL_r","Length of glenoid surface",value=NA),
                                   numericInput("SH_S_GSL2_r",label=NULL,value=NA),
                                   numericInput("SH_S_GSL3_r",label=NULL,value=NA),
                                   numericInput("SH_S_MGD_r","Mid glenoid diameter",value=NA),
                                   numericInput("SH_S_MGD2_r",label=NULL,value=NA),
                                   numericInput("SH_S_MGD3_r",label=NULL,value=NA),
                                   numericInput("SH_S_GML_r","Glenoid mass length",value=NA),
                                   numericInput("SH_S_GML2_r",label=NULL,value=NA),
                                   numericInput("SH_S_GML3_r",label=NULL,value=NA),
                                   numericInput("SH_S_SL_r","Spine length",value=NA),
                                   numericInput("SH_S_SL2_r",label=NULL,value=NA),
                                   numericInput("SH_S_SL3_r",label=NULL,value=NA),
                                   numericInput("SH_S_W_r","Width",value=NA),
                                   numericInput("SH_S_W2_r",label=NULL,value=NA),
                                   numericInput("SH_S_W3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4(br()),
                                   numericInput("SH_S_L_r","Length",value=NA),
                                   numericInput("SH_S_L2_r",label=NULL,value=NA),
                                   numericInput("SH_S_L3_r",label=NULL,value=NA),
                                   numericInput("SH_S_ISH_r","Infra-scapular height",value=NA),
                                   numericInput("SH_S_ISH2_r",label=NULL,value=NA),
                                   numericInput("SH_S_ISH3_r",label=NULL,value=NA),
                                   numericInput("SH_S_SSH_r","Supra-scapular height",value=NA),
                                   numericInput("SH_S_SSH2_r",label=NULL,value=NA),
                                   numericInput("SH_S_SSH3_r",label=NULL,value=NA),
                                   numericInput("SH_S_AW_r","Acromial width",value=NA),
                                   numericInput("SH_S_AW2_r",label=NULL,value=NA),
                                   numericInput("SH_S_AW3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left Scapula"),
                                   numericInput("SH_S_GSL_l","Length of glenoid surface",value=NA),
                                   numericInput("SH_S_GSL2_l",label=NULL,value=NA),
                                   numericInput("SH_S_GSL3_l",label=NULL,value=NA),
                                   numericInput("SH_S_MGD_l","Mid gelnoid diameter",value=NA),
                                   numericInput("SH_S_MGD2_l",label=NULL,value=NA),
                                   numericInput("SH_S_MGD3_l",label=NULL,value=NA),
                                   numericInput("SH_S_GML_l","Glenoid mass length",value=NA),
                                   numericInput("SH_S_GML2_l",label=NULL,value=NA),
                                   numericInput("SH_S_GML3_l",label=NULL,value=NA),
                                   numericInput("SH_S_SL_l","Spine length",value=NA),
                                   numericInput("SH_S_SL2_l",label=NULL,value=NA),
                                   numericInput("SH_S_SL3_l",label=NULL,value=NA),
                                   numericInput("SH_S_W_l","Width",value=NA),
                                   numericInput("SH_S_W2_l",label=NULL,value=NA),
                                   numericInput("SH_S_W3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4(br()),
                                   numericInput("SH_S_L_l","Length",value=NA),
                                   numericInput("SH_S_L2_l",label=NULL,value=NA),
                                   numericInput("SH_S_L3_l",label=NULL,value=NA),
                                   numericInput("SH_S_ISH_l","Infra-scapular height",value=NA),
                                   numericInput("SH_S_ISH2_l",label=NULL,value=NA),
                                   numericInput("SH_S_ISH3_l",label=NULL,value=NA),
                                   numericInput("SH_S_SSH_l","Supra-scapular height",value=NA),
                                   numericInput("SH_S_SSH2_l",label=NULL,value=NA),
                                   numericInput("SH_S_SSH3_l",label=NULL,value=NA),
                                   numericInput("SH_S_AW_l","Acromial width",value=NA),
                                   numericInput("SH_S_AW2_l",label=NULL,value=NA),
                                   numericInput("SH_S_AW3_l",label=NULL,value=NA)),
                            column(width=4,
                                   h4("Right Clavicle"),
                                   numericInput("SH_C_L_r","Maximum Length",value=NA),
                                   numericInput("SH_C_L2_r",label=NULL,value=NA),
                                   numericInput("SH_C_L3_r",label=NULL,value=NA),
                                   h4("Left Clavicle"),
                                   numericInput("SH_C_L_l","Maximum Length",value=NA),
                                   numericInput("SH_C_L2_l",label=NULL,value=NA),
                                   numericInput("SH_C_L3_l",label=NULL,value=NA))),
                   #Upperlimb:Humerus,ulna,radius,metacarpals####
                   tabPanel("Upper Limb",
                            selectInput("ulHelp","Help",c("Humerus:Diaphyseal length"="H_DL","Humerus:Distal Width"="H_DW","Humerus:Total Length"="H_TL","Ulna:Diaphyseal length"="U_DL","Ulna:Total length"="U_TL",
                                                          "Radius:Diaphyseal length"="R_DL","Radius:Total length"="R_TL","1st Metacarpal:Length"="MC1_L","2nd Metacarpal:Length"="MC2_L","2nd Metacarpal:Midshaft width"="MC2_W")),
                            h4(textOutput("ulhelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=2,
                                   h4("Right Humerus"),
                                   numericInput("UL_H_DL_r","Diaphyseal Length",value=NA),
                                   numericInput("UL_H_DL2_r",label=NULL,value=NA),
                                   numericInput("UL_H_DL3_r",label=NULL,value=NA),
                                   numericInput("UL_H_DW_r","Distal width",value=NA),
                                   numericInput("UL_H_DW2_r",label=NULL,value=NA),
                                   numericInput("UL_H_DW3_r",label=NULL,value=NA),
                                   numericInput("UL_H_TL_r","Total Length",value=NA),
                                   numericInput("UL_H_TL2_r",label=NULL,value=NA),
                                   numericInput("UL_H_TL3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left Humerus"),
                                   numericInput("UL_H_DL_l","Diaphyseal Length",value=NA),
                                   numericInput("UL_H_DL2_l",label=NULL,value=NA),
                                   numericInput("UL_H_DL3_l",label=NULL,value=NA),
                                   numericInput("UL_H_DW_l","Distal width",value=NA),
                                   numericInput("UL_H_DW2_l",label=NULL,value=NA),
                                   numericInput("UL_H_DW3_l",label=NULL,value=NA),
                                   numericInput("UL_H_TL_l","Total Length",value=NA),
                                   numericInput("UL_H_TL2_l",label=NULL,value=NA),
                                   numericInput("UL_H_TL3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Ulna"),
                                   numericInput("UL_U_DL_r","Diaphyseal Length",value=NA),
                                   numericInput("UL_U_DL2_r",label=NULL,value=NA),
                                   numericInput("UL_U_DL3_r",label=NULL,value=NA),
                                   numericInput("UL_U_TL_r","Total Length",value=NA),
                                   numericInput("UL_U_TL2_r",label=NULL,value=NA),
                                   numericInput("UL_U_TL3_r",label=NULL,value=NA),
                                   h4("Left Ulna"),
                                   numericInput("UL_U_DL_l","Diaphyseal Length",value=NA),
                                   numericInput("UL_U_DL2_l",label=NULL,value=NA),
                                   numericInput("UL_U_DL3_l",label=NULL,value=NA),
                                   numericInput("UL_U_TL_l","Total Length",value=NA),
                                   numericInput("UL_U_TL2_l",label=NULL,value=NA),
                                   numericInput("UL_U_TL3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Radius"),
                                   numericInput("UL_R_DL_r","Diaphyseal Length",value=NA),
                                   numericInput("UL_R_DL2_r",label=NULL,value=NA),
                                   numericInput("UL_R_DL3_r",label=NULL,value=NA),
                                   numericInput("UL_R_TL_r","Total Length",value=NA),
                                   numericInput("UL_R_TL2_r",label=NULL,value=NA),
                                   numericInput("UL_R_TL3_r",label=NULL,value=NA),
                                   h4("Left Radius"),
                                   numericInput("UL_R_DL_l","Diaphyseal Length",value=NA),
                                   numericInput("UL_R_DL2_l",label=NULL,value=NA),
                                   numericInput("UL_R_DL3_l",label=NULL,value=NA),
                                   numericInput("UL_R_TL_l","Total Length",value=NA),
                                   numericInput("UL_R_TL2_l",label=NULL,value=NA),
                                   numericInput("UL_R_TL3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("1st Metacarpals"),
                                   numericInput("UL_MC1_L_r","Right length",value=NA),
                                   numericInput("UL_MC1_L2_r",label=NULL,value=NA),
                                   numericInput("UL_MC1_L3_r",label=NULL,value=NA),
                                   numericInput("UL_MC1_L_l","Left length",value=NA),
                                   numericInput("UL_MC1_L2_l",label=NULL,value=NA),
                                   numericInput("UL_MC1_L3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("2nd Metacarpal"),
                                   numericInput("UL_MC2_L_r","Right length",value=NA),
                                   numericInput("UL_MC2_L2_r",label=NULL,value=NA),
                                   numericInput("UL_MC2_L3_r",label=NULL,value=NA),
                                   numericInput("UL_MC2_W_r","Right Midshaft width",value=NA),
                                   numericInput("UL_MC2_W2_r",label=NULL,value=NA),
                                   numericInput("UL_MC2_W3_r",label=NULL,value=NA),
                                   numericInput("UL_MC2_L_l","Left 2nd metacarpal length",value=NA),
                                   numericInput("UL_MC2_L2_l",label=NULL,value=NA),
                                   numericInput("UL_MC2_L3_l",label=NULL,value=NA),
                                   numericInput("UL_MC2_W_l","Left Midshaft width",value=NA),
                                   numericInput("UL_MC2_W2_l",label=NULL,value=NA),
                                   numericInput("UL_MC2_W3_l",label=NULL,value=NA))),
                   #Pelvis:Illium,ischium,pubis####
                   tabPanel("Pelvis",
                            selectInput("pHelp","Help",c("Illium:Maximum length"="Il_L","Illium: Maximum width"="Il_W","Ischium:Maximum length"="Is_L","Ischium:Maximum width"="Is_W","Pubis:Maximum length"="P_L")),
                            h4(textOutput("phelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=2,
                                   h4("Right illium"),
                                   numericInput("P_Il_L_r","Maximum length",value=NA),
                                   numericInput("P_Il_L2_r",label=NULL,value=NA),
                                   numericInput("P_Il_L3_r",label=NULL,value=NA),
                                   numericInput("P_Il_W_r","Maximum Width",value=NA),
                                   numericInput("P_Il_W2_r",label=NULL,value=NA),
                                   numericInput("P_Il_W3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left illium"),
                                   numericInput("P_Il_L_l","Maximum length",value=NA),
                                   numericInput("P_Il_L2_l",label=NULL,value=NA),
                                   numericInput("P_Il_L3_l",label=NULL,value=NA),
                                   numericInput("P_Il_W_l","Maximum Width",value=NA),
                                   numericInput("P_Il_W2_l",label=NULL,value=NA),
                                   numericInput("P_Il_W3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right ischium"),
                                   numericInput("P_Is_L_r","Maximum length",value=NA),
                                   numericInput("P_Is_L2_r",label=NULL,value=NA),
                                   numericInput("P_Is_L3_r",label=NULL,value=NA),
                                   numericInput("P_Is_W_r","Maximum Width",value=NA),
                                   numericInput("P_Is_W2_r",label=NULL,value=NA),
                                   numericInput("P_Is_W3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left ischium"),
                                   numericInput("P_Is_L_l","Maximum length",value=NA),
                                   numericInput("P_Is_L2_l",label=NULL,value=NA),
                                   numericInput("P_Is_L3_l",label=NULL,value=NA),
                                   numericInput("P_Is_W_l","Maximum Width",value=NA),
                                   numericInput("P_Is_W2_l",label=NULL,value=NA),
                                   numericInput("P_Is_W3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right pubis"),
                                   numericInput("P_P_L_r","Maximum length",value=NA),
                                   numericInput("P_P_L2_r",label=NULL,value=NA),
                                   numericInput("P_P_L3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left pubis"),
                                   numericInput("P_P_L_l","Maximum length",value=NA),
                                   numericInput("P_P_L2_l",label=NULL,value=NA),
                                   numericInput("P_P_L3_l",label=NULL,value=NA))),
                   #LowerLimb: Femur,tibia, fibula,metatarsals####
                   tabPanel("Lower Limb",
                            selectInput("llHelp","Help",c("Femur:Diaphyseal length"="F_DL","Femur:Distal width"="F_DW","Femur:Total length"="F_TL","Tibia:Diaphyseal length"="T_DL","Tibia:Total length"="T_TL","Fibula:Diaphyseal length"="Fb_DL","Fibula:Total length"="Fb_TL","Metatarsal:Diaphyseal length"="MT_DL")),
                            h4(textOutput("llhelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=2,
                                   h4("Right Femur"),
                                   numericInput("LL_F_DL_r","Diaphyseal Length",value=NA),
                                   numericInput("LL_F_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_F_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_F_DW_r","Distal width",value=NA),
                                   numericInput("LL_F_DW2_r",label=NULL,value=NA),
                                   numericInput("LL_F_DW3_r",label=NULL,value=NA),
                                   numericInput("LL_F_TL_r","Total Length",value=NA),
                                   numericInput("LL_F_TL2_r",label=NULL,value=NA),
                                   numericInput("LL_F_TL3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left Femur"),
                                   numericInput("LL_F_DL_l","Diaphyseal Length",value=NA),
                                   numericInput("LL_F_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_F_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_F_DW_l","Distal width",value=NA),
                                   numericInput("LL_F_DW2_l",label=NULL,value=NA),
                                   numericInput("LL_F_DW3_l",label=NULL,value=NA),
                                   numericInput("LL_F_TL_l","Total Length",value=NA),
                                   numericInput("LL_F_TL2_l",label=NULL,value=NA),
                                   numericInput("LL_F_TL3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right tibia"),
                                   numericInput("LL_T_DL_r","Diaphyseal Length",value=NA),
                                   numericInput("LL_T_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_T_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_T_TL_r","Total Length",value=NA),
                                   numericInput("LL_T_TL2_r",label=NULL,value=NA),
                                   numericInput("LL_T_TL3_r",label=NULL,value=NA),
                                   h4("Left Tibia"),
                                   numericInput("LL_T_DL_l","Diaphyseal Length",value=NA),
                                   numericInput("LL_T_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_T_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_T_TL_l","Total Length",value=NA),
                                   numericInput("LL_T_TL2_l",label=NULL,value=NA),
                                   numericInput("LL_T_TL3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Fibula"),
                                   numericInput("LL_Fb_DL_r","Diaphyseal Length",value=NA),
                                   numericInput("LL_Fb_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_Fb_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_Fb_TL_r","Total Length",value=NA),
                                   numericInput("LL_Fb_TL2_r",label=NULL,value=NA),
                                   numericInput("LL_Fb_TL3_r",label=NULL,value=NA),
                                   h4("Left Fibula"),
                                   numericInput("LL_Fb_DL_l","Diaphyseal Length",value=NA),
                                   numericInput("LL_Fb_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_Fb_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_Fb_TL_l","Total Length",value=NA),
                                   numericInput("LL_Fb_TL2_l",label=NULL,value=NA),
                                   numericInput("LL_Fb_TL3_l",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Right Metatarsals"),
                                   numericInput("LL_MT1_DL_r","1st Diaphyseal Length",value=NA),
                                   numericInput("LL_MT1_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_MT1_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_MT2_DL_r","2nd Diaphyseal Length",value=NA),
                                   numericInput("LL_MT2_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_MT2_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_MT3_DL_r","3rd Diaphyseal Length",value=NA),
                                   numericInput("LL_MT3_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_MT3_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_MT4_DL_r","4th Diaphyseal Length",value=NA),
                                   numericInput("LL_MT4_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_MT4_DL3_r",label=NULL,value=NA),
                                   numericInput("LL_MT5_DL_r","5th Diaphyseal Length",value=NA),
                                   numericInput("LL_MT5_DL2_r",label=NULL,value=NA),
                                   numericInput("LL_MT5_DL3_r",label=NULL,value=NA)),
                            column(width=2,
                                   h4("Left Metatarsals"),
                                   numericInput("LL_MT1_DL_l","1st Diaphyseal Length",value=NA),
                                   numericInput("LL_MT1_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_MT1_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_MT2_DL_l","2nd Diaphyseal Length",value=NA),
                                   numericInput("LL_MT2_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_MT2_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_MT3_DL_l","3rd Diaphyseal Length",value=NA),
                                   numericInput("LL_MT3_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_MT3_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_MT4_DL_l","4th Diaphyseal Length",value=NA),
                                   numericInput("LL_MT4_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_MT4_DL3_l",label=NULL,value=NA),
                                   numericInput("LL_MT5_DL_l","5th Diaphyseal Length",value=NA),
                                   numericInput("LL_MT5_DL2_l",label=NULL,value=NA),
                                   numericInput("LL_MT5_DL3_l",label=NULL,value=NA))),
                   #Other:Vertebrea, ribs####
                   tabPanel("Other",
                            selectInput("oHelp","Help",c("Atlas:Maximum neural arch length"="At_NAL","Axis:Maximum neural arch length"="Ax_NAL","1st Rib:Maximum length"="R1_L")),
                            h4(textOutput("ohelp")),
                            h4("----------------------------------------------------------------------------------------------------------------------------------"),
                            column(width=4,
                                   h4("Vertebrae"),
                                   numericInput("O_At_NAL","Atlas maximum neural arch length",value=NA),
                                   numericInput("O_At_NAL2",label=NULL,value=NA),
                                   numericInput("O_At_NAL3",label=NULL,value=NA),
                                   numericInput("O_Ax_NAL","Axis maximum neural arch length",value=NA),
                                   numericInput("O_Ax_NAL2",label=NULL,value=NA),
                                   numericInput("O_Ax_NAL3",label=NULL,value=NA)),
                            column(width=4,
                                   h4("1st Rib"),
                                   numericInput("O_R1_L_r","Right Maximum Length",value=NA),
                                   numericInput("O_R1_L2_r",label=NULL,value=NA),
                                   numericInput("O_R1_L3_r",label=NULL,value=NA),
                                   numericInput("O_R1_L_l","Left Maximum Length",value=NA),
                                   numericInput("O_R1_L2_l",label=NULL,value=NA),
                                   numericInput("O_R1_L3_l",label=NULL,value=NA))
                            ),
                   
                   tabPanel("write",
                            textInput("dir","Data Folder",value="../../data/"),
                            column(width=3,
                                   checkboxGroupInput("Equipment","Please tick all available equipment",choices=c("Digital sliding calipers","Analog sliding calipers","Spreading calipers","Osteometric board","Tape","Mandibulometer","Craniophore","Coordinate calipers","digitizer tablet","Other")),
                                   conditionalPanel("input.Equipment.indexOf('Other') >= 0 ",
                                                    textInput("equipment2","Specify other",value=NA))
                                   
                            ),
                            column(width=3,
                                   h3("Population Info"),
                                   textInput("POPID","Population ID",value="NA"),
                                   textInput("POPName","Population name",value="NA"),
                                   textInput("Person1","Investigator",value="NA"),
                                   actionButton("Create","Create new file"),
                                   h4(textOutput("PMessage"))
                            ),
                            column(width=3,
                                   h3("Individual Info"),
                                   textInput("ID","Individual ID",value="NA"),
                                   textInput("Person2","Investigator intials",value="NA"),
                                   actionButton("Append","Add individual"),
                                   h4(textOutput("IMessage"))
                            ),
                            column(width=3,
                                   h3("Compatability check"),
                                   actionButton("Compat","Check file"),
                                   h4(textOutput("ComMessage"))
                            )
                   )
                   ))