library(shiny);library(markdown)

shinyUI(navbarPage("PaleoPath",
                   tabPanel("Custom Lesions",
                            tableOutput("customcheck"),
                            actionButton("Add","Add")
                            ),
                   tabPanel("Skull",
                            titlePanel("Specific abnormalities effecting the cranium or mandible"),
                            sidebarPanel(width=4,
                                   h4("Shape abnormalities"),
                                   checkboxGroupInput("Shape_Skull",label=NULL,c("Abnormally small circumference (Microscephly)"="SK_S01", "Abnormally large/wide cranium (Macrocephly)"="SK_S02", "Anterior Posterior elongation (Scaphocephaly)"="SK_S03", "Superior-Inferior elongation (Oxycephaly)"="SK_S04", "Flattening of the posterior skull(Brachycephaly)"="SK_S05", "Asymmetrical distortion(Plagiocephaly)"="SK_S06", "Anteriorly Pointed forehead (Trigonocephaly)"="SK_S07", "Asymmetry of the cranial base"="SK_S08", "Supernummery bones/sutural ossicles"="SK_S09", "Unfused Metopic Suture"="SK_S10", "Deviation from midline of nasal septum"="SK_S11", "Cleft palate"="SK_S12", "Suprainion depression"="SK_S13", "Absence/ complete closure of the external auditory meatus"="SK_S14")),
                                   h4("Abnormal bone loss"),
                                   checkboxGroupInput("Loss_Skull",label=NULL,c("Ectocranial porosis: of the Parietal/Orbit/ Occipital Squama /Frontal Squama/ Zygomatic"="SK_L01", "Supraorbital frontal groove(s)"="SK_L02", "Erosion of Nasal apeture or spine"="SK_L03", "Periapical perforations in mandible or maxilla"="SK_L04", "Endocranial depressions in the neurocranium"="SK_L05", "Perforation(s) or resorption of the mastoid region"="SK_L06", "Thinning of parietal bone"="SK_L07", "Circular/ Oval concavity on lingual surface of the mandible inferior to the mylohyoid line"="SK_L08", "Enlarged parietal foramina"="SK_L09", "Perforation of tympanic plate of temporal bone"="SK_L10")),
                                   h4("Abnormal bone growth"),
                                   checkboxGroupInput("Formation_Skull",label=NULL,c("Roughly circlar raised area(s) of dense bone on ectocranial surface"="SK_F01", "Bone growth at the External occipital protuberance"="SK_F02", "Bone growth in or around the external auditory meatus"="SK_F03", "Elongation of the styloid process"="SK_F04", "Rounded bone growth(s) along the lingual border of the mandible"="SK_F05", "Irregular thick bone growth(s) on endocranial surface vault"="SK_F06")),
                                   h4("Complex lesion"),
                                   checkboxGroupInput("Complex_Skull",label=NULL,c("Tempro-mandibular joint porocity/erosion/osteophytes"="SK_C01", "Extensive destruction of the outer table and diploe with radiating grooves and smooth raised nodules"="SK_C02", "Area of disorganized/abnormal bone remodeling, With one or more of: resorptive lesions/patches of sclerotic bone/bone softening/cortical thickening/prominent menigeal grooves/gross enlargement/increased weight, thickness or density/general deformity"="SK_C03","Lesion(s) displaying erosion, remodelling and scarring"="SK_C04"))),
                            mainPanel(width=8,
                                   h3("Details"),
                                   h5("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                                   actionButton("SkullUI","Enter details."),
                                   uiOutput("Skull_UI"),
                                   tableOutput("SKTable")
                                  )
                            
                            ),
                   tabPanel("Vertebrae",
                            titlePanel("Specific pathologies effecting the cervical,thorasic, lumbar or sacral vertebrae"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab "), 
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Vert",label=NULL,c("Abnormal  anterior posterior curvature (when vertebrae are in approximate anatomical position)"="V_S01 ", "Abnormal  lateral curvature (when vertebrae are in approximate anatomical position)"="V_S02",  "Malformed/ cleft centra"="V_S03", "Final lumbar vertebra partially or completely fused to the sacrum or displays features of the sacral vertebrae (Sacralisation)"="V_S04", "1st Sacral vertebra displays features of the lumbar vertebrae (Lumbarisation)"="V_S05", "Incomplete closure of sacral neural arch"="V_S06", "Incomplete closure of  lumbar neural arch"="V_S07","Incomplete closure of thoracic or cervical neural arch"="V_S08", "Separation of vertebral  body from the posterior portion of the neural arch"="V_S09","Supernummery vertebrae"="V_S10")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Vert",label=NULL,c("Severe erosive degradation/Cavitation of the vertebral body with little or no effect on the posterior vertebral elements"="V_L01", "Loss of body height"="V_L02", "Circular and/linear depressed lesion(s) in centra endplate"="V_L03", "Large scooped out lesions(s) on left anterior lateral  surface of the vertebral body "="V_L04", "Erosion of the odontoid process"="V_L05")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Vert",label=NULL,c("Rounded or radiating fingerlike bony projections (osteophytes) from the rim of the vertebral body"="V_F01", "Fusion of rib(s) to vertebra(e)"="V_F02", "Fusion of 2 vertebrae (not L5 and S1)"="V_F03", "Fusion of 3 or more vertebrae"="V_F04")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Vert",label=NULL,c("At least 2 of: Osteophytes on the rim of the vertebral body/irregular margins of the articular facets/ Surface porosity or eburnation of articular facets or odontoid process "="V_C01","Pitting on the superior surface of the vertebral bodies and marginal osteophyte(s)"="V_C02","Bridging of L5 and S1 with unusually large asymmetric inferior articular facets and fissures below the superior articular facet, possibly with callus formation"="V_C03"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("VertUI","Enter details."),
                                      uiOutput("Vert_UI"),
                                      tableOutput("VTable")
                            )
                   ),
                   tabPanel("Pelvis",
                            titlePanel("Specific pathologies effecting the os coxa and the sacroillac joint"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Pelvis",label=NULL,c("Acetabular ossicles"="P_S01", "Wide gap between pubic symphyses when pelvis is articulated"="P_S02")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Pelvis",label=NULL,c("Enlarged nutrient foramina"="P_L01", "A concavity or perforation on the inner surface of the illium/Illiac fossa"="P_L02", "Circular or linear depression(s) on the dorsal surface of the pubic symphyses"="P_L03")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Pelvis",label=NULL,c("Accessory sacral facets adjacent to the auricular surface"="P_F01", "Fusion of the sacroiliac joint"="P_F02", "Spike-like projections/spur/ridges/irregular ossification on the iliac crest/Ishial crest, tuberosity or spine/the margin of the obturator foramen"="P_F03", "Bridging of the cotyloid (acetabular) notch"="P_F04", "Long bony projection from the superior region of the ishial tuberocity"="P_F05")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Pelvis",label=NULL,c("Flattening of the superior rim of the acetabulum creating a 2-3cm long eroded area with exposed trabeculae or flattened depression"="P_C01", "Destruction of the acetabulum with surrounding reactive bone growth"="P_C02"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("PelvisUI","Enter details."),
                                      uiOutput("Pelvis_UI"),
                                      tableOutput("PTable")
                            )
                   ),
                   tabPanel("Shoulder",
                            titlePanel("Specific pathologies effecting the scapula or clavicle"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_shoulder",label=NULL,c("Separated acromion process"="SH_S01")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Shoulder",label=NULL,c("Irregularly shaped crater, groove, depression or pit in the anterior surface of the clavicle"="SH_L01")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Shoulder",label=NULL,c("Raised plateau like bony extension on the superior edge of the lateral end of the clavicle"="SH_F01", "Raised circular plateau of bone on the coracoid process"="SH_F02")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Shoulder",label=NULL,c("Raised sharp margins and pitting on the articular surface of the glenoid fossa"="SH_C01", "Flattening or extension of the glenoid fossa accompanied by erosion or pitting"="SH_C02","Pitting on the insertion of rotator cuff muscle and new bone around the insertion or alteration in the contour of the insertion"="SH_C03","Eburnation on the undersurface of the acromion"="SH_C04"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("ShoulderUI","Enter details."),
                                      uiOutput("Shoulder_UI"),
                                      tableOutput("SHTable")
                            )
                   ),
                   tabPanel("Thorax",
                            titlePanel("Specific pathologies effecting the ribs or sternum"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Thorax",label=NULL,c("Straightening of ribs, producing shepherd's crook appearance"="T_S01", "Bifid or bicipital(two headed) rib"="T_S02", "Accessory/supernummery ribs"="T_S03")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Thorax",label=NULL,c("Oval or circular defect in Sternum"="T_L01")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Thorax",label=NULL,c("Raised irregular bony growth on rib around vertebral articulation"="T_F01", "Enlarged and thickened periosteal bone on cortical surfaces of rib, particularly at ends, producing clubbed appearance"="T_F02")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Thorax",label=NULL,c())),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("ThoraxUI","Enter details."),
                                      uiOutput("Thorax_UI"),
                                      tableOutput("TTable")
                            )
                   ),
                   tabPanel("Arm",
                            titlePanel("Specific pathologies effecting the humerus, ulna or radius"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Arm",label=NULL,c("Supernumery bones of the elbow"="A_S01")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Arm",label=NULL,c("A Porous groove on the upper humeral shaft"="A_L01", "Round/oval perforation in the olecranon fossa"="A_L02", "Erosion of the radial styloid process"="A_L03")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Arm",label=NULL,c("Small roughly triangular hook-shaped bone spur 5-7cm above the medial epicondyle"="A_F01" , "Thickened line(s) extending across the diaphysis/metaphysis of the Humerus, Ulna or Radius"="A_F02", "Area of new bone growth on the outer cortex, with defined raise margins, pitting and striations, that is discolored compared to the underlying bone and has a tree-bark appearance"="A_F03","Smooth (healed) bone growth attached to the outer cortex which appears to sit on top of the underlying bone"="A_F04")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Arm",label=NULL,c("On Distal Humerus at last 2 of:Osteophytes along the articular surface, Mushrooming of the medial margin, extension into the olecranon fossa, Eburnation, Pitting, distortion of the articular surface"="A_C01", "Pitting within and Spike-like projections/spur/ridges/irregular ossification along the radial tuberocity"="A_C02","Margin osteophytes and areas of pitting or eburnation on the radial head"="A_C03", "Margin osteophytes and areas of pitting or eburnation on the trochlea notch/olecranon and/or coronoid process"="A_C04","Eburnation on the superior pole of head of humerus"="A_C05"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("ArmUI","Enter details."),
                                      uiOutput("Arm_UI"),
                                      tableOutput("ATable")
                            )
                   ),
                   tabPanel("Hand",
                            titlePanel("Specific pathologies effecting the hand"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Hand",label=NULL,c("Fusion of the proximal interphalangeal joint, resulting in a swan-neck deformity"="H_S01","Acessory/Supernummery bones"="H_S02")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Hand",label=NULL,c("Increased nutrient foramen in phalanx"="H_L01","Symmetrical erosion of metacarpophalangeal or proximal interphalangeal joint(s)"="H_L02")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Hand",label=NULL,c()),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Hand",label=NULL,c("Tufting and resorption of distal phalanges"="H_C01","Eburnation in any hand joint"="H_C02"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("HandUI","Enter details."),
                                      uiOutput("Hand_UI"),
                                      tableOutput("HTable")
                            )
                   ),
                   tabPanel("Leg",
                            titlePanel("Specific pathologies effecting the femur,patella,tibia or fibula"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Leg",label=NULL,c("Narrowed and elongated lateral condyle of femur"="L_S01", "Deep trochlear fossa"="L_S02", "Wide intercondylar fossa"="L_S03","Large raised and widely spaced lateral articular facet"="L_S04", "Small raised widely spaced medial articular facet"="L_S05","Bowing of the femur"="L_S06", "Bowing of the Tibia"="L_S07","Elongated sharpened tibial spines"="L_S08","Fusion of the Tibia and femur"="L_S09","Patella appears to have a large notch taken out of the superolateral corner"="L_S10","Small notch or depression on the superolateral or superomedial corner of the patella"="L_S11")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Leg",label=NULL,c("Large Pit/depression superior to the fovea capitis"="L_L01", "Scooped out lesion in medial condyle of femur"="L_L02", "Depression along the margin of the distal articular surface of the femur"="L_L03","Porous/sieve-like depression in the femoral neck"="L_L04",">2cm defect/ abnormality superior to the medial condyle"="L_L05", "Elongated groove/shallow depression inferior to the lesser trochanter"="L_L06","Break in the continuity of the straight line forming the anterior margin of the distal tibia, extension of the articular surface over this line"="L_L07")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Leg",label=NULL,c("Irregular raised area(s)/roughened attachments site/ bony spurs/ whisker like projection on the greater trochanter,lesser trochanter, trochanteric fossa and/or linea aspera"="L_F01","raised plaque-like area/extension of articular surface of the femoral head"="L_F02" ,"Exuberant bone formation on the femoral shaft"="L_F03", "Thickened line(s) extending across the diaphysis/metaphysis of the femur, Tibia or fibula"="L_F04", "Extensive/ exuberant  new bone formation  on the distal femur ,proximal tibia (and patella) coupled with a misalignment of the femur and tibia"="L_F05","Sheave/ envelope of disorganized new bone formation on shaft of femur/ tibia or fibula"="L_F06","Area of new bone growth on the outer cortex, with defined raise margins, pitting and striations, that is discolored compared to the underlying bone and has a tree-bark appearance"="L_F07","Smooth (healed) bone growth attached to the outer cortex which appears to sit on top of the underlying bone"="L_F08", "Irregular raise margins and/or raised islands of bone on the articular surface  of the tibial plateau"="L_F09","Rounded, smooth or irregular bony projection(s) from the tibial shaft running roughly perpendicular to the long axis"="L_F10","Bone spurs emanating from the tibial tuberocity"="L_F11","Elongation and projection of the inferior border of the patella"="L_F12","Bone spur on the lateral to midline articular rim of the distal tibia"="L_F13")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Leg",label=NULL,c("Marginal osteophytes, mushrooming, eburnation and/or pitting on the femoral head"="L_C01","Marginal osteophytes,osteophytes on the articular surface, eburnation and/or porosity on distal end of the femur"="L_C02", "Sheave/ envelope of disorganized new bone formation on shaft of femur/ tibia or fibula with large hole/depression(s) which may contain a isolated fragment of bone"="L_C03","On the Patella atleast 2 of :Raise rim around articular surface, surface osteophytes, eburnation, surface porosity and pitting, grooved articular surface"="L_C04"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("LegUI","Enter details."),
                                      uiOutput("Leg_UI"),
                                      tableOutput("LTable")
                            )
                   ),
                   tabPanel("Foot",
                            titlePanel("Specific pathologies effecting the Foot"),
                            em("nb If recording multiple anomalies select all before completing the details. If your abnormality is not on the list or you wish to enter more information use the custom lesion tab"),
                            sidebarPanel(width=4,
                                         h4("Shape abnormalities"),
                                         checkboxGroupInput("Shape_Foot",label=NULL,c("Accessory/supernummery bones"="F_S01","Malformation of the talus and medial rotation of the clacaneus leading to medial rotation of the foot so that the outside of the foot becomes the walking surface"="F_S02","Fusion of the calcaneous and talus"="F_S03","Fusion of the Tibia and Talus (and calcaneous)"="F_S04","Fusion of interphalangeal joints"="F_S05","Fusion of  phalangeal metatarsal joints"="F_S06","Fusion of intertarsal joint(s)"="F_S07")),
                                         h4("Abnormal bone loss"),
                                         checkboxGroupInput("Loss_Foot",label=NULL,c("Destruction of metatarsal and phalanges producing penciled cupped and pegged shapes with destruction beginning distally"="F_L01","Enlarged nutrient foramen"="F_L02","Symmetrical erosion of metatarsophalangeal or proximal interphalangeal joint(s)"="F_L03","Asymetric erosion of metatarsophalangeal or interphalangeal joint(s)"="F_L04")),
                                         h4("Abnormal bone growth"),
                                         checkboxGroupInput("Formation_Foot",label=NULL,c("Bone spur(s) on the superior posterior portion of the calcaneal tuber"="F_F01","Bone spur(s) on the inferor calcaneal tuber"="F_F02","Bone spur on medial aspect of the talar neck"="F_F03")),
                                         h4("Complex lesion"),
                                         checkboxGroupInput("Complex_Foot",label=NULL,c("Severe loss of bone across multiple foot bones accompanied by deformity bending the forefoot towards to hind foot creating a very high arch"="F_C01","Tufting and resorption of distal phalanges"="F_C02"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("FootUI","Enter details."),
                                      uiOutput("Foot_UI"),
                                      tableOutput("FTable"),
                                      h1(br()),
                                      h1(br())
                            )
                   ),
                   tabPanel("Systemic",
                            titlePanel("Specific pathologies effecting the whole skeleton"),
                            em("nb this tab is designed to record pathologies that effect the whole or large parts of the skeleton, where it is problematic or inapproprate to record lesions/abnormalities individually.systemic conditions that effect multiple element but produce lesions or abnormalities that are separatable should be recorded as a series of indivdual lesions using the approprate tabs."),
                            sidebarPanel(width=4,
                                         checkboxGroupInput("Systemic","Systemic conditions",c("Dwarfism"="SY_01", "Gigantism"="SY_02"))),
                            mainPanel(width=8,
                                      h3("Details"),
                                      actionButton("SystemicUI","Enter details."),
                                      uiOutput("Systemic_UI"),
                                      tableOutput("SYTable")
                                      )),
                   tabPanel("Write",
                            sidebarPanel(width=3,uiOutput("Photo")
                                         #tableOutput("Phototable")
                                         ),
                            mainPanel(textInput("dir","Data Folder",value="../../data/"),
                                      tableOutput("ResultsTable"),
                                      column(width=4,
                                             h3("Population Info"),
                                             textInput("POPID","Population ID",value="NA"),
                                             textInput("POPName","Population name",value="NA"),
                                             textInput("Person1","Investigator",value="NA"),
                                             actionButton("Create","Create new file"),
                                             h4(textOutput("PMessage"))
                                      ),
                                      column(width=4,
                                             h3("Individual Info"),
                                             textInput("ID","Individual ID",value="NA"),
                                             textInput("Person2","Investigator intials",value="NA"),
                                             actionButton("Append","Add individual"),
                                             h4(textOutput("IMessage"))
                                      ),
                                      column(width=4,
                                             h3("Compatability check"),
                                             actionButton("Compat","Check file"),
                                             h4(textOutput("ComMessage"))
                                      )))))