SKFusion<-c("O_LSM","O_rICP","O_lICP","O_rIOA","O_lIOA","SOS","rT_PT-PS","lT_PT-PS","rT_PM-ST","lT_PM-ST","S_rLW-B","S_lLW-B","S_Pre-Pos","S_rP-GW",
            "S_lP-GW","S_rGW-B","S_lGW-B","SC-E","F_MS","E_CG-C-L","E-V","V_VG","M_S","H_rGH-B","H_lGH-B","AF","SF","MF","SF","PF","MtF")
SKInvent<-c("O_PS","O_rPL","O_lPL","O_PB","rT_PS","lT_PS","rT_PT","lT_PT","rT_PP","lT_PP","rT_FH","lT_FH","rT_MP","lT_MP","S_Pre","S_Pos","S_rGW","S_lGW","S_rLW","S_lLW","S_DS","S_FS",
            "rP","lP","rF","lF","rN","lN","E_rL","E_lL","E_CP","rINC","lINC","rL","lL","V","rZ","lZ","rM","lM","rP","lP","M_rHM","M_lHM","H_B","H_rGH","H_lGH")

VInvent<-c("C1_rA","C1_lA","C1_AA","C2_D","C2_C","C2_rA","C2_lA","C3_C","C4_C","C5_C","C6_C","C7_C","C3_rA","C4_rA","C5_rA","C6_rA","C7_rA","C3_lA","C4_lA","C5_lA","C6_lA","C7_lA",
           "T1_C","T2_C","T3_C","T4_C","T5_C","T6_C","T7_C","T8_C","T9_C","T10_C","T11_C","T12_C",
           "T1_rA","T2_rA","T3_rA","T4_rA","T5_rA","T6_rA","T7_rA","T8_rA","T9_rA","T10_rA","T11_rA","T12_rA","T1_lA","T2_lA","T3_lA","T4_lA","T5_lA","T6_lA","T7_lA","T8_lA","T9_lA","T10_lA","T11_lA","T12_lA",
           "L1_C","L2_C","L3_C","L4_C","L5_C","L1_rA","L2_rA","L3_rA","L4_rA","L5_rA","L1_lA","L2_lA","L3_lA","L4_lA","L5_lA")
VFusion<-c("C1_PS","C1_rA-AA","C1_lA-AA","C2_DCJ","C2_rDNJ","C2_lDNJ","C2_rNCJ","C2_lNCJ","C2_PS","C2_IAR","C2_OT","C2_rTPE","C2_lTPE","C2_rSPE","C2_lSPE",
           "C3_PS","C4_PS","C5_PS","C6_PS","C7_PS","C3_rNCJ","C4_rNCJ","C5_rNCJ","C6_rNCJ","C7_rNCJ","C3_lNCJ","C4_lNCJ","C5_lNCJ","C6_lNCJ","C7_lNCJ","C3_SAR","C4_SAR","C5_SAR","C6_SAR","C7_SAR","C3_IAR","C4_IAR","C5_IAR","C6_IAR","C7_IAR","C3_rCPE","C4_rCPE","C5_rCPE","C6_rCPE","C7_rCPE","C3_lCPE","C4_lCPE","C5_lCPE","C6_lCPE","C7_lCPE","C3_rSPE","C4_rSPE","C5_rSPE","C6_rSPE","C7_rSPE","C3_lSPE","C4_lSPE","C5_lSPE","C6_lSPE","C7_lSPE",
           "T1_PS","T2_PS","T3_PS","T4_PS","T5_PS","T6_PS","T7_PS","T8_PS","T9_PS","T10_PS","T11_PS","T12_PS","T1_rNCJ","T2_rNCJ","T3_rNCJ","T4_rNCJ","T5_rNCJ","T6_rNCJ","T7_rNCJ","T8_rNCJ","T9_rNCJ","T10_rNCJ","T11_rNCJ","T12_rNCJ","T1_lNCJ","T2_lNCJ","T3_lNCJ","T4_lNCJ","T5_lNCJ","T6_lNCJ","T7_lNCJ","T8_lNCJ","T9_lNCJ","T10_lNCJ","T11_lNCJ","T12_lNCJ","T1_SAR","T2_SAR","T3_SAR","T4_SAR","T5_SAR","T6_SAR","T7_SAR","T8_SAR","T9_SAR","T10_SAR","T11_SAR","T12_SAR",
           "T1_IAR","T2_IAR","T3_IAR","T4_IAR","T5_IAR","T6_IAR","T7_IAR","T8_IAR","T9_IAR","T10_IAR","T11_IAR","T12_IAR","T1_rTPE","T2_rTPE","T3_rTPE","T4_rTPE","T5_rTPE","T6_rTPE","T7_rTPE","T8_rTPE","T9_rTPE","T10_rTPE","T11_rTPE","T12_rTPE","T1_lTPE","T2_lTPE","T3_lTPE","T4_lTPE","T5_lTPE","T6_lTPE","T7_lTPE","T8_lTPE","T9_lTPE","T10_lTPE","T11_lTPE","T12_lTPE","T1_SPE","T2_SPE","T3_SPE","T4_SPE","T5_SPE","T6_SPE","T7_SPE","T8_SPE","T9_SPE","T10_SPE","T11_SPE","T12_SPE",
           "L1_PS","L2_PS","L3_PS","L4_PS","L5_PS","L1_rNCJ","L2_rNCJ","L3_rNCJ","L4_rNCJ","L5_rNCJ","L1_lNCJ","L2_lNCJ","L3_lNCJ","L4_lNCJ","L5_lNCJ","L1_SAR","L2_SAR","L3_SAR","L4_SAR","L5_SAR","L1_IAR","L2_IAR","L3_IAR","L4_IAR","L5_IAR","L1_rLPE","L2_rLPE","L3_rLPE","L4_rLPE","L1_lLPE","L2_lLPE","L3_lLPE","L4_lLPE","L1_SPE","L2_SPE","L3_SPE","L4_SPE","L5_SPE")