library(shiny);library(markdown)

shinyUI(navbarPage("Juvenille Inventory",
                   tabPanel("Cranial",
                            column(width=4,h3("Inventory"),
                                   textOutput("SKIScore"),
                                   column(width=6,h4("Present"),
                                   checkboxGroupInput("SKPresent",label=NULL,
                                                      choices=list("Pars Squama (occipital)"="O_PS","Right Pars Lateralis (occipital)"="O_rPL","Left Pars Lateralis (occipital)"="O_lPL","Pars Basilaris (occipital)"="O_PB",
                                                                   "Right Pars squama (temporal)"="rT_PS","Left Pars squama (temporal)"="lT_PS","Right Pars Tympani (temporal)"="rT_PT","Left Pars Tympani (temporal)"="lT_PT","Right Pars Petrosa (temporal)"="rT_PP","Left Pars Petrosa (temporal)"="lT_PP","Right formen of Huscheke (temporal)"="rT_FH","Left formen of Huscheke (temporal)"="lT_FH","Right mastoid process (temporal)"="rT_MP","Left mastoid process (temporal)"="lT_MP",
                                                                   "Presphenoid (sphenoid)"="S_Pre","Postsphenoid (sphenoid)"="S_Pos","Right greater wing (sphenoid)"="S_rGW","Left greater wing (sphenoid)"="S_lGW","Right lesser wing (sphenoid)"="S_rLW","Left lesser wing (sphenoid)"="S_lLW","Dorseum sellae (sphenoid)"="S_DS","Foramen spinosum (sphenoid)"="S_FS",
                                                                   "Right Parietal"="rP","Left Parietal"="lP","Right Frontal"="rF","Left Frontal"="lF","Right Nasal"="rN","Left Nasal"="lN",
                                                                   "Right labyrinth (ethmoid)"="E_rL","Left labyrinth (ethmoid)"="E_lL","Ossified Cribiform plate (ethmoid)"="E_CP",
                                                                   "Right Inferior Nasal Concha"="rINC","Left Inferior Nasal Concha"="lINC","Right Lacrimal"="rL","Left Lacrimal"="lL","Vomer"="V","Right Zygomatic"="rZ","Left Zygomatic"="lZ","Right  Maxilla"="rM","Left Maxilla"="lM","Right Palatine"="rP","Left Palatine"="lP",
                                                                   "Right Hemi-mandible"="M_rHM","Left Hemi-mandible"="M_lHM","Body (hyoid)"="H_B","Right Greater horn (hyoid)"="H_rGH","Left Greater horn (hyoid)"="H_lGH"))),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("SKComplete",label=NULL,
                                                             choices=list("Pars Squama (occipital)"="O_PS","Right Pars Lateralis (occipital)"="O_rPL","Left Pars Lateralis (occipital)"="O_lPL","Pars Basilaris (occipital)"="O_PB",
                                                                          "Right Pars squama (temporal)"="rT_PS","Left Pars squama (temporal)"="lT_PS","Right Pars Tympani (temporal)"="rT_PT","Left Pars Tympani (temporal)"="lT_PT","Right Pars Petrosa (temporal)"="rT_PP","Left Pars Petrosa (temporal)"="lT_PP","Right formen of Huscheke (temporal)"="rT_FH","Left formen of Huscheke (temporal)"="lT_FH","Right mastoid process (temporal)"="rT_MP","Left mastoid process (temporal)"="lT_MP",
                                                                          "Presphenoid (sphenoid)"="S_Pre","Postsphenoid (sphenoid)"="S_Pos","Right greater wing (sphenoid)"="S_rGW","Left greater wing (sphenoid)"="S_lGW","Right lesser wing (sphenoid)"="S_rLW","Left lesser wing (sphenoid)"="S_lLW","Dorseum sellae (sphenoid)"="S_DS","Foramen spinosum (sphenoid)"="S_FS",
                                                                          "Right Parietal"="rP","Left Parietal"="lP","Right Frontal"="rF","Left Frontal"="lF","Right Nasal"="rN","Left Nasal"="lN",
                                                                          "Right labyrinth (ethmoid)"="E_rL","Left labyrinth (ethmoid)"="E_lL","Ossified Cribiform plate (ethmoid)"="E_CP",
                                                                          "Right Inferior Nasal Concha"="rINC","Left Inferior Nasal Concha"="lINC","Right Lacrimal"="rL","Left Lacrimal"="lL","Vomer"="V","Right Zygomatic"="rZ","Left Zygomatic"="lZ","Right  Maxilla"="rM","Left Maxilla"="lM","Right Palatine"="rP","Left Palatine"="lP",
                                                                          "Right Hemi-mandible"="M_rHM","Left Hemi-mandible"="M_lHM","Body (hyoid)"="H_B","Right Greater horn (hyoid)"="H_rGH","Left Greater horn (hyoid)"="H_lGH")))),
                            column(width=8,h3("Fusion"),
                                   textOutput("SKFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("SKOpen",label=NULL,choice=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                              "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                              "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                              "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("SKFusing",label=NULL,choice=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                               "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                               "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                               "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("SKFused",label=NULL,choice=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                              "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                              "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                              "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("SKOblit",label=NULL,choice=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                              "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                              "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                              "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))))),
                   tabPanel("Vertebrae",
                            column(width=4,h3("Inventory"),
                                   textOutput("VIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("VPresent",label=NULL,
                                                             choices=list("Right Arch(C1)"="C1_rA","Left Arch (C1)"="C1_lA","Anterior Arch(C1)"="C1_AA","Dens(C2)"="C2_D","Centrum(C2)"="C2_C","Right Arch(c2)"="C2_rA","Left Arch(C2)"="C2_lA",
                                                                          "Centrum (C3-7)[3]"="C3_C","Centrum (C3-7)[4]"="C4_C","Centrum (C3-7)[5]"="C5_C","Centrum (C3-7)[6]"="C6_C","Centrum (C3-7)[7]"="C7_C",
                                                                          "Right Arch(C3-7)[3]"="C3_rA","Right Arch(C3-7)[4]"="C4_rA","Right Arch(C3-7)[5]"="C5_rA","Right Arch(C3-7)[6]"="C6_rA","Right Arch(C3-7)[7]"="C7_rA","Left Arch(C3-7)[3]"="C3_lA","Left Arch(C3-7)[4]"="C4_lA","Left Arch(C3-7)[5]"="C5_lA","Left Arch(C3-7)[6]"="C6_lA","Left Arch(C3-7)[7]"="C7_lA",
                                                                          "Centrum (T1-12)[1]"="T1_C","Centrum (T1-12)[2]"="T2_C","Centrum (T1-12)[3]"="T3_C","Centrum (T1-12)[4]"="T4_C","Centrum (T1-12)[5]"="T5_C","Centrum (T1-12)[6]"="T6_C","Centrum (T1-12)[7]"="T7_C","Centrum (T1-12)[8]"="T8_C","Centrum (T1-12)[9]"="T9_C","Centrum (T1-12)[10]"="T10_C","Centrum (T1-12)[11]"="T11_C","Centrum (T1-12)[12]"="T12_C",
                                                                          "Right Arch(T1-12)[1]"="T1_rA","Right Arch(T1-12)[2]"="T2_rA","Right Arch(T1-12)[3]"="T3_rA","Right Arch(T1-12)[4]"="T4_rA","Right Arch(T1-12)[5]"="T5_rA","Right Arch(T1-12)[6]"="T6_rA","Right Arch(T1-12)[7]"="T7_rA","Right Arch(T1-12)[8]"="T8_rA","Right Arch(T1-12)[9]"="T9_rA","Right Arch(T1-12)[10]"="T10_rA","Right Arch(T1-12)[11]"="T11_rA","Right Arch(T1-12)[12]"="T12_rA",
                                                                          "Left Arch(T1-12)[1]"="T1_lA","Left Arch(T1-12)[2]"="T2_lA","Left Arch(T1-12)[3]"="T3_lA","Left Arch(T1-12)[4]"="T4_lA","Left Arch(T1-12)[5]"="T5_lA","Left Arch(T1-12)[6]"="T6_lA","Left Arch(T1-12)[7]"="T7_lA","Left Arch(T1-12)[8]"="T8_lA","Left Arch(T1-12)[9]"="T9_lA","Left Arch(T1-12)[10]"="T10_lA","Left Arch(T1-12)[11]"="T11_lA","Left Arch(T1-12)[12]"="T12_lA",
                                                                          "Centrum (L1-5)[1]"="L1_C","Centrum (L1-5)[2]"="L2_C","Centrum (L1-5)[3]"="L3_C","Centrum (L1-5)[4]"="L4_C","Centrum (L1-5)[5]"="L5_C",
                                                                          "Right Arch(L1-5)[1]"="L1_rA","Right Arch(L1-5)[2]"="L2_rA","Right Arch(L1-5)[3]"="L3_rA","Right Arch(L1-5)[4]"="L4_rA","Right Arch(L1-5)[5]"="L5_rA","Left Arch(L1-5)[1]"="L1_lA","Left Arch(L1-5)[2]"="L2_lA","Left Arch(L1-5)[3]"="L3_lA","Left Arch(L1-5)[4]"="L4_lA","Left Arch(L1-5)[5]"="L5_lA"))),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("VComplete",label=NULL,
                                                             choices=list("Right Arch(C1)"="C1_rA","Left Arch (C1)"="C1_lA","Anterior Arch(C1)"="C1_AA","Dens(C2)"="C2_D","Centrum(C2)"="C2_C","Right Arch(c2)"="C2_rA","Left Arch(C2)"="C2_lA",
                                                                          "Centrum (C3-7)[3]"="C3_C","Centrum (C3-7)[4]"="C4_C","Centrum (C3-7)[5]"="C5_C","Centrum (C3-7)[6]"="C6_C","Centrum (C3-7)[7]"="C7_C",
                                                                          "Right Arch(C3-7)[3]"="C3_rA","Right Arch(C3-7)[4]"="C4_rA","Right Arch(C3-7)[5]"="C5_rA","Right Arch(C3-7)[6]"="C6_rA","Right Arch(C3-7)[7]"="C7_rA","Left Arch(C3-7)[3]"="C3_lA","Left Arch(C3-7)[4]"="C4_lA","Left Arch(C3-7)[5]"="C5_lA","Left Arch(C3-7)[6]"="C6_lA","Left Arch(C3-7)[7]"="C7_lA",
                                                                          "Centrum (T1-12)[1]"="T1_C","Centrum (T1-12)[2]"="T2_C","Centrum (T1-12)[3]"="T3_C","Centrum (T1-12)[4]"="T4_C","Centrum (T1-12)[5]"="T5_C","Centrum (T1-12)[6]"="T6_C","Centrum (T1-12)[7]"="T7_C","Centrum (T1-12)[8]"="T8_C","Centrum (T1-12)[9]"="T9_C","Centrum (T1-12)[10]"="T10_C","Centrum (T1-12)[11]"="T11_C","Centrum (T1-12)[12]"="T12_C",
                                                                          "Right Arch(T1-12)[1]"="T1_rA","Right Arch(T1-12)[2]"="T2_rA","Right Arch(T1-12)[3]"="T3_rA","Right Arch(T1-12)[4]"="T4_rA","Right Arch(T1-12)[5]"="T5_rA","Right Arch(T1-12)[6]"="T6_rA","Right Arch(T1-12)[7]"="T7_rA","Right Arch(T1-12)[8]"="T8_rA","Right Arch(T1-12)[9]"="T9_rA","Right Arch(T1-12)[10]"="T10_rA","Right Arch(T1-12)[11]"="T11_rA","Right Arch(T1-12)[12]"="T12_rA",
                                                                          "Left Arch(T1-12)[1]"="T1_lA","Left Arch(T1-12)[2]"="T2_lA","Left Arch(T1-12)[3]"="T3_lA","Left Arch(T1-12)[4]"="T4_lA","Left Arch(T1-12)[5]"="T5_lA","Left Arch(T1-12)[6]"="T6_lA","Left Arch(T1-12)[7]"="T7_lA","Left Arch(T1-12)[8]"="T8_lA","Left Arch(T1-12)[9]"="T9_lA","Left Arch(T1-12)[10]"="T10_lA","Left Arch(T1-12)[11]"="T11_lA","Left Arch(T1-12)[12]"="T12_lA",
                                                                          "Centrum (L1-5)[1]"="L1_C","Centrum (L1-5)[2]"="L2_C","Centrum (L1-5)[3]"="L3_C","Centrum (L1-5)[4]"="L4_C","Centrum (L1-5)[5]"="L5_C",
                                                                          "Right Arch(L1-5)[1]"="L1_rA","Right Arch(L1-5)[2]"="L2_rA","Right Arch(L1-5)[3]"="L3_rA","Right Arch(L1-5)[4]"="L4_rA","Right Arch(L1-5)[5]"="L5_rA","Left Arch(L1-5)[1]"="L1_lA","Left Arch(L1-5)[2]"="L2_lA","Left Arch(L1-5)[3]"="L3_lA","Left Arch(L1-5)[4]"="L4_lA","Left Arch(L1-5)[5]"="L5_lA")))),
                            column(width=8,h3("Fusion"),
                                   textOutput("VFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("VOpen",label=NULL,choice=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("VFusing",label=NULL,choice=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("VFused",label=NULL,choice=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("VOblit",label=NULL,choice=list())))),
                   
                   tabPanel("Thorax",
                            column(width=4,h3("Inventory"),
                                   textOutput("TIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("TPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("TComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("TFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("TOpen",label=NULL,choice=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("TFusing",label=NULL,choice=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("TFused",label=NULL,choice=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("TOblit",label=NULL,choice=list())))),
                   tabPanel("Shoulder",
                            column(width=4,h3("Inventory"),
                                   textOutput("SHIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("SHPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("SHComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("SHFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("SHOpen",label=NULL,choice=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("SHFusing",label=NULL,choice=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("SHFused",label=NULL,choice=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("SHOblit",label=NULL,choice=list())))),
                   tabPanel("Upper Limb",
                            column(width=4,h3("Inventory"),
                                   textOutput("ULIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("ULPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("ULComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("ULFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("ULOpen",label=NULL,choice=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("ULFusing",label=NULL,choice=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("ULFused",label=NULL,choice=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("ULOblit",label=NULL,choice=list())))),
                   tabPanel("Pelvis",
                            column(width=4,h3("Inventory"),
                                   textOutput("PIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("PPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("PComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("PFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("POpen",label=NULL,choice=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("PFusing",label=NULL,choice=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("PFused",label=NULL,choice=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("POblit",label=NULL,choice=list())))),
                   tabPanel("Lower Limb",
                            column(width=4,h3("Inventory"),
                                   textOutput("LLIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("LLPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("LLComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("LLFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("LLOpen",label=NULL,choice=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("LLFusing",label=NULL,choice=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("LLFused",label=NULL,choice=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("LLOblit",label=NULL,choice=list())))),
                   tabPanel("Unidentified fragments",
                            fluidPage(h3("Unidentified Inventory"),
                                      textOutput("UScore"),
                                      column(width=4,
                                             numericInput("USkull","Skull",value=0,width='50%'),
                                             numericInput("ULimb","Limb Long bone",value=0,width='50%'),
                                             numericInput("UVert","Vertebrae",value=0,width='50%'),
                                             numericInput("UHandFoot","Hand/foot",value=0,width='50%')),
                                      column(width=4,
                                             numericInput("UClavScap","Clavicle/Scapula",value=0,width='50%'),
                                             numericInput("UOsCoxae","Os coxae",value=0,width='50%'),
                                             numericInput("UOther","Other fragments",value=0,width='50%')))),
                   tabPanel("Additional",
                            column(width=6,h3("Ordering and Siding"),
                                   #textOutput("O_S"),
                                   column(width=6,selectInput("CVOrder","Cervicle Vertebrae (3-7) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.CVOrder=='Partial'",textInput("CVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("TVOrder","Thorasic Vertebrae (1-12) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.TVOrder=='Partial'",textInput("TVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("LVOrder","Lumbar Vertebrae (1-5) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.LVOrder=='Partial'",textInput("LVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("ROrder","Ribs (3-10) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.ROrder=='Partial'",textInput("ROrder2","Describe partial ordering",value="NA")),
                                          selectInput("RSide","Ribs (1-12) siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.RSide=='Partial'",textInput("RSide2","Describe partial Siding",value="NA")),
                                          selectInput("MCOrder","Metacarpal ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.MCOrder=='Partial'",textInput("MCOrder2","Describe partial ordering",value="NA")),
                                          selectInput("MCSide","Metacarpal siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          h1(br()),
                                          h1(br())),
                                   column(width=6,conditionalPanel("input.MCSide=='Partial'",textInput("MCSide2","Describe partial Siding",value="NA")),
                                          selectInput("HPOrder","Hand phalanges ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.HPOrder=='Partial'",textInput("HPOrder2","Describe partial ordering",value="NA")),
                                          selectInput("HPSide","Hand halanges siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.HPSide=='Partial'",textInput("HPSide2","Describe partial Siding",value="NA")),
                                          selectInput("MTOrder","Metatarsal ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.MTOrder=='Partial'",textInput("MTOrder2","Describe partial ordering",value="NA")),
                                          selectInput("MTSide","Metatarsal siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.MTSide=='Partial'",textInput("MTSide2","Describe partial Siding",value="NA")),
                                          selectInput("FPOrder","Foot phalanges ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.FPOrder=='Partial'",textInput("FPOrder2","Describe partial ordering",value="NA")),
                                          selectInput("FPSide","Foot phalanges siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.FPSide=='Partial'",textInput("FPSide2","Describe partial Siding",value="NA")),
                                          h1(br()),
                                          h1(br()))
                            ),
                            column(width=6,h3("Photographic record"),
                                   h5("Please enter photographic reference number(s) or filepath(s)separate multiple entries with /"),
                                   column(width=6,textInput("Photo1","Full Skeleton",value="NA"),
                                          textInput("Photo2","Cranium Anterior",value='NA'),
                                          textInput("Photo3","Cranium Lateral",value='NA'),
                                          textInput("Photo4","Cranium Superior",value='NA'),
                                          textInput("Photo5","Cranium Basilar",value='NA'),
                                          textInput("Photo6","Skull Fragmented",value='NA'),
                                          textInput("Photo7","Mandible",value='NA'),
                                          textInput("Photo8","Hand",value='NA')),
                                   column(width=6,textInput("Photo9","Foot",value='NA'),
                                          textInput("Photo10","Arm",value='NA'),
                                          textInput("Photo11","Leg",value='NA'),
                                          textInput("Photo12","Pelvis",value='NA'),
                                          textInput("Photo13","Shoulder",value='NA'),
                                          textInput("Photo14","Thorax",value='NA'),
                                          textInput("Photo15","Vertebrae",value='NA'),
                                          textInput("Photo16","Unidentified Fragments",value='NA')))),
                   tabPanel("write",
                            textInput("dir","Data Folder",value="../../data/"),
                            column(width=4,
                                   h3("Population Info"),
                                   textInput("POPID","Population ID",value="NA"),
                                   textInput("POPName","Population name",value="NA"),
                                   textInput("Person1","Investigator",value="NA"),
                                   actionButton("Create","Create new file"),
                                   h4(textOutput("PMessage"))
                            ),
                            column(width=4,
                                   h3("Individual Info"),
                                   textInput("ID","Individual ID",value="NA"),
                                   textInput("Person2","Investigator intials",value="NA"),
                                   actionButton("Append","Add individual"),
                                   h4(textOutput("IMessage"))
                            ),
                            column(width=4,
                                   h3("Compatability check"),
                                   actionButton("Compat","Check file"),
                                   h4(textOutput("ComMessage"))
                            )
                   )
                   ))