library(shiny);library(markdown)

shinyUI(navbarPage("Juvenille Inventory",
                   tabPanel("Cranial",
                            column(width=4,h3("Inventory"),
                                   textOutput("SKIScore"),
                                   column(width=6,h4("Present"),
                                   checkboxGroupInput("SKPresent",label=NULL,
                                                      choices=list("Pars Squama (occipital)"="O_PS","Right Pars Lateralis (occipital)"="O_rPL","Left Pars Lateralis (occipital)"="O_lPL","Pars Basilaris (occipital)"="O_PB",
                                                                   "Right Pars squama (temporal)"="rT_PS","Left Pars squama (temporal)"="lT_PS","Right Pars Tympani (temporal)"="rT_PT","Left Pars Tympani (temporal)"="lT_PT","Right Pars Petrosa (temporal)"="rT_PP","Left Pars Petrosa (temporal)"="lT_PP","Right formen of Huscheke (temporal)"="rT_FH","Left formen of Huscheke (temporal)"="lT_FH","Right mastoid process (temporal)"="rT_MP","Left mastoid process (temporal)"="lT_MP",
                                                                   "Presphenoid (sphenoid)"="S_Pre","Postsphenoid (sphenoid)"="S_Pos","Right greater wing (sphenoid)"="S_rGW","Left greater wing (sphenoid)"="S_lGW","Right lesser wing (sphenoid)"="S_rLW","Left lesser wing (sphenoid)"="S_lLW","Dorseum sellae (sphenoid)"="S_DS","Foramen spinosum (sphenoid)"="S_FS",
                                                                   "Right Parietal"="rP","Left Parietal"="lP","Right Frontal"="rF","Left Frontal"="lF","Right Nasal"="rN","Left Nasal"="lN",
                                                                   "Right labyrinth (ethmoid)"="E_rL","Left labyrinth (ethmoid)"="E_lL","Ossified Cribiform plate (ethmoid)"="E_CP",
                                                                   "Right Inferior Nasal Concha"="rINC","Left Inferior Nasal Concha"="lINC","Right Lacrimal"="rL","Left Lacrimal"="lL","Vomer"="V","Right Zygomatic"="rZ","Left Zygomatic"="lZ","Right  Maxilla"="rM","Left Maxilla"="lM","Right Palatine"="rP","Left Palatine"="lP",
                                                                   "Right Hemi-mandible"="M_rHM","Left Hemi-mandible"="M_lHM","Body (hyoid)"="H_B","Right Greater horn (hyoid)"="H_rGH","Left Greater horn (hyoid)"="H_lGH"))),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("SKComplete",label=NULL,
                                                             choices=list("Pars Squama (occipital)"="O_PS","Right Pars Lateralis (occipital)"="O_rPL","Left Pars Lateralis (occipital)"="O_lPL","Pars Basilaris (occipital)"="O_PB",
                                                                          "Right Pars squama (temporal)"="rT_PS","Left Pars squama (temporal)"="lT_PS","Right Pars Tympani (temporal)"="rT_PT","Left Pars Tympani (temporal)"="lT_PT","Right Pars Petrosa (temporal)"="rT_PP","Left Pars Petrosa (temporal)"="lT_PP","Right formen of Huscheke (temporal)"="rT_FH","Left formen of Huscheke (temporal)"="lT_FH","Right mastoid process (temporal)"="rT_MP","Left mastoid process (temporal)"="lT_MP",
                                                                          "Presphenoid (sphenoid)"="S_Pre","Postsphenoid (sphenoid)"="S_Pos","Right greater wing (sphenoid)"="S_rGW","Left greater wing (sphenoid)"="S_lGW","Right lesser wing (sphenoid)"="S_rLW","Left lesser wing (sphenoid)"="S_lLW","Dorseum sellae (sphenoid)"="S_DS","Foramen spinosum (sphenoid)"="S_FS",
                                                                          "Right Parietal"="rP","Left Parietal"="lP","Right Frontal"="rF","Left Frontal"="lF","Right Nasal"="rN","Left Nasal"="lN",
                                                                          "Right labyrinth (ethmoid)"="E_rL","Left labyrinth (ethmoid)"="E_lL","Ossified Cribiform plate (ethmoid)"="E_CP",
                                                                          "Right Inferior Nasal Concha"="rINC","Left Inferior Nasal Concha"="lINC","Right Lacrimal"="rL","Left Lacrimal"="lL","Vomer"="V","Right Zygomatic"="rZ","Left Zygomatic"="lZ","Right  Maxilla"="rM","Left Maxilla"="lM","Right Palatine"="rP","Left Palatine"="lP",
                                                                          "Right Hemi-mandible"="M_rHM","Left Hemi-mandible"="M_lHM","Body (hyoid)"="H_B","Right Greater horn (hyoid)"="H_rGH","Left Greater horn (hyoid)"="H_lGH")))),
                            column(width=8,h3("Fusion"),
                                   textOutput("SKFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("SKOpen",label=NULL,choices=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                              "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                              "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                              "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("SKFusing",label=NULL,choices=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                               "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                               "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                               "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("SKFused",label=NULL,choices=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                              "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                              "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                              "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("SKOblit",label=NULL,choices=list("Lateral Sutura Mendosa (occipital)"="O_LSM","Right Intra-Occipitalis Posterior (occipital)"="O_rICP","left Intra-Occipitalis Posterior (occipital)"="O_lICP", "Right Intra-occipitalis Anterior (occipital)"="O_rIOA","Left Intra-occipitalis Anterior (occipital)"="O_lIOA","Spheno_Occipital Sychondrosis"="SOS",
                                                                                              "Right Pars Tympani and Pars Squama (temporal)"="rT_PT-PS","left Pars Tympani and Pars Squama (temporal)"="lT_PT-PS","Right Petromastoid and Squamotympanic (temporal)"="rT_PM-ST","Left Petromastoid and Squamotympanic (temporal)"="lT_PM-ST",
                                                                                              "Right lesser wing and body (sphenoid)"="S_rLW-B","Left lesser wing and body (sphenoid)"="S_lLW-B","Presphenoid and Postsphenoid (sphenoid)"="S_Pre-Pos","Right ptergoid and greater wing (sphenoid)"="S_rP-GW","left ptergoid and greater wing (sphenoid)"="S_lP-GW","Right greater wing and body(sphenoid)"="S_rGW-B","Left greater wing and body(sphenoid)"="S_lGW-B","Sphenoid conchae and ethmoid"="SC-E",
                                                                                              "Metopic Suture"="F_MS","Crista galli, Cribiform and labyrinth (ethmoid)"="E_CG-C-L","Ethmoid and Vomer"="E-V","Edges of vomerine groove (vomer)"="V_VG","Symphysis (Mandible)"="M_S","Right greater horn and body (hyoid)"="H_rGH-B","Left greater horn and body (hyoid)"="H_lGH-B","Anterior Fontanelle"="AF","Saggital Fontanelle"="SF","Mastoid fontanelle"="MF","Sphenoid Fontanelle"="SF","Posterior fontanelle"="PF","Metopic fontanelle"="MtF"))))),
                   tabPanel("Vertebrae",
                            column(width=4,h3("Inventory"),
                                   textOutput("VIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("VPresent",label=NULL,
                                                             choices=list("Right Arch(C1)"="C1_rA","Left Arch (C1)"="C1_lA","Anterior Arch(C1)"="C1_AA","Dens(C2)"="C2_D","Centrum(C2)"="C2_C","Right Arch(c2)"="C2_rA","Left Arch(C2)"="C2_lA",
                                                                          "Centrum (C3-7)[3]"="C3_C","[4]"="C4_C","[5]"="C5_C","[6]"="C6_C","[7]"="C7_C",
                                                                          "Right Arch(C3-7)[3]"="C3_rA","[4]"="C4_rA","[5]"="C5_rA","[6]"="C6_rA","[7]"="C7_rA","Left Arch(C3-7)[3]"="C3_lA","[4]"="C4_lA","[5]"="C5_lA","[6]"="C6_lA","[7]"="C7_lA",
                                                                          "Centrum (T1-12)[1]"="T1_C","[2]"="T2_C","[3]"="T3_C","[4]"="T4_C","[5]"="T5_C","[6]"="T6_C","[7]"="T7_C","[8]"="T8_C","[9]"="T9_C","[10]"="T10_C","[11]"="T11_C","[12]"="T12_C",
                                                                          "Right Arch(T1-12)[1]"="T1_rA","[2]"="T2_rA","[3]"="T3_rA","[4]"="T4_rA","[5]"="T5_rA","[6]"="T6_rA","[7]"="T7_rA","[8]"="T8_rA","[9]"="T9_rA","[10]"="T10_rA","[11]"="T11_rA","[12]"="T12_rA",
                                                                          "Left Arch(T1-12)[1]"="T1_lA","[2]"="T2_lA","[3]"="T3_lA","[4]"="T4_lA","[5]"="T5_lA","[6]"="T6_lA","[7]"="T7_lA","[8]"="T8_lA","[9]"="T9_lA","[10]"="T10_lA","[11]"="T11_lA","[12]"="T12_lA",
                                                                          "Centrum (L1-5)[1]"="L1_C","[2]"="L2_C","[3]"="L3_C","[4]"="L4_C","[5]"="L5_C",
                                                                          "Right Arch(L1-5)[1]"="L1_rA","[2]"="L2_rA","[3]"="L3_rA","[4]"="L4_rA","[5]"="L5_rA","Left Arch(L1-5)[1]"="L1_lA","[2]"="L2_lA","[3]"="L3_lA","[4]"="L4_lA","[5]"="L5_lA"))),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("VComplete",label=NULL,
                                                             choices=list("Right Arch(C1)"="C1_rA","Left Arch (C1)"="C1_lA","Anterior Arch(C1)"="C1_AA","Dens(C2)"="C2_D","Centrum(C2)"="C2_C","Right Arch(c2)"="C2_rA","Left Arch(C2)"="C2_lA",
                                                                          "Centrum (C3-7)[3]"="C3_C","[4]"="C4_C","[5]"="C5_C","[6]"="C6_C","[7]"="C7_C",
                                                                          "Right Arch(C3-7)[3]"="C3_rA","[4]"="C4_rA","[5]"="C5_rA","[6]"="C6_rA","[7]"="C7_rA","Left Arch(C3-7)[3]"="C3_lA","[4]"="C4_lA","[5]"="C5_lA","[6]"="C6_lA","[7]"="C7_lA",
                                                                          "Centrum (T1-12)[1]"="T1_C","[2]"="T2_C","[3]"="T3_C","[4]"="T4_C","[5]"="T5_C","[6]"="T6_C","[7]"="T7_C","[8]"="T8_C","[9]"="T9_C","[10]"="T10_C","[11]"="T11_C","[12]"="T12_C",
                                                                          "Right Arch(T1-12)[1]"="T1_rA","[2]"="T2_rA","[3]"="T3_rA","[4]"="T4_rA","[5]"="T5_rA","[6]"="T6_rA","[7]"="T7_rA","[8]"="T8_rA","[9]"="T9_rA","[10]"="T10_rA","[11]"="T11_rA","[12]"="T12_rA",
                                                                          "Left Arch(T1-12)[1]"="T1_lA","[2]"="T2_lA","[3]"="T3_lA","[4]"="T4_lA","[5]"="T5_lA","[6]"="T6_lA","[7]"="T7_lA","[8]"="T8_lA","[9]"="T9_lA","[10]"="T10_lA","[11]"="T11_lA","[12]"="T12_lA",
                                                                          "Centrum (L1-5)[1]"="L1_C","[2]"="L2_C","[3]"="L3_C","[4]"="L4_C","[5]"="L5_C",
                                                                          "Right Arch(L1-5)[1]"="L1_rA","[2]"="L2_rA","[3]"="L3_rA","[4]"="L4_rA","[5]"="L5_rA","Left Arch(L1-5)[1]"="L1_lA","[2]"="L2_lA","[3]"="L3_lA","[4]"="L4_lA","[5]"="L5_lA")))),
                            column(width=8,h3("Fusion/ Secondary centers"),
                                   textOutput("VFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("VOpen",label=NULL,choices=list("Posterior Synchondrosis (C1)"="C1_PS","Right arch to anterior Arch (C1)"="C1_rA-AA","Left arch to anterior arch (c1)"="C1_lA-AA",
                                                                                            "Dentocentral junction (C2)"="C2_DCJ","Right dentoneural junction (c2)"="C2_rDNJ","Left dentoneural junction (C2)"="C2_lDNJ","Right Neurocentral junction (C2)"="C2_rNCJ","Left Neurocentral junction (C2)"="C2_lNCJ","Posterior Synchondrosis (C2)"="C2_PS","Inferior Annular ring (C2)"="C2_IAR","Dens ossiculum terminale(C2)"="C2_OT","Right transverse process epiphyses (C2)"="C2_rTPE","Left transverse process epiphyses (C2)"="C2_lTPE","Right spinous process epiphyses (C2)"="C2_rSPE","Left Spinous process epiphyses (C2)"="C2_lSPE",
                                                                                            "Posterior Synchondrosis(C3-7)[3]"="C3_PS","[4]"="C4_PS","[5]"="C5_PS","[6]"="C6_PS","[7]"="C7_PS",
                                                                                            "Right Neurocentral junction(C3-7)[3]"="C3_rNCJ","[4]"="C4_rNCJ","[5]"="C5_rNCJ","[6]"="C6_rNCJ","[7]"="C7_rNCJ",
                                                                                            "Left Neurocentral junction(C3-7)[3]"="C3_lNCJ","[4]"="C4_lNCJ","[5]"="C5_lNCJ","[6]"="C6_lNCJ","[7]"="C7_lNCJ",
                                                                                            "Superior annular ring(C3-7)[3]"="C3_SAR","[4]"="C4_SAR","[5]"="C5_SAR","[6]"="C6_SAR","[7]"="C7_SAR",
                                                                                            "Inferior annular ring(C3-7)[3]"="C3_IAR","[4]"="C4_IAR","[5]"="C5_IAR","[6]"="C6_IAR","[7]"="C7_IAR",
                                                                                            "Right transverse process epiphyses(C3-7)[3]"="C3_rCPE","[4]"="C4_rCPE","[5]"="C5_rCPE","[6]"="C6_rCPE","[7]"="C7_rCPE",
                                                                                            "Left transverse process epiphyses(C3-7)[3]"="C3_lCPE","[4]"="C4_lCPE","[5]"="C5_lCPE","[6]"="C6_lCPE","[7]"="C7_lCPE",
                                                                                            "Right spinous process epiphyses(C3-7)[3]"="C3_rSPE","[4]"="C4_rSPE","[5]"="C5_rSPE","[6]"="C6_rSPE","[7]"="C7_rSPE",
                                                                                            "Left spinous process epiphyses(C3-7)[3]"="C3_lSPE","[4]"="C4_lSPE","[5]"="C5_lSPE","[6]"="C6_lSPE","[7]"="C7_lSPE",
                                                                                            "Posterior Synchondrosis(T1-12)[1]"="T1_PS","[2]"="T2_PS","[3]"="T3_PS","[4]"="T4_PS","[5]"="T5_PS","[6]"="T6_PS","[7]"="T7_PS","[8]"="T8_PS","[9]"="T9_PS","[10]"="T10_PS","[11]"="T11_PS","[12]"="T12_PS",
                                                                                            "Right Neurocentral junction(T1-12)[1]"="T1_rNCJ","[2]"="T2_rNCJ","[3]"="T3_rNCJ","[4]"="T4_rNCJ","[5]"="T5_rNCJ","[6]"="T6_rNCJ","[7]"="T7_rNCJ","[8]"="T8_rNCJ","[9]"="T9_rNCJ","[10]"="T10_rNCJ","[11]"="T11_rNCJ","[12]"="T12_rNCJ",
                                                                                            "Left Neurocentral junction(T1-12)[1]"="T1_lNCJ","[2]"="T2_lNCJ","[3]"="T3_lNCJ","[4]"="T4_lNCJ","[5]"="T5_lNCJ","[6]"="T6_lNCJ","[7]"="T7_lNCJ","[8]"="T8_lNCJ","[9]"="T9_lNCJ","[10]"="T10_lNCJ","[11]"="T11_lNCJ","[12]"="T12_lNCJ",
                                                                                            "Superior annular ring(T1-12)[1]"="T1_SAR","[2]"="T2_SAR","[3]"="T3_SAR","[4]"="T4_SAR","[5]"="T5_SAR","[6]"="T6_SAR","[7]"="T7_SAR","[8]"="T8_SAR","[9]"="T9_SAR","[10]"="T10_SAR","[11]"="T11_SAR","[12]"="T12_SAR",
                                                                                            "Inferior annular ring(T1-12)[1]"="T1_IAR","[2]"="T2_IAR","[3]"="T3_IAR","[4]"="T4_IAR","[5]"="T5_IAR","[6]"="T6_IAR","[7]"="T7_IAR","[8]"="T8_IAR","[9]"="T9_IAR","[10]"="T10_IAR","[11]"="T11_IAR","[12]"="T12_IAR",
                                                                                            "Right transverse process epiphyses(T1-12)[1]"="T1_rTPE","[2]"="T2_rTPE","[3]"="T3_rTPE","[4]"="T4_rTPE","[5]"="T5_rTPE","[6]"="T6_rTPE","[7]"="T7_rTPE","[8]"="T8_rTPE","[9]"="T9_rTPE","[10]"="T10_rTPE","[11]"="T11_rTPE","[12]"="T12_rTPE",
                                                                                            "Left transverse process epiphyses(T1-12)[1]"="T1_lTPE","[2]"="T2_lTPE","[3]"="T3_lTPE","[4]"="T4_lTPE","[5]"="T5_lTPE","[6]"="T6_lTPE","[7]"="T7_lTPE","[8]"="T8_lTPE","[9]"="T9_lTPE","[10]"="T10_lTPE","[11]"="T11_lTPE","[12]"="T12_lTPE",
                                                                                            "Spinous process epiphyses(T1-12)[1]"="T1_SPE","[2]"="T2_SPE","[3]"="T3_SPE","[4]"="T4_SPE","[5]"="T5_SPE","[6]"="T6_SPE","[7]"="T7_SPE","[8]"="T8_SPE","[9]"="T9_SPE","[10]"="T10_SPE","[11]"="T11_SPE","[12]"="T12_SPE",
                                                                                            "Posterior Synchondrosis(L1-5)[1]"="L1_PS","[2]"="L2_PS","[3]"="L3_PS","[4]"="L4_PS","[5]"="L5_PS",
                                                                                            "Right Neurocentral junction(L1-5)[1]"="L1_rNCJ","[2]"="L2_rNCJ","[3]"="L3_rNCJ","[4]"="L4_rNCJ","[5]"="L5_rNCJ",
                                                                                            "Left Neurocentral junction(L1-5)[1]"="L1_lNCJ","[2]"="L2_lNCJ","[3]"="L3_lNCJ","[4]"="L4_lNCJ","[5]"="L5_lNCJ",
                                                                                            "Superior annular ring(L1-5)[1]"="L1_SAR","[2]"="L2_SAR","[3]"="L3_SAR","[4]"="L4_SAR","[5]"="L5_SAR",
                                                                                            "Inferior annular ring(L1-5)[1]"="L1_IAR","[2]"="L2_IAR","[3]"="L3_IAR","[4]"="L4_IAR","[5]"="L5_IAR",
                                                                                            "Right transverse process epiphyses(L1-5)[1]"="L1_rLPE","[2]"="L2_rLPE","[3]"="L3_rLPE","[4]"="L4_rLPE",
                                                                                            "Left transverse process epiphyses(L1-5)[1]"="L1_lLPE","[2]"="L2_lLPE","[3]"="L3_lLPE","[4]"="L4_lLPE",
                                                                                            "Spinous process epiphyses(L1-5)[1]"="L1_SPE","[2]"="L2_SPE","[3]"="L3_SPE","[4]"="L4_SPE","[5]"="L5_SPE"))),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("VFusing",label=NULL,choices=list("Posterior Synchondrosis (C1)"="C1_PS","Right arch to anterior Arch (C1)"="C1_rA-AA","Left arch to anterior arch (c1)"="C1_lA-AA",
                                                                                              "Dentocentral junction (C2)"="C2_DCJ","Right dentoneural junction (c2)"="C2_rDNJ","Left dentoneural junction (C2)"="C2_lDNJ","Right Neurocentral junction (C2)"="C2_rNCJ","Left Neurocentral junction (C2)"="C2_lNCJ","Posterior Synchondrosis (C2)"="C2_PS","Inferior Annular ring (C2)"="C2_IAR","Dens ossiculum terminale(C2)"="C2_OT","Right transverse process epiphyses (C2)"="C2_rTPE","Left transverse process epiphyses (C2)"="C2_lTPE","Right spinous process epiphyses (C2)"="C2_rSPE","Left Spinous process epiphyses (C2)"="C2_lSPE",
                                                                                              "Posterior Synchondrosis(C3-7)[3]"="C3_PS","[4]"="C4_PS","[5]"="C5_PS","[6]"="C6_PS","[7]"="C7_PS",
                                                                                              "Right Neurocentral junction(C3-7)[3]"="C3_rNCJ","[4]"="C4_rNCJ","[5]"="C5_rNCJ","[6]"="C6_rNCJ","[7]"="C7_rNCJ",
                                                                                              "Left Neurocentral junction(C3-7)[3]"="C3_lNCJ","[4]"="C4_lNCJ","[5]"="C5_lNCJ","[6]"="C6_lNCJ","[7]"="C7_lNCJ",
                                                                                              "Superior annular ring(C3-7)[3]"="C3_SAR","[4]"="C4_SAR","[5]"="C5_SAR","[6]"="C6_SAR","[7]"="C7_SAR",
                                                                                              "Inferior annular ring(C3-7)[3]"="C3_IAR","[4]"="C4_IAR","[5]"="C5_IAR","[6]"="C6_IAR","[7]"="C7_IAR",
                                                                                              "Right transverse process epiphyses(C3-7)[3]"="C3_rCPE","[4]"="C4_rCPE","[5]"="C5_rCPE","[6]"="C6_rCPE","[7]"="C7_rCPE",
                                                                                              "Left transverse process epiphyses(C3-7)[3]"="C3_lCPE","[4]"="C4_lCPE","[5]"="C5_lCPE","[6]"="C6_lCPE","[7]"="C7_lCPE",
                                                                                              "Right spinous process epiphyses(C3-7)[3]"="C3_rSPE","[4]"="C4_rSPE","[5]"="C5_rSPE","[6]"="C6_rSPE","[7]"="C7_rSPE",
                                                                                              "Left spinous process epiphyses(C3-7)[3]"="C3_lSPE","[4]"="C4_lSPE","[5]"="C5_lSPE","[6]"="C6_lSPE","[7]"="C7_lSPE",
                                                                                              "Posterior Synchondrosis(T1-12)[1]"="T1_PS","[2]"="T2_PS","[3]"="T3_PS","[4]"="T4_PS","[5]"="T5_PS","[6]"="T6_PS","[7]"="T7_PS","[8]"="T8_PS","[9]"="T9_PS","[10]"="T10_PS","[11]"="T11_PS","[12]"="T12_PS",
                                                                                              "Right Neurocentral junction(T1-12)[1]"="T1_rNCJ","[2]"="T2_rNCJ","[3]"="T3_rNCJ","[4]"="T4_rNCJ","[5]"="T5_rNCJ","[6]"="T6_rNCJ","[7]"="T7_rNCJ","[8]"="T8_rNCJ","[9]"="T9_rNCJ","[10]"="T10_rNCJ","[11]"="T11_rNCJ","[12]"="T12_rNCJ",
                                                                                              "Left Neurocentral junction(T1-12)[1]"="T1_lNCJ","[2]"="T2_lNCJ","[3]"="T3_lNCJ","[4]"="T4_lNCJ","[5]"="T5_lNCJ","[6]"="T6_lNCJ","[7]"="T7_lNCJ","[8]"="T8_lNCJ","[9]"="T9_lNCJ","[10]"="T10_lNCJ","[11]"="T11_lNCJ","[12]"="T12_lNCJ",
                                                                                              "Superior annular ring(T1-12)[1]"="T1_SAR","[2]"="T2_SAR","[3]"="T3_SAR","[4]"="T4_SAR","[5]"="T5_SAR","[6]"="T6_SAR","[7]"="T7_SAR","[8]"="T8_SAR","[9]"="T9_SAR","[10]"="T10_SAR","[11]"="T11_SAR","[12]"="T12_SAR",
                                                                                              "Inferior annular ring(T1-12)[1]"="T1_IAR","[2]"="T2_IAR","[3]"="T3_IAR","[4]"="T4_IAR","[5]"="T5_IAR","[6]"="T6_IAR","[7]"="T7_IAR","[8]"="T8_IAR","[9]"="T9_IAR","[10]"="T10_IAR","[11]"="T11_IAR","[12]"="T12_IAR",
                                                                                              "Right transverse process epiphyses(T1-12)[1]"="T1_rTPE","[2]"="T2_rTPE","[3]"="T3_rTPE","[4]"="T4_rTPE","[5]"="T5_rTPE","[6]"="T6_rTPE","[7]"="T7_rTPE","[8]"="T8_rTPE","[9]"="T9_rTPE","[10]"="T10_rTPE","[11]"="T11_rTPE","[12]"="T12_rTPE",
                                                                                              "Left transverse process epiphyses(T1-12)[1]"="T1_lTPE","[2]"="T2_lTPE","[3]"="T3_lTPE","[4]"="T4_lTPE","[5]"="T5_lTPE","[6]"="T6_lTPE","[7]"="T7_lTPE","[8]"="T8_lTPE","[9]"="T9_lTPE","[10]"="T10_lTPE","[11]"="T11_lTPE","[12]"="T12_lTPE",
                                                                                              "Spinous process epiphyses(T1-12)[1]"="T1_SPE","[2]"="T2_SPE","[3]"="T3_SPE","[4]"="T4_SPE","[5]"="T5_SPE","[6]"="T6_SPE","[7]"="T7_SPE","[8]"="T8_SPE","[9]"="T9_SPE","[10]"="T10_SPE","[11]"="T11_SPE","[12]"="T12_SPE",
                                                                                              "Posterior Synchondrosis(L1-5)[1]"="L1_PS","[2]"="L2_PS","[3]"="L3_PS","[4]"="L4_PS","[5]"="L5_PS",
                                                                                              "Right Neurocentral junction(L1-5)[1]"="L1_rNCJ","[2]"="L2_rNCJ","[3]"="L3_rNCJ","[4]"="L4_rNCJ","[5]"="L5_rNCJ",
                                                                                              "Left Neurocentral junction(L1-5)[1]"="L1_lNCJ","[2]"="L2_lNCJ","[3]"="L3_lNCJ","[4]"="L4_lNCJ","[5]"="L5_lNCJ",
                                                                                              "Superior annular ring(L1-5)[1]"="L1_SAR","[2]"="L2_SAR","[3]"="L3_SAR","[4]"="L4_SAR","[5]"="L5_SAR",
                                                                                              "Inferior annular ring(L1-5)[1]"="L1_IAR","[2]"="L2_IAR","[3]"="L3_IAR","[4]"="L4_IAR","[5]"="L5_IAR",
                                                                                              "Right transverse process epiphyses(L1-5)[1]"="L1_rLPE","[2]"="L2_rLPE","[3]"="L3_rLPE","[4]"="L4_rLPE",
                                                                                              "Left transverse process epiphyses(L1-5)[1]"="L1_lLPE","[2]"="L2_lLPE","[3]"="L3_lLPE","[4]"="L4_lLPE",
                                                                                              "Spinous process epiphyses(L1-5)[1]"="L1_SPE","[2]"="L2_SPE","[3]"="L3_SPE","[4]"="L4_SPE","[5]"="L5_SPE"))),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("VFused",label=NULL,choices=list("Posterior Synchondrosis (C1)"="C1_PS","Right arch to anterior Arch (C1)"="C1_rA-AA","Left arch to anterior arch (c1)"="C1_lA-AA",
                                                                                             "Dentocentral junction (C2)"="C2_DCJ","Right dentoneural junction (c2)"="C2_rDNJ","Left dentoneural junction (C2)"="C2_lDNJ","Right Neurocentral junction (C2)"="C2_rNCJ","Left Neurocentral junction (C2)"="C2_lNCJ","Posterior Synchondrosis (C2)"="C2_PS","Inferior Annular ring (C2)"="C2_IAR","Dens ossiculum terminale(C2)"="C2_OT","Right transverse process epiphyses (C2)"="C2_rTPE","Left transverse process epiphyses (C2)"="C2_lTPE","Right spinous process epiphyses (C2)"="C2_rSPE","Left Spinous process epiphyses (C2)"="C2_lSPE",
                                                                                             "Posterior Synchondrosis(C3-7)[3]"="C3_PS","[4]"="C4_PS","[5]"="C5_PS","[6]"="C6_PS","[7]"="C7_PS",
                                                                                             "Right Neurocentral junction(C3-7)[3]"="C3_rNCJ","[4]"="C4_rNCJ","[5]"="C5_rNCJ","[6]"="C6_rNCJ","[7]"="C7_rNCJ",
                                                                                             "Left Neurocentral junction(C3-7)[3]"="C3_lNCJ","[4]"="C4_lNCJ","[5]"="C5_lNCJ","[6]"="C6_lNCJ","[7]"="C7_lNCJ",
                                                                                             "Superior annular ring(C3-7)[3]"="C3_SAR","[4]"="C4_SAR","[5]"="C5_SAR","[6]"="C6_SAR","[7]"="C7_SAR",
                                                                                             "Inferior annular ring(C3-7)[3]"="C3_IAR","[4]"="C4_IAR","[5]"="C5_IAR","[6]"="C6_IAR","[7]"="C7_IAR",
                                                                                             "Right transverse process epiphyses(C3-7)[3]"="C3_rCPE","[4]"="C4_rCPE","[5]"="C5_rCPE","[6]"="C6_rCPE","[7]"="C7_rCPE",
                                                                                             "Left transverse process epiphyses(C3-7)[3]"="C3_lCPE","[4]"="C4_lCPE","[5]"="C5_lCPE","[6]"="C6_lCPE","[7]"="C7_lCPE",
                                                                                             "Right spinous process epiphyses(C3-7)[3]"="C3_rSPE","[4]"="C4_rSPE","[5]"="C5_rSPE","[6]"="C6_rSPE","[7]"="C7_rSPE",
                                                                                             "Left spinous process epiphyses(C3-7)[3]"="C3_lSPE","[4]"="C4_lSPE","[5]"="C5_lSPE","[6]"="C6_lSPE","[7]"="C7_lSPE",
                                                                                             "Posterior Synchondrosis(T1-12)[1]"="T1_PS","[2]"="T2_PS","[3]"="T3_PS","[4]"="T4_PS","[5]"="T5_PS","[6]"="T6_PS","[7]"="T7_PS","[8]"="T8_PS","[9]"="T9_PS","[10]"="T10_PS","[11]"="T11_PS","[12]"="T12_PS",
                                                                                             "Right Neurocentral junction(T1-12)[1]"="T1_rNCJ","[2]"="T2_rNCJ","[3]"="T3_rNCJ","[4]"="T4_rNCJ","[5]"="T5_rNCJ","[6]"="T6_rNCJ","[7]"="T7_rNCJ","[8]"="T8_rNCJ","[9]"="T9_rNCJ","[10]"="T10_rNCJ","[11]"="T11_rNCJ","[12]"="T12_rNCJ",
                                                                                             "Left Neurocentral junction(T1-12)[1]"="T1_lNCJ","[2]"="T2_lNCJ","[3]"="T3_lNCJ","[4]"="T4_lNCJ","[5]"="T5_lNCJ","[6]"="T6_lNCJ","[7]"="T7_lNCJ","[8]"="T8_lNCJ","[9]"="T9_lNCJ","[10]"="T10_lNCJ","[11]"="T11_lNCJ","[12]"="T12_lNCJ",
                                                                                             "Superior annular ring(T1-12)[1]"="T1_SAR","[2]"="T2_SAR","[3]"="T3_SAR","[4]"="T4_SAR","[5]"="T5_SAR","[6]"="T6_SAR","[7]"="T7_SAR","[8]"="T8_SAR","[9]"="T9_SAR","[10]"="T10_SAR","[11]"="T11_SAR","[12]"="T12_SAR",
                                                                                             "Inferior annular ring(T1-12)[1]"="T1_IAR","[2]"="T2_IAR","[3]"="T3_IAR","[4]"="T4_IAR","[5]"="T5_IAR","[6]"="T6_IAR","[7]"="T7_IAR","[8]"="T8_IAR","[9]"="T9_IAR","[10]"="T10_IAR","[11]"="T11_IAR","[12]"="T12_IAR",
                                                                                             "Right transverse process epiphyses(T1-12)[1]"="T1_rTPE","[2]"="T2_rTPE","[3]"="T3_rTPE","[4]"="T4_rTPE","[5]"="T5_rTPE","[6]"="T6_rTPE","[7]"="T7_rTPE","[8]"="T8_rTPE","[9]"="T9_rTPE","[10]"="T10_rTPE","[11]"="T11_rTPE","[12]"="T12_rTPE",
                                                                                             "Left transverse process epiphyses(T1-12)[1]"="T1_lTPE","[2]"="T2_lTPE","[3]"="T3_lTPE","[4]"="T4_lTPE","[5]"="T5_lTPE","[6]"="T6_lTPE","[7]"="T7_lTPE","[8]"="T8_lTPE","[9]"="T9_lTPE","[10]"="T10_lTPE","[11]"="T11_lTPE","[12]"="T12_lTPE",
                                                                                             "Spinous process epiphyses(T1-12)[1]"="T1_SPE","[2]"="T2_SPE","[3]"="T3_SPE","[4]"="T4_SPE","[5]"="T5_SPE","[6]"="T6_SPE","[7]"="T7_SPE","[8]"="T8_SPE","[9]"="T9_SPE","[10]"="T10_SPE","[11]"="T11_SPE","[12]"="T12_SPE",
                                                                                             "Posterior Synchondrosis(L1-5)[1]"="L1_PS","[2]"="L2_PS","[3]"="L3_PS","[4]"="L4_PS","[5]"="L5_PS",
                                                                                             "Right Neurocentral junction(L1-5)[1]"="L1_rNCJ","[2]"="L2_rNCJ","[3]"="L3_rNCJ","[4]"="L4_rNCJ","[5]"="L5_rNCJ",
                                                                                             "Left Neurocentral junction(L1-5)[1]"="L1_lNCJ","[2]"="L2_lNCJ","[3]"="L3_lNCJ","[4]"="L4_lNCJ","[5]"="L5_lNCJ",
                                                                                             "Superior annular ring(L1-5)[1]"="L1_SAR","[2]"="L2_SAR","[3]"="L3_SAR","[4]"="L4_SAR","[5]"="L5_SAR",
                                                                                             "Inferior annular ring(L1-5)[1]"="L1_IAR","[2]"="L2_IAR","[3]"="L3_IAR","[4]"="L4_IAR","[5]"="L5_IAR",
                                                                                             "Right transverse process epiphyses(L1-5)[1]"="L1_rLPE","[2]"="L2_rLPE","[3]"="L3_rLPE","[4]"="L4_rLPE",
                                                                                             "Left transverse process epiphyses(L1-5)[1]"="L1_lLPE","[2]"="L2_lLPE","[3]"="L3_lLPE","[4]"="L4_lLPE",
                                                                                             "Spinous process epiphyses(L1-5)[1]"="L1_SPE","[2]"="L2_SPE","[3]"="L3_SPE","[4]"="L4_SPE","[5]"="L5_SPE"))),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("VOblit",label=NULL,choices=list("Posterior Synchondrosis (C1)"="C1_PS","Right arch to anterior Arch (C1)"="C1_rA-AA","Left arch to anterior arch (c1)"="C1_lA-AA",
                                                                                             "Dentocentral junction (C2)"="C2_DCJ","Right dentoneural junction (c2)"="C2_rDNJ","Left dentoneural junction (C2)"="C2_lDNJ","Right Neurocentral junction (C2)"="C2_rNCJ","Left Neurocentral junction (C2)"="C2_lNCJ","Posterior Synchondrosis (C2)"="C2_PS","Inferior Annular ring (C2)"="C2_IAR","Dens ossiculum terminale(C2)"="C2_OT","Right transverse process epiphyses (C2)"="C2_rTPE","Left transverse process epiphyses (C2)"="C2_lTPE","Right spinous process epiphyses (C2)"="C2_rSPE","Left Spinous process epiphyses (C2)"="C2_lSPE",
                                                                                             "Posterior Synchondrosis(C3-7)[3]"="C3_PS","[4]"="C4_PS","[5]"="C5_PS","[6]"="C6_PS","[7]"="C7_PS",
                                                                                             "Right Neurocentral junction(C3-7)[3]"="C3_rNCJ","[4]"="C4_rNCJ","[5]"="C5_rNCJ","[6]"="C6_rNCJ","[7]"="C7_rNCJ",
                                                                                             "Left Neurocentral junction(C3-7)[3]"="C3_lNCJ","[4]"="C4_lNCJ","[5]"="C5_lNCJ","[6]"="C6_lNCJ","[7]"="C7_lNCJ",
                                                                                             "Superior annular ring(C3-7)[3]"="C3_SAR","[4]"="C4_SAR","[5]"="C5_SAR","[6]"="C6_SAR","[7]"="C7_SAR",
                                                                                             "Inferior annular ring(C3-7)[3]"="C3_IAR","[4]"="C4_IAR","[5]"="C5_IAR","[6]"="C6_IAR","[7]"="C7_IAR",
                                                                                             "Right transverse process epiphyses(C3-7)[3]"="C3_rCPE","[4]"="C4_rCPE","[5]"="C5_rCPE","[6]"="C6_rCPE","[7]"="C7_rCPE",
                                                                                             "Left transverse process epiphyses(C3-7)[3]"="C3_lCPE","[4]"="C4_lCPE","[5]"="C5_lCPE","[6]"="C6_lCPE","[7]"="C7_lCPE",
                                                                                             "Right spinous process epiphyses(C3-7)[3]"="C3_rSPE","[4]"="C4_rSPE","[5]"="C5_rSPE","[6]"="C6_rSPE","[7]"="C7_rSPE",
                                                                                             "Left spinous process epiphyses(C3-7)[3]"="C3_lSPE","[4]"="C4_lSPE","[5]"="C5_lSPE","[6]"="C6_lSPE","[7]"="C7_lSPE",
                                                                                             "Posterior Synchondrosis(T1-12)[1]"="T1_PS","[2]"="T2_PS","[3]"="T3_PS","[4]"="T4_PS","[5]"="T5_PS","[6]"="T6_PS","[7]"="T7_PS","[8]"="T8_PS","[9]"="T9_PS","[10]"="T10_PS","[11]"="T11_PS","[12]"="T12_PS",
                                                                                             "Right Neurocentral junction(T1-12)[1]"="T1_rNCJ","[2]"="T2_rNCJ","[3]"="T3_rNCJ","[4]"="T4_rNCJ","[5]"="T5_rNCJ","[6]"="T6_rNCJ","[7]"="T7_rNCJ","[8]"="T8_rNCJ","[9]"="T9_rNCJ","[10]"="T10_rNCJ","[11]"="T11_rNCJ","[12]"="T12_rNCJ",
                                                                                             "Left Neurocentral junction(T1-12)[1]"="T1_lNCJ","[2]"="T2_lNCJ","[3]"="T3_lNCJ","[4]"="T4_lNCJ","[5]"="T5_lNCJ","[6]"="T6_lNCJ","[7]"="T7_lNCJ","[8]"="T8_lNCJ","[9]"="T9_lNCJ","[10]"="T10_lNCJ","[11]"="T11_lNCJ","[12]"="T12_lNCJ",
                                                                                             "Superior annular ring(T1-12)[1]"="T1_SAR","[2]"="T2_SAR","[3]"="T3_SAR","[4]"="T4_SAR","[5]"="T5_SAR","[6]"="T6_SAR","[7]"="T7_SAR","[8]"="T8_SAR","[9]"="T9_SAR","[10]"="T10_SAR","[11]"="T11_SAR","[12]"="T12_SAR",
                                                                                             "Inferior annular ring(T1-12)[1]"="T1_IAR","[2]"="T2_IAR","[3]"="T3_IAR","[4]"="T4_IAR","[5]"="T5_IAR","[6]"="T6_IAR","[7]"="T7_IAR","[8]"="T8_IAR","[9]"="T9_IAR","[10]"="T10_IAR","[11]"="T11_IAR","[12]"="T12_IAR",
                                                                                             "Right transverse process epiphyses(T1-12)[1]"="T1_rTPE","[2]"="T2_rTPE","[3]"="T3_rTPE","[4]"="T4_rTPE","[5]"="T5_rTPE","[6]"="T6_rTPE","[7]"="T7_rTPE","[8]"="T8_rTPE","[9]"="T9_rTPE","[10]"="T10_rTPE","[11]"="T11_rTPE","[12]"="T12_rTPE",
                                                                                             "Left transverse process epiphyses(T1-12)[1]"="T1_lTPE","[2]"="T2_lTPE","[3]"="T3_lTPE","[4]"="T4_lTPE","[5]"="T5_lTPE","[6]"="T6_lTPE","[7]"="T7_lTPE","[8]"="T8_lTPE","[9]"="T9_lTPE","[10]"="T10_lTPE","[11]"="T11_lTPE","[12]"="T12_lTPE",
                                                                                             "Spinous process epiphyses(T1-12)[1]"="T1_SPE","[2]"="T2_SPE","[3]"="T3_SPE","[4]"="T4_SPE","[5]"="T5_SPE","[6]"="T6_SPE","[7]"="T7_SPE","[8]"="T8_SPE","[9]"="T9_SPE","[10]"="T10_SPE","[11]"="T11_SPE","[12]"="T12_SPE",
                                                                                             "Posterior Synchondrosis(L1-5)[1]"="L1_PS","[2]"="L2_PS","[3]"="L3_PS","[4]"="L4_PS","[5]"="L5_PS",
                                                                                             "Right Neurocentral junction(L1-5)[1]"="L1_rNCJ","[2]"="L2_rNCJ","[3]"="L3_rNCJ","[4]"="L4_rNCJ","[5]"="L5_rNCJ",
                                                                                             "Left Neurocentral junction(L1-5)[1]"="L1_lNCJ","[2]"="L2_lNCJ","[3]"="L3_lNCJ","[4]"="L4_lNCJ","[5]"="L5_lNCJ",
                                                                                             "Superior annular ring(L1-5)[1]"="L1_SAR","[2]"="L2_SAR","[3]"="L3_SAR","[4]"="L4_SAR","[5]"="L5_SAR",
                                                                                             "Inferior annular ring(L1-5)[1]"="L1_IAR","[2]"="L2_IAR","[3]"="L3_IAR","[4]"="L4_IAR","[5]"="L5_IAR",
                                                                                             "Right transverse process epiphyses(L1-5)[1]"="L1_rLPE","[2]"="L2_rLPE","[3]"="L3_rLPE","[4]"="L4_rLPE",
                                                                                             "Left transverse process epiphyses(L1-5)[1]"="L1_lLPE","[2]"="L2_lLPE","[3]"="L3_lLPE","[4]"="L4_lLPE",
                                                                                             "Spinous process epiphyses(L1-5)[1]"="L1_SPE","[2]"="L2_SPE","[3]"="L3_SPE","[4]"="L4_SPE","[5]"="L5_SPE"))))),
                   
                   tabPanel("Thorax",
                            column(width=4,h3("Inventory"),
                                   textOutput("TIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("TPresent",label=NULL,
                                                             choices=list("Manubrum(Sternum)"="ST_M","1st Sternebra(Sternum)"="ST_S1","2nd Sternebra[Single ossification centre](Sternum)"="ST_S2","Right 2nd Sternebra[Biparate](Sternum)"="ST_S2_r","Left 2nd Sternebra[Biparate](Sternum)"="ST_S2_l","Right 3rd Sternebra(Sternum)"="ST_S3_r","Left 3rd Sternebra(Sternum)"="ST_S3_l","Right 4th Sternebra(Sternum)"="ST_S4_r","Left 4th Sternebra(Sternum)"="ST_S4_l","Xiphoid(Sternum)"="ST_X",
                                                                          "Right 1st Rib"="R1_r","Left 1st Rib"="R1_l","Right rib(2-3)[2]"="R2_r","Left rib(2-3)[2]"="R2_l","Right rib(2-3)[3]"="R3_r","Left rib(2-3)[3]"="R3_l","Right rib(4-6)[4]"="R4_r","Left rib(4-6)[4]"="R4_l","Right rib(4-6)[5]"="R5_r","Left rib(4-6)[5]"="R5_l","Right rib(4-6)[6]"="R6_r","Left rib(4-6)[6]"="R6_l",
                                                                          "Right rib(7-9)[7]"="R7_r","Left rib(7-9)[7]"="R7_l","Right rib(7-9)[8]"="R8_r","Left rib(7-9)[8]"="R8_l","Right rib(7-9)[9]"="R9_r","Left rib(7-9)[9]"="R9_l","Right rib(10-12)[10]"="R10_r","Left rib(10-12)[10]"="R10_l","Right rib(10-12)[11]"="R11_r","Left rib(10-12)[11]"="R11_l","Right rib(10-12)[12]"="R12_r","Left rib(10-12)[12]"="R12_l"))),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("TComplete",label=NULL,
                                                             choices=list("Manubrum(Sternum)"="ST_M","1st Sternebra(Sternum)"="ST_S1","2nd Sternebra[Single ossification centre](Sternum)"="ST_S2","Right 2nd Sternebra[Biparate](Sternum)"="ST_S2_r","Left 2nd Sternebra[Biparate](Sternum)"="ST_S2_l","Right 3rd Sternebra(Sternum)"="ST_S3_r","Left 3rd Sternebra(Sternum)"="ST_S3_l","Right 4th Sternebra(Sternum)"="ST_S4_r","Left 4th Sternebra(Sternum)"="ST_S4_l","Xiphoid(Sternum)"="ST_X",
                                                                          "Right 1st Rib"="R1_r","Left 1st Rib"="R1_l","Right rib(2-3)[2]"="R2_r","Left rib(2-3)[2]"="R2_l","Right rib(2-3)[3]"="R3_r","Left rib(2-3)[3]"="R3_l","Right rib(4-6)[4]"="R4_r","Left rib(4-6)[4]"="R4_l","Right rib(4-6)[5]"="R5_r","Left rib(4-6)[5]"="R5_l","Right rib(4-6)[6]"="R6_r","Left rib(4-6)[6]"="R6_l",
                                                                          "Right rib(7-9)[7]"="R7_r","Left rib(7-9)[7]"="R7_l","Right rib(7-9)[8]"="R8_r","Left rib(7-9)[8]"="R8_l","Right rib(7-9)[9]"="R9_r","Left rib(7-9)[9]"="R9_l","Right rib(10-12)[10]"="R10_r","Left rib(10-12)[10]"="R10_l","Right rib(10-12)[11]"="R11_r","Left rib(10-12)[11]"="R11_l","Right rib(10-12)[12]"="R12_r","Left rib(10-12)[12]"="R12_l")))),
                            column(width=8,h3("Fusion"),
                                   textOutput("TFScore"),
                                   column(width=3,h4("Open/Epiphysis unformed"),
                                          checkboxGroupInput("TOpen",label=NULL,choices=list("Sternebrae 3 and 4(Sternum)"="ST_S3_S4","Sternebrae 2 and 3/4(Sternum)"="ST_S2_S3-4","Sternebrae 1 and Mesosternum[2-4](sternum)"="ST_S1_S2-4","Manubrium and mesosternum(Sternum)"="ST_M_MS","Xiphoid and mesosternum(Sternum)"="ST_X_MS","Right Suprasternal flake(Sternum)"="ST_SSF_r","Left Suprasternal flake(Sternum)"="ST_SSF_l","Right Manubrial flake(Sternum)"="ST_MF_r","Left Manubrial flake(Sternum)"="ST_MF_l",
                                                                                             "Right 1st Costal notch flake(Sternum)"="ST_CNF1_r","Left 1st Costal notch flake(Sternum)"="ST_CNF1_l","Right 2nd Costal notch flake(Sternum)"="ST_CNF2_r","Left 2nd Costal notch flake(Sternum)"="ST_CNF2_l","Right 3rd Costal notch flake(Sternum)"="ST_CNF3_r","Left 3rd Costal notch flake(Sternum)"="ST_CNF3_l","Right 4th Costal notch flake(Sternum)"="ST_CNF4_r","Left 4th Costal notch flake(Sternum)"="ST_CNF4_l","Right 5th Costal notch flake(Sternum)"="ST_CNF5_r","Left 5th Costal notch flake(Sternum)"="ST_CNF5_l","Right 6th Costal notch flake(Sternum)"="ST_CNF6_r","Left 6th Costal notch flake(Sternum)"="ST_CNF6_l"))),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("TFusing",label=NULL,choices=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("TFused",label=NULL,choices=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("TOblit",label=NULL,choices=list())))),
                   tabPanel("Shoulder",
                            column(width=4,h3("Inventory"),
                                   textOutput("SHIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("SHPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("SHComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("SHFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("SHOpen",label=NULL,choices=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("SHFusing",label=NULL,choices=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("SHFused",label=NULL,choices=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("SHOblit",label=NULL,choices=list())))),
                   tabPanel("Upper Limb",
                            column(width=4,h3("Inventory"),
                                   textOutput("ULIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("ULPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("ULComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("ULFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("ULOpen",label=NULL,choices=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("ULFusing",label=NULL,choices=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("ULFused",label=NULL,choices=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("ULOblit",label=NULL,choices=list())))),
                   tabPanel("Pelvis",
                            column(width=4,h3("Inventory"),
                                   textOutput("PIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("PPresent",label=NULL,
                                                             choices=list("Right Neural Arch (S1)"="S1_rNA","Left Neural Arch (S1)"="S1_lNA","Centrum (S1)"="S1_C","Right Lateral element (S1)"="S1_rLE","Left Lateral element(S1)"="S1_lLE","Right Neural Arch (S2)"="S2_rNA","Left Neural Arch (S2)"="S2_lNA","Centrum (S2)"="S2_C","Right Lateral element (S2)"="S2_rLE","Left Lateral element(S2)"="S2_lLE",
                                                                          "Right Neural Arch (S3)"="S3_rNA","Left Neural Arch (S3)"="S3_lNA","Centrum (S3)"="S3_C","Right Neural Arch (S4)"="S4_rNA","Left Neural Arch (S4)"="S4_lNA","Centrum (S4)"="S4_C","Right Neural Arch (S5)"="S5_rNA","Left Neural Arch (S5)"="S5_lNA","Centrum (S5)"="S5_C"))),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("PComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("PFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("POpen",label=NULL,choices=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("PFusing",label=NULL,choices=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("PFused",label=NULL,choices=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("POblit",label=NULL,choices=list())))),
                   tabPanel("Lower Limb",
                            column(width=4,h3("Inventory"),
                                   textOutput("LLIScore"),
                                   column(width=6,h4("Present"),
                                          checkboxGroupInput("LLPresent",label=NULL,
                                                             choices=list())),
                                   column(width=6,h4("Complete"),
                                          checkboxGroupInput("LLComplete",label=NULL,
                                                             choices=list()))),
                            column(width=8,h3("Fusion"),
                                   textOutput("LLFScore"),
                                   column(width=3,h4("Open"),
                                          checkboxGroupInput("LLOpen",label=NULL,choices=list())),
                                   column(width=3,h4("Fusing"),
                                          checkboxGroupInput("LLFusing",label=NULL,choices=list())),
                                   column(width=3,h4("Fused"),
                                          checkboxGroupInput("LLFused",label=NULL,choices=list())),
                                   column(width=3,h4("Obliterated"),
                                          checkboxGroupInput("LLOblit",label=NULL,choices=list())))),
                   tabPanel("Unidentified fragments",
                            fluidPage(h3("Unidentified Inventory"),
                                      textOutput("UScore"),
                                      column(width=4,
                                             numericInput("USkull","Skull",value=0,width='50%'),
                                             numericInput("ULimb","Limb Long bone",value=0,width='50%'),
                                             numericInput("UVert","Vertebrae",value=0,width='50%'),
                                             numericInput("UHandFoot","Hand/foot",value=0,width='50%')),
                                      column(width=4,
                                             numericInput("UClavScap","Clavicle/Scapula",value=0,width='50%'),
                                             numericInput("UOsCoxae","Os coxae",value=0,width='50%'),
                                             numericInput("UOther","Other fragments",value=0,width='50%')))),
                   tabPanel("Additional",
                            column(width=6,h3("Ordering and Siding"),
                                   #textOutput("O_S"),
                                   column(width=6,selectInput("CVOrder","Cervicle Vertebrae (3-7) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.CVOrder=='Partial'",textInput("CVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("TVOrder","Thorasic Vertebrae (1-12) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.TVOrder=='Partial'",textInput("TVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("LVOrder","Lumbar Vertebrae (1-5) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.LVOrder=='Partial'",textInput("LVOrder2","Describe partial ordering",value="NA")),
                                          selectInput("ROrder","Ribs (3-10) ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.ROrder=='Partial'",textInput("ROrder2","Describe partial ordering",value="NA")),
                                          selectInput("RSide","Ribs (1-12) siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.RSide=='Partial'",textInput("RSide2","Describe partial Siding",value="NA")),
                                          selectInput("MCOrder","Metacarpal ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.MCOrder=='Partial'",textInput("MCOrder2","Describe partial ordering",value="NA")),
                                          selectInput("MCSide","Metacarpal siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          h1(br()),
                                          h1(br())),
                                   column(width=6,conditionalPanel("input.MCSide=='Partial'",textInput("MCSide2","Describe partial Siding",value="NA")),
                                          selectInput("HPOrder","Hand phalanges ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.HPOrder=='Partial'",textInput("HPOrder2","Describe partial ordering",value="NA")),
                                          selectInput("HPSide","Hand halanges siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.HPSide=='Partial'",textInput("HPSide2","Describe partial Siding",value="NA")),
                                          selectInput("MTOrder","Metatarsal ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.MTOrder=='Partial'",textInput("MTOrder2","Describe partial ordering",value="NA")),
                                          selectInput("MTSide","Metatarsal siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.MTSide=='Partial'",textInput("MTSide2","Describe partial Siding",value="NA")),
                                          selectInput("FPOrder","Foot phalanges ording",c("Not Ordered"=FALSE,"Ordered"=TRUE,"Partial Ording"="Partial")),
                                          conditionalPanel("input.FPOrder=='Partial'",textInput("FPOrder2","Describe partial ordering",value="NA")),
                                          selectInput("FPSide","Foot phalanges siding",c("Not Sided"=FALSE,"Sided"=TRUE,"Partial Siding"="Partial")),
                                          conditionalPanel("input.FPSide=='Partial'",textInput("FPSide2","Describe partial Siding",value="NA")),
                                          h1(br()),
                                          h1(br()))
                            ),
                            column(width=6,h3("Photographic record"),
                                   h5("Please enter photographic reference number(s) or filepath(s)separate multiple entries with /"),
                                   column(width=6,textInput("Photo1","Full Skeleton",value="NA"),
                                          textInput("Photo2","Cranium Anterior",value='NA'),
                                          textInput("Photo3","Cranium Lateral",value='NA'),
                                          textInput("Photo4","Cranium Superior",value='NA'),
                                          textInput("Photo5","Cranium Basilar",value='NA'),
                                          textInput("Photo6","Skull Fragmented",value='NA'),
                                          textInput("Photo7","Mandible",value='NA'),
                                          textInput("Photo8","Hand",value='NA')),
                                   column(width=6,textInput("Photo9","Foot",value='NA'),
                                          textInput("Photo10","Arm",value='NA'),
                                          textInput("Photo11","Leg",value='NA'),
                                          textInput("Photo12","Pelvis",value='NA'),
                                          textInput("Photo13","Shoulder",value='NA'),
                                          textInput("Photo14","Thorax",value='NA'),
                                          textInput("Photo15","Vertebrae",value='NA'),
                                          textInput("Photo16","Unidentified Fragments",value='NA')))),
                   tabPanel("write",
                            textInput("dir","Data Folder",value="../../data/"),
                            column(width=4,
                                   h3("Population Info"),
                                   textInput("POPID","Population ID",value="NA"),
                                   textInput("POPName","Population name",value="NA"),
                                   textInput("Person1","Investigator",value="NA"),
                                   actionButton("Create","Create new file"),
                                   h4(textOutput("PMessage"))
                            ),
                            column(width=4,
                                   h3("Individual Info"),
                                   textInput("ID","Individual ID",value="NA"),
                                   textInput("Person2","Investigator intials",value="NA"),
                                   actionButton("Append","Add individual"),
                                   h4(textOutput("IMessage"))
                            ),
                            column(width=4,
                                   h3("Compatability check"),
                                   actionButton("Compat","Check file"),
                                   h4(textOutput("ComMessage"))
                            )
                   )
                   ))