library(shiny);library(markdown)

shinyUI(navbarPage("Dental",
                   tabPanel("Perminant Inventory",#Perminant Inventory####
                            h3(textOutput("pScore")),
                            #h4(textOutput("Perminant")),
                            column(width=2,
                                   h4("Maxillary"),
                                   checkboxGroupInput("u_present","Tick if present",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")),
                                   h4("Mandibular"),
                                   checkboxGroupInput("L_present","Tick if present",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("u_loose","Tick if loose",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")),
                                   h4(br()),
                                   checkboxGroupInput("L_loose","Tick if loose",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("u_occlusion","In occlusion",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")),
                                   h4(br()),
                                   checkboxGroupInput("L_occlusion","In occlusion",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("u_unerupted","un-erupted",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")),
                                   h4(br()),
                                   checkboxGroupInput("L_unerupted","un-erupted",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("u_premortem","premortem loss",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")),
                                   h4(br()),
                                   checkboxGroupInput("L_premortem","premortem loss",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("u_postmortem","postmortem loss",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")),
                                   h4(br()),
                                   checkboxGroupInput("L_postmortem","postmortem loss",c("RM3","RM2","RM1","RP4","RP3","RC1","RI2","RI1","LI1","LI2","LC1","LP3","LP4","LM1","LM2","LM3")))
                            ),
                   tabPanel("Deciduous Inventory",#Decidous Inventory####
                            h3(textOutput("dScore")),
                            column(width=2,
                                   h4("Maxillary"),
                                   checkboxGroupInput("ud_present","Tick if present",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")),
                                   h4("Mandibular"),
                                   checkboxGroupInput("Ld_present","Tick if present",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("ud_loose","Tick if loose",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")),
                                   h4(br()),
                                   checkboxGroupInput("Ld_loose","Tick if loose",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("ud_occlusion","In occlusion",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")),
                                   h4(br()),
                                   checkboxGroupInput("Ld_occlusion","In occlusion",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("ud_unerupted","un-erupted",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")),
                                   h4(br()),
                                   checkboxGroupInput("Ld_unerupted","un-erupted",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("ud_premortem","premortem loss",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")),
                                   h4(br()),
                                   checkboxGroupInput("Ld_premortem","premortem loss",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2"))),
                            column(width=2,
                                   h4(br()),
                                   checkboxGroupInput("ud_postmortem","postmortem loss",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")),
                                   h4(br()),
                                   checkboxGroupInput("Ld_postmortem","postmortem loss",c("RdM2","RdM1","RdC1","RdI2","RdI1","LdI1","LdI2","LdC1","LdM1","LdM2")))
                   ),
                   tabPanel("Caries/Calculus",#Caries/Calculus####
                            #h3(textOutput("Caries")),
                            #h3(textOutput("Calculus")),
                            uiOutput("CC_UI")
                   ),
                   tabPanel("Enamel defects",#Enamel defects####
                            h6("nb loactions should be given as the distance in mm from the midpoint of the labial/buccal cemento-enamel-junction(CEJ) to the most occlusal portion of the defect. Separate multiple measurements with /"),
                            #h3(textOutput("Hypoplasia")),
                            #h3(textOutput("Hypercalcification")),
                            uiOutput("ED_UI")
                   ),
                            
                   tabPanel("Premortem modification",#Postmortem mods####
                            #h3(textOutput("Ablation")),
                            #h3(textOutput("Mod")),
                            #tableOutput("Mods"),
                            uiOutput("PM_UI")
                            ),
                   tabPanel("Molar Wear",#Molar wear####
                            #h3(textOutput("Wear")),
                            uiOutput("MW_UI")),
                   tabPanel("Other Wear",#other wear####
                            uiOutput("OW_UI")),
                   tabPanel("Measurements",#measurements####
                            #h3(textOutput("Measurements")),
                            uiOutput("M_UI")),
                   tabPanel("Morphological traits",#Morphological traits####
                            #h3(textOutput("MTraits")),
                            column(width=3,
                                   h3("Incisors"),
                                   conditionalPanel("input.u_present.indexOf('RI1') >=0 && input.u_present.indexOf('LI1') >=0 && input.u_loose.indexOf('RI1')==-1 && input.u_loose.indexOf('LI1')==-1",
                                                    selectInput("winging","Winging of upper central incisors",c("Straight/ no winging"="S","Bilateral winging (mesiolingual)"="BW","Unilateral winging (mesiolingual):Left"="UWL","Unilateral winging (mesiolingual):Right"="UWR","Bilateral Counter winging(distolingual)"="BCW","Unilateral Counter winging:Left"="UCWL","Unilateral Counter winging:Right"="UCWR"))),
                                   conditionalPanel("input.u_present.indexOf('RI2') >=0",
                                                    h4("upper RI2"),
                                                    selectInput("shovel_uRI2","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uRI2","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling"),
                                                    selectInput("Peg_uRI2","Peg-Shaped",c("Normal-sized incisor"=0,"Reduced in size but normal crown form"=1,"Very reduced in size with peg shaped crown morphology"=2))),
                                   conditionalPanel("input.u_present.indexOf('LI2') >=0",
                                                    h4("upper LI2"),
                                                    selectInput("shovel_uLI2","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uLI2","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling"),
                                                    selectInput("Peg_uLI2","Peg-Shaped",c("Normal-sized incisor"=0,"Reduced in size but normal crown form"=1,"Very reduced in size with peg shaped crown morphology"=2))),
                                   conditionalPanel("input.u_present.indexOf('RI1') >=0",
                                                    h4("upper RI1"),
                                                    selectInput("shovel_uRI1","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uRI1","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling")),
                                   conditionalPanel("input.u_present.indexOf('LI1') >=0",
                                                    h4("upper LI1"),
                                                    selectInput("shovel_uLI1","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uLI1","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling")),
                                   conditionalPanel("input.ud_present.indexOf('RdI1') >=0 && input.ud_present.indexOf('LdI1') >=0 && input.ud_loose.indexOf('RdI1')==-1 && input.ud_loose.indexOf('LdI1')==-1",
                                                    selectInput("winging_d","Winging of upper central decidous incisors",c("Straight/ no winging"="S","Bilateral winging (mesiolingual)"="BW","Unilateral winging (mesiolingual):Left"="UWL","Unilateral winging (mesiolingual):Right"="UWR","Bilateral Counter winging(distolingual)"="BCW","Unilateral Counter winging:Left"="UCWL","Unilateral Counter winging:Right"="UCWR"))),
                                   conditionalPanel("input.ud_present.indexOf('RddI2') >=0",
                                                    h4("upper RdI2"),
                                                    selectInput("shovel_uRdI2","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uRdI2","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling"),
                                                    selectInput("Peg_uRdI2","Peg-Shaped",c("Normal-sized incisor"=0,"Reduced in size but normal crown form"=1,"Very reduced in size with peg shaped crown morphology"=2))),
                                   conditionalPanel("input.ud_present.indexOf('LdI2') >=0",
                                                    h4("upper LdI2"),
                                                    selectInput("shovel_uLdI2","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uLdI2","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling"),
                                                    selectInput("Peg_uLdI2","Peg-Shaped",c("Normal-sized incisor"=0,"Reduced in size but normal crown form"=1,"Very reduced in size with peg shaped crown morphology"=2))),
                                   conditionalPanel("input.ud_present.indexOf('RdI1') >=0",
                                                    h4("upper RdI1"),
                                                    selectInput("shovel_uRdI1","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uRdI1","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling")),
                                   conditionalPanel("input.ud_present.indexOf('LdI1') >=0",
                                                    h4("upper LdI1"),
                                                    selectInput("shovel_uLdI1","Shovelling (lingual)",c("None"=0,"Faint: very slight elevation of mesial and distal aspects"=1,"Trace: easily visible elevations"=2,"Semishovel: stronger ridging with tendency for convergence at cingulum"=3,"Semishovel: Convergence and ridging stronger"=4,"Shovel: Strong ridge development, almost contact at cingulum"=5,"Marked shovel: strong development,ridges sometimes in contact at cingulum"=6,"Barrel: expression greater than marked shovel"=7)),
                                                    selectInput("DShovel_uLdI1","Double Shovelling (labial)",c("None"=0,"Faint: ridges visible under strong light"=1,"Trace:Ridges more easierly seen and palpated"=2,"Semi-Double shovel: ridges readily palpable"=3,"Double shovel: more pronounced on at least 1/2 total crown height"=4,"Pronounced:Very prominent can occur from CEJ to occulsial surface"=5,"Extreme: Very pronounced ridging"=6)),
                                                    h5("nb Distal ridges can be absent in double shovelling")),
                                   h1(br()),
                                   h1(br()),
                                   h1(br()),
                                   h1(br())
                                   ),
                            column(width=3,
                                   h3("Premolars"),
                                  conditionalPanel("input.u_present.indexOf('RP4') >=0",
                                                   h4("upper RP4"),
                                                   selectInput("root_uRP4","Root number",c("One: bifid for less than 1/3 of length"=1,"Two: separate >1/4 of the total length"=2,"Three: separate >1/4 of the total length"=3))),
                                  conditionalPanel("input.u_present.indexOf('RP3') >=0",
                                                   h4("upper RP3"),
                                                   selectInput("root_uRP3","Root number",c("One: bifid for less than 1/3 of length"=1,"Two: separate >1/4 of the total length"=2,"Three: separate >1/4 of the total length"=3))),
                                  conditionalPanel("input.u_present.indexOf('LP4') >=0",
                                                   h4("upper LP4"),
                                                   selectInput("root_uLP4","Root number",c("One: bifid for less than 1/3 of length"=1,"Two: separate >1/4 of the total length"=2,"Three: separate >1/4 of the total length"=3))),
                                  conditionalPanel("input.u_present.indexOf('LP3') >=0",
                                                   h4("upper LP3"),
                                                   selectInput("root_uLP3","Root number",c("One: bifid for less than 1/3 of length"=1,"Two: separate >1/4 of the total length"=2,"Three: separate >1/4 of the total length"=3))),
                                  conditionalPanel("input.L_present.indexOf('RP3') >=0",
                                                   h4("lower RP3"),
                                                   selectInput("Tomes_lRP3","Root number/Tomes' root",c("Developmental groove absent ot shallow and rounded"=0,"Shallow v-shaped developmental groove"=1,"Moderately deep v-shaped developmental groove"=2,"V-shaped deep devellopmental groove"=3,"Deeply invaginated groove on mesial and distal surface"=4,"Two roots: separate for >1/4 of length"=5))),
                                  conditionalPanel("input.L_present.indexOf('LP3') >=0",
                                                   h4("lower LP3"),
                                                   selectInput("Tomes_lLP3","Root number/Tomes' root",c("Developmental groove absent ot shallow and rounded"=0,"Shallow v-shaped developmental groove"=1,"Moderately deep v-shaped developmental groove"=2,"V-shaped deep devellopmental groove"=3,"Deeply invaginated groove on mesial and distal surface"=4,"Two roots: separate for >1/4 of length"=5))),
                                  h1(br()),
                                  h1(br()),
                                  h1(br()),
                                  h1(br())
                                  ),
                            column(width=3,
                                   h3("Molars"),
                                   conditionalPanel("input.u_present.indexOf('RM3') >=0",
                                                    h4("upper RM3"),
                                                    selectInput("Hypocone_uRM3","Hypocone",c("None,site smooth"=0,"Faint ridging"=1,"Faint cuspule"=2,"Small cusp"=3,"Moderate cusp"=3.5,"Large cusp"=4,"Very large cusp"=5)),
                                                    selectInput("Metaconule_uRM3","Metaconule/cusp 5",c("Site smooth,single distal groove separating cusps 3 & 4"=0,"Faint cuspule"=1,"Trace cuspule"=2,"Small cuspule"=3,"Small cusp"=4,"Medium cusp"=5)),
                                                    selectInput("Carabelli_uRM3","Carabelli's trait",c("Mesiolingual aspect of cusp1 smooth"=0,"Groove"=1,"Pit"=2,"Small Y-shaped depression"=3,"Large Y-shaped depression"=4,"Small cusp without free apex. Distal border not contacting lingual grove between cusps 1 & 4"=5,"Medium cusp with attached apex making contact with medial lingual groove"=6,"Large free cusp"=7)),
                                                    selectInput("extensions_uRM3","Enamel Extensions",c("Enamel border straight/ curved towards crown(rarly)"=0,"Faint (~1mm) extension projecting towards & along root"=1,"Medium (~2mm) exension"=2,"Lengthy (>4mm) exension, may extend to root bifurcation"=3)),
                                                    h5("nb score any extension not attached to crown as absent")),
                                   conditionalPanel("input.u_present.indexOf('RM2') >=0",
                                                    h4("upper RM2"),
                                                    selectInput("Hypocone_uRM2","Hypocone",c("None,site smooth"=0,"Faint ridging"=1,"Faint cuspule"=2,"Small cusp"=3,"Moderate cusp"=3.5,"Large cusp"=4,"Very large cusp"=5)),
                                                    selectInput("Metaconule_uRM2","Metaconule/cusp 5",c("Site smooth,single distal groove separating cusps 3 & 4"=0,"Faint cuspule"=1,"Trace cuspule"=2,"Small cuspule"=3,"Small cusp"=4,"Medium cusp"=5)),
                                                    selectInput("Carabelli_uRM2","Carabelli's trait",c("Mesiolingual aspect of cusp1 smooth"=0,"Groove"=1,"Pit"=2,"Small Y-shaped depression"=3,"Large Y-shaped depression"=4,"Small cusp without free apex. Distal border not contacting lingual grove between cusps 1 & 4"=5,"Medium cusp with attached apex making contact with medial lingual groove"=6,"Large free cusp"=7)),
                                                    selectInput("extensions_uRM2","Enamel Extensions",c("Enamel border straight/ curved towards crown(rarly)"=0,"Faint (~1mm) extension projecting towards & along root"=1,"Medium (~2mm) exension"=2,"Lengthy (>4mm) exension, may extend to root bifurcation"=3)),
                                                    h5("nb score any extension not attached to crown as absent")),
                                   conditionalPanel("input.u_present.indexOf('RM1') >=0",
                                                    h4("upper RM1"),
                                                    selectInput("Hypocone_uRM1","Hypocone",c("None,site smooth"=0,"Faint ridging"=1,"Faint cuspule"=2,"Small cusp"=3,"Moderate cusp"=3.5,"Large cusp"=4,"Very large cusp"=5)),
                                                    selectInput("Metaconule_uRM1","Metaconule/cusp 5",c("Site smooth,single distal groove separating cusps 3 & 4"=0,"Faint cuspule"=1,"Trace cuspule"=2,"Small cuspule"=3,"Small cusp"=4,"Medium cusp"=5)),
                                                    selectInput("Carabelli_uRM1","Carabelli's trait",c("Mesiolingual aspect of cusp1 smooth"=0,"Groove"=1,"Pit"=2,"Small Y-shaped depression"=3,"Large Y-shaped depression"=4,"Small cusp without free apex. Distal border not contacting lingual grove between cusps 1 & 4"=5,"Medium cusp with attached apex making contact with medial lingual groove"=6,"Large free cusp"=7)),
                                                    selectInput("extensions_uRM1","Enamel Extensions",c("Enamel border straight/ curved towards crown(rarly)"=0,"Faint (~1mm) extension projecting towards & along root"=1,"Medium (~2mm) exension"=2,"Lengthy (>4mm) exension, may extend to root bifurcation"=3)),
                                                    h5("nb score any extension not attached to crown as absent")),
                                   conditionalPanel("input.u_present.indexOf('LM1') >=0",
                                                    h4("upper LM1"),
                                                    selectInput("Hypocone_uLM1","Hypocone",c("None,site smooth"=0,"Faint ridging"=1,"Faint cuspule"=2,"Small cusp"=3,"Moderate cusp"=3.5,"Large cusp"=4,"Very large cusp"=5)),
                                                    selectInput("Metaconule_uLM1","Metaconule/cusp 5",c("Site smooth,single distal groove separating cusps 3 & 4"=0,"Faint cuspule"=1,"Trace cuspule"=2,"Small cuspule"=3,"Small cusp"=4,"Medium cusp"=5)),
                                                    selectInput("Carabelli_uLM1","Carabelli's trait",c("Mesiolingual aspect of cusp1 smooth"=0,"Groove"=1,"Pit"=2,"Small Y-shaped depression"=3,"Large Y-shaped depression"=4,"Small cusp without free apex. Distal border not contacting lingual grove between cusps 1 & 4"=5,"Medium cusp with attached apex making contact with medial lingual groove"=6,"Large free cusp"=7)),
                                                    selectInput("extensions_uLM1","Enamel Extensions",c("Enamel border straight/ curved towards crown(rarly)"=0,"Faint (~1mm) extension projecting towards & along root"=1,"Medium (~2mm) exension"=2,"Lengthy (>4mm) exension, may extend to root bifurcation"=3)),
                                                    h5("nb score any extension not attached to crown as absent")),
                                   conditionalPanel("input.u_present.indexOf('LM2') >=0",
                                                    h4("upper LM2"),
                                                    selectInput("Hypocone_uLM2","Hypocone",c("None,site smooth"=0,"Faint ridging"=1,"Faint cuspule"=2,"Small cusp"=3,"Moderate cusp"=3.5,"Large cusp"=4,"Very large cusp"=5)),
                                                    selectInput("Metaconule_uLM2","Metaconule/cusp 5",c("Site smooth,single distal groove separating cusps 3 & 4"=0,"Faint cuspule"=1,"Trace cuspule"=2,"Small cuspule"=3,"Small cusp"=4,"Medium cusp"=5)),
                                                    selectInput("Carabelli_uLM2","Carabelli's trait",c("Mesiolingual aspect of cusp1 smooth"=0,"Groove"=1,"Pit"=2,"Small Y-shaped depression"=3,"Large Y-shaped depression"=4,"Small cusp without free apex. Distal border not contacting lingual grove between cusps 1 & 4"=5,"Medium cusp with attached apex making contact with medial lingual groove"=6,"Large free cusp"=7)),
                                                    selectInput("extensions_uLM2","Enamel Extensions",c("Enamel border straight/ curved towards crown(rarly)"=0,"Faint (~1mm) extension projecting towards & along root"=1,"Medium (~2mm) exension"=2,"Lengthy (>4mm) exension, may extend to root bifurcation"=3)),
                                                    h5("nb score any extension not attached to crown as absent")),
                                   conditionalPanel("input.u_present.indexOf('LM3') >=0",
                                                    h4("upper LM3"),
                                                    selectInput("Hypocone_uLM3","Hypocone",c("None,site smooth"=0,"Faint ridging"=1,"Faint cuspule"=2,"Small cusp"=3,"Moderate cusp"=3.5,"Large cusp"=4,"Very large cusp"=5)),
                                                    selectInput("Metaconule_uLM3","Metaconule/cusp 5",c("Site smooth,single distal groove separating cusps 3 & 4"=0,"Faint cuspule"=1,"Trace cuspule"=2,"Small cuspule"=3,"Small cusp"=4,"Medium cusp"=5)),
                                                    selectInput("Carabelli_uLM3","Carabelli's trait",c("Mesiolingual aspect of cusp1 smooth"=0,"Groove"=1,"Pit"=2,"Small Y-shaped depression"=3,"Large Y-shaped depression"=4,"Small cusp without free apex. Distal border not contacting lingual grove between cusps 1 & 4"=5,"Medium cusp with attached apex making contact with medial lingual groove"=6,"Large free cusp"=7)),
                                                    selectInput("extensions_uLM3","Enamel Extensions",c("Enamel border straight/ curved towards crown(rarly)"=0,"Faint (~1mm) extension projecting towards & along root"=1,"Medium (~2mm) exension"=2,"Lengthy (>4mm) exension, may extend to root bifurcation"=3)),
                                                    h5("nb score any extension not attached to crown as absent")),
                                   h1(br()),
                                   h1(br()),
                                   h1(br()),
                                   h1(br())
                                   ),
                            column(width=3,
                                   h3(br()),
                                   conditionalPanel("input.L_present.indexOf('RM3') >=0",
                                                    h4("lower RM3"),
                                                    selectInput("Groove_lRM3","Groove pattern",c("Cusps 2 and 3 in contact(Y)"="Y","Cusps 1,2,3 and 4 in contact(+)"="+","Cusps 1 and 4 in contact(X)"="X")),
                                                    h5("nb Determination should be aided by the use of a 10x hand lens"),
                                                    selectInput("nCusp_lRM3","Cusp number",c("4 (protoconid,metaconid,Hypoconid & entoconid)"=4,"5(4+Hypoconulid)"=5,"6(5+entoconulid)"=6)),
                                                    selectInput("Protostylid_lRM3","Protostylid",c("No expression of any sort"=0,"Pit in buccal groove"=1,"Buccal groove curves distally"=2,"Faint secondary groove extending mesially"=3,"More pronounced secondary groove"=4,"Secondary groove stronger, easily seen"=5,"Secondary groove extends across most of buccal surface of cusp1"=6,"Cusp with free apex"=7)),
                                                    selectInput("Hypoconulid_lRM3","Hypoconulid/cusp5",c("Absent"=0,"Present and very small"=1,"Small"=2,"Medium"=3,"Large"=4,"Very large"=5)),
                                                    selectInput("Entoconulid_lRM3","Entoconulid/cusp6",c("Absent"=0,"Much smaller than cusp 5"=1,"Smaller than cusp 5"=2,"Equal to cusp 5"=3,"Larger than cusp 5"=4,"Much larger than cusp 5"=5)),
                                                    selectInput("Metaconulid_lRM3","Metaconculid/cusp7",c("Absent"=0,"Faint cusp, two weak lingual grooves instead on one"=1,"faint tipless cusp, displaced as a bulge on the lingual surface of cusp 2"=1.5,"Small cusp"=2,"Medium cusp"=3,"Large cusp"=4)),
                                                    selectInput("nroot_lRM3","Root number",c("One: tip may be bifurcated <1/4 of total length"=1,"Two:Separate for >1/4 of total length"=2,"Three:separate root on distolingual aspect"=3))),
                                   conditionalPanel("input.L_present.indexOf('RM2') >=0",
                                                    h4("lower RM2"),
                                                    selectInput("Groove_lRM2","Groove pattern",c("Cusps 2 and 3 in contact(Y)"="Y","Cusps 1,2,3 and 4 in contact(+)"="+","Cusps 1 and 4 in contact(X)"="X")),
                                                    h5("nb Determination should be aided by the use of a 10x hand lens"),
                                                    selectInput("nCusp_lRM2","Cusp number",c("4 (protoconid,metaconid,Hypoconid & entoconid)"=4,"5(4+Hypoconulid)"=5,"6(5+entoconulid)"=6)),
                                                    selectInput("Protostylid_lRM2","Protostylid",c("No expression of any sort"=0,"Pit in buccal groove"=1,"Buccal groove curves distally"=2,"Faint secondary groove extending mesially"=3,"More pronounced secondary groove"=4,"Secondary groove stronger, easily seen"=5,"Secondary groove extends across most of buccal surface of cusp1"=6,"Cusp with free apex"=7)),
                                                    selectInput("Hypoconulid_lRM2","Hypoconulid/cusp5",c("Absent"=0,"Present and very small"=1,"Small"=2,"Medium"=3,"Large"=4,"Very large"=5)),
                                                    selectInput("Entoconulid_lRM2","Entoconulid/cusp6",c("Absent"=0,"Much smaller than cusp 5"=1,"Smaller than cusp 5"=2,"Equal to cusp 5"=3,"Larger than cusp 5"=4,"Much larger than cusp 5"=5)),
                                                    selectInput("Metaconulid_lRM2","Metaconculid/cusp7",c("Absent"=0,"Faint cusp, two weak lingual grooves instead on one"=1,"faint tipless cusp, displaced as a bulge on the lingual surface of cusp 2"=1.5,"Small cusp"=2,"Medium cusp"=3,"Large cusp"=4)),
                                                    selectInput("nroot_lRM2","Root number",c("One: tip may be bifurcated <1/4 of total length"=1,"Two:Separate for >1/4 of total length"=2,"Three:separate root on distolingual aspect"=3))),
                                   conditionalPanel("input.L_present.indexOf('RM1') >=0",
                                                    h4("lower RM1"),
                                                    selectInput("Groove_lRM1","Groove pattern",c("Cusps 2 and 3 in contact(Y)"="Y","Cusps 1,2,3 and 4 in contact(+)"="+","Cusps 1 and 4 in contact(X)"="X")),
                                                    h5("nb Determination should be aided by the use of a 10x hand lens"),
                                                    selectInput("nCusp_lRM1","Cusp number",c("4 (protoconid,metaconid,Hypoconid & entoconid)"=4,"5(4+Hypoconulid)"=5,"6(5+entoconulid)"=6)),
                                                    selectInput("Protostylid_lRM1","Protostylid",c("No expression of any sort"=0,"Pit in buccal groove"=1,"Buccal groove curves distally"=2,"Faint secondary groove extending mesially"=3,"More pronounced secondary groove"=4,"Secondary groove stronger, easily seen"=5,"Secondary groove extends across most of buccal surface of cusp1"=6,"Cusp with free apex"=7)),
                                                    selectInput("Hypoconulid_lRM1","Hypoconulid/cusp5",c("Absent"=0,"Present and very small"=1,"Small"=2,"Medium"=3,"Large"=4,"Very large"=5)),
                                                    selectInput("Entoconulid_lRM1","Entoconulid/cusp6",c("Absent"=0,"Much smaller than cusp 5"=1,"Smaller than cusp 5"=2,"Equal to cusp 5"=3,"Larger than cusp 5"=4,"Much larger than cusp 5"=5)),
                                                    selectInput("Metaconulid_lRM1","Metaconculid/cusp7",c("Absent"=0,"Faint cusp, two weak lingual grooves instead on one"=1,"faint tipless cusp, displaced as a bulge on the lingual surface of cusp 2"=1.5,"Small cusp"=2,"Medium cusp"=3,"Large cusp"=4)),
                                                    selectInput("nroot_lRM1","Root number",c("One: tip may be bifurcated <1/4 of total length"=1,"Two:Separate for >1/4 of total length"=2,"Three:separate root on distolingual aspect"=3))),
                                   conditionalPanel("input.L_present.indexOf('LM1') >=0",
                                                    h4("lower LM1"),
                                                    selectInput("Groove_lLM1","Groove pattern",c("Cusps 2 and 3 in contact(Y)"="Y","Cusps 1,2,3 and 4 in contact(+)"="+","Cusps 1 and 4 in contact(X)"="X")),
                                                    h5("nb Determination should be aided by the use of a 10x hand lens"),
                                                    selectInput("nCusp_lLM1","Cusp number",c("4 (protoconid,metaconid,Hypoconid & entoconid)"=4,"5(4+Hypoconulid)"=5,"6(5+entoconulid)"=6)),
                                                    selectInput("Protostylid_lLM1","Protostylid",c("No expression of any sort"=0,"Pit in buccal groove"=1,"Buccal groove curves distally"=2,"Faint secondary groove extending mesially"=3,"More pronounced secondary groove"=4,"Secondary groove stronger, easily seen"=5,"Secondary groove extends across most of buccal surface of cusp1"=6,"Cusp with free apex"=7)),
                                                    selectInput("Hypoconulid_lLM1","Hypoconulid/cusp5",c("Absent"=0,"Present and very small"=1,"Small"=2,"Medium"=3,"Large"=4,"Very large"=5)),
                                                    selectInput("Entoconulid_lLM1","Entoconulid/cusp6",c("Absent"=0,"Much smaller than cusp 5"=1,"Smaller than cusp 5"=2,"Equal to cusp 5"=3,"Larger than cusp 5"=4,"Much larger than cusp 5"=5)),
                                                    selectInput("Metaconulid_lLM1","Metaconculid/cusp7",c("Absent"=0,"Faint cusp, two weak lingual grooves instead on one"=1,"faint tipless cusp, displaced as a bulge on the lingual surface of cusp 2"=1.5,"Small cusp"=2,"Medium cusp"=3,"Large cusp"=4)),
                                                    selectInput("nroot_lLM1","Root number",c("One: tip may be bifurcated <1/4 of total length"=1,"Two:Separate for >1/4 of total length"=2,"Three:separate root on distolingual aspect"=3))),
                                   conditionalPanel("input.L_present.indexOf('LM2') >=0",
                                                    h4("lower LM2"),
                                                    selectInput("Groove_lLM2","Groove pattern",c("Cusps 2 and 3 in contact(Y)"="Y","Cusps 1,2,3 and 4 in contact(+)"="+","Cusps 1 and 4 in contact(X)"="X")),
                                                    h5("nb Determination should be aided by the use of a 10x hand lens"),
                                                    selectInput("nCusp_lLM2","Cusp number",c("4 (protoconid,metaconid,Hypoconid & entoconid)"=4,"5(4+Hypoconulid)"=5,"6(5+entoconulid)"=6)),
                                                    selectInput("Protostylid_lLM2","Protostylid",c("No expression of any sort"=0,"Pit in buccal groove"=1,"Buccal groove curves distally"=2,"Faint secondary groove extending mesially"=3,"More pronounced secondary groove"=4,"Secondary groove stronger, easily seen"=5,"Secondary groove extends across most of buccal surface of cusp1"=6,"Cusp with free apex"=7)),
                                                    selectInput("Hypoconulid_lLM2","Hypoconulid/cusp5",c("Absent"=0,"Present and very small"=1,"Small"=2,"Medium"=3,"Large"=4,"Very large"=5)),
                                                    selectInput("Entoconulid_lLM2","Entoconulid/cusp6",c("Absent"=0,"Much smaller than cusp 5"=1,"Smaller than cusp 5"=2,"Equal to cusp 5"=3,"Larger than cusp 5"=4,"Much larger than cusp 5"=5)),
                                                    selectInput("Metaconulid_lLM2","Metaconculid/cusp7",c("Absent"=0,"Faint cusp, two weak lingual grooves instead on one"=1,"faint tipless cusp, displaced as a bulge on the lingual surface of cusp 2"=1.5,"Small cusp"=2,"Medium cusp"=3,"Large cusp"=4)),
                                                    selectInput("nroot_lLM2","Root number",c("One: tip may be bifurcated <1/4 of total length"=1,"Two:Separate for >1/4 of total length"=2,"Three:separate root on distolingual aspect"=3))),
                                   conditionalPanel("input.L_present.indexOf('LM3') >=0",
                                                    h4("lower LM3"),
                                                    selectInput("Groove_lLM3","Groove pattern",c("Cusps 2 and 3 in contact(Y)"="Y","Cusps 1,2,3 and 4 in contact(+)"="+","Cusps 1 and 4 in contact(X)"="X")),
                                                    h5("nb Determination should be aided by the use of a 10x hand lens"),
                                                    selectInput("nCusp_lLM3","Cusp number",c("4 (protoconid,metaconid,Hypoconid & entoconid)"=4,"5(4+Hypoconulid)"=5,"6(5+entoconulid)"=6)),
                                                    selectInput("Protostylid_lLM3","Protostylid",c("No expression of any sort"=0,"Pit in buccal groove"=1,"Buccal groove curves distally"=2,"Faint secondary groove extending mesially"=3,"More pronounced secondary groove"=4,"Secondary groove stronger, easily seen"=5,"Secondary groove extends across most of buccal surface of cusp1"=6,"Cusp with free apex"=7)),
                                                    selectInput("Hypoconulid_lLM3","Hypoconulid/cusp5",c("Absent"=0,"Present and very small"=1,"Small"=2,"Medium"=3,"Large"=4,"Very large"=5)),
                                                    selectInput("Entoconulid_lLM3","Entoconulid/cusp6",c("Absent"=0,"Much smaller than cusp 5"=1,"Smaller than cusp 5"=2,"Equal to cusp 5"=3,"Larger than cusp 5"=4,"Much larger than cusp 5"=5)),
                                                    selectInput("Metaconulid_lLM3","Metaconculid/cusp7",c("Absent"=0,"Faint cusp, two weak lingual grooves instead on one"=1,"faint tipless cusp, displaced as a bulge on the lingual surface of cusp 2"=1.5,"Small cusp"=2,"Medium cusp"=3,"Large cusp"=4)),
                                                    selectInput("nroot_lLM3","Root number",c("One: tip may be bifurcated <1/4 of total length"=1,"Two:Separate for >1/4 of total length"=2,"Three:separate root on distolingual aspect"=3))),
                                   h1(br()),
                                   h1(br()),
                                   h1(br()),
                                   h1(br())
                                   )),
                   tabPanel("Growth",#Growth####
                            #h3(textOutput("Growth")),
                            column(width=4,
                                   selectInput("eruption","Stage of eruption and formation.(figure 24 Buiskra &Uberlaker,1994)",c("One:5 months in utero (+-2m)"=1,"Two:7 months in utero (+-2m)"=2,"Three:Birth(+-2m)"=3,"Four:6 months(+-3m)"=4,"Five:9 months(+-3m)"=5,"Six:1year(+-4m)"=6,"Seven:18 months(+-6m)"=7,
                                                                                                                                  "Eight:2 years(+-8m)"=8,"Nine:3 years(+-12m)"=9,"Ten:4 years(+-12m)"=10,"Eleven:5 years(+-16m)"=11,"Twelve:6 Years(+-24m)"=12,"Thirteen:7 years(+-24m)"=13,"Fourteen:8 years(+-24m)"=14,
                                                                                                                                  "Fifteen:9 years(+-24m)"=15,"Sixteen:10 years(+-30m)"=16,"Seventeen:11 years(+-30m)"=17,"Eighteen:12 years(+-36m)"=18,"Ninteen:15 years(+-36m)"=19,"Twenty:21 years"=20,"Twentyone:35 years"=21),selected=20)),
                            column(width=4,
                                   h3("Deciduous mandibular tooth formation"),
                                   conditionalPanel("input.Ld_present.indexOf('RdC1') >=0",selectInput("formation_lRdC1","RdC1",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                        "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.Ld_present.indexOf('LdC1') >=0",selectInput("formation_lLdC1","LdC1",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                        "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.Ld_present.indexOf('RdM1') >=0",selectInput("formation_lRdM1","RdM1",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                        "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.Ld_present.indexOf('LdM1') >=0",selectInput("formation_lLdM1","LdM1",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                        "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.Ld_present.indexOf('RdM2') >=0",selectInput("formation_lRdM2","RdM2",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                        "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.Ld_present.indexOf('LdM2') >=0",selectInput("formation_lLdM2","LdM2",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                        "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   h1(br()),
                                   h1(br()),
                                   h1(br()),
                                   h1(br())),
                            column(width=4,
                                   h3("Perminant mandibular tooth formation"),
                                   conditionalPanel("input.L_present.indexOf('RM1') >=0",selectInput("formation_lRM1","RM1",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                  "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.L_present.indexOf('LM1') >=0",selectInput("formation_lLM1","LM1",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                  "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.L_present.indexOf('RM2') >=0",selectInput("formation_lRM2","RM2",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                  "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.L_present.indexOf('LM2') >=0",selectInput("formation_lLM2","LM2",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                                  "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.L_present.indexOf('RM3') >=0",selectInput("formation_lRM3","RM3",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                              "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   conditionalPanel("input.L_present.indexOf('LM3') >=0",selectInput("formation_lLM3","LM3",c("Inital cusp formation"=1,"Coalescence of cusps"=2,"Cusp outline complete"=3,"Crown 1/2 complete"=4,"Crown 1/4 complete"=5,"Crown complete"=6,"Intial root formation"=7,
                                                                                                                              "Intial cleft formation"=8,"Root length 1/4"=9,"Root length 1/2"=10,"Root length 3/4"=11,"Root length complete"=12,"Apex 1/2 closed"=13,"Apex closed"=14),selected=14)),
                                   h1(br()),
                                   h1(br()),
                                   h1(br()),
                                   h1(br()))
                            ),
                   tabPanel("Write",#Write####
                            textInput("dir","Data Folder",value="../../data/"),
                            column(width=4,
                                   h3("Population Info"),
                                   textInput("POPID","Population ID",value="NA"),
                                   textInput("POPName","Population name",value="NA"),
                                   textInput("Person1","Investigator",value="NA"),
                                   actionButton("Create","Create new file"),
                                   h4(textOutput("PMessage"))
                            ),
                            column(width=4,
                                   h3("Individual Info"),
                                   textInput("ID","Individual ID",value="NA"),
                                   textInput("Person2","Investigator intials",value="NA"),
                                   actionButton("Append","Add individual"),
                                   h4(textOutput("IMessage"))
                            ),
                            column(width=4,
                                   h3("Compatability check"),
                                   actionButton("Compat","Check file"),
                                   h4(textOutput("ComMessage"))
                            )
                   )
                   ))